# Generated by Django 5.2.9 on 2026-01-23 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplianceAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the compliance assessment", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the assessment scope and objectives",
                        null=True,
                    ),
                ),
                (
                    "assessment_id",
                    models.CharField(
                        help_text="Unique assessment identifier (e.g., CMP-2024-001)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        help_text="Assessment scope (e.g., 'Enterprise', 'System', 'Department')",
                        max_length=100,
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("gap_analysis", "Gap Analysis"),
                            ("full_assessment", "Full Assessment"),
                            ("targeted_review", "Targeted Review"),
                            ("continuous_monitoring", "Continuous Monitoring"),
                            ("certification_prep", "Certification Preparation"),
                        ],
                        default="full_assessment",
                        help_text="Type of compliance assessment",
                        max_length=50,
                    ),
                ),
                (
                    "primary_framework",
                    models.CharField(
                        help_text="Primary compliance framework (e.g., 'NIST SP 800-53', 'ISO 27001')",
                        max_length=100,
                    ),
                ),
                (
                    "framework_version",
                    models.CharField(
                        blank=True,
                        help_text="Framework version or revision",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "additional_frameworks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional frameworks included in this assessment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("evidence_collection", "Evidence Collection"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("superseded", "Superseded"),
                        ],
                        default="planned",
                        help_text="Current status of the assessment",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        help_text="Assessment priority",
                        max_length=10,
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(
                        blank=True, help_text="Planned assessment start date", null=True
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, help_text="Actual assessment start date", null=True
                    ),
                ),
                (
                    "planned_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Planned assessment completion date",
                        null=True,
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual assessment completion date",
                        null=True,
                    ),
                ),
                (
                    "assessment_lead_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of the assessment lead",
                        null=True,
                    ),
                ),
                (
                    "assessment_lead_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of the assessment lead",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "assessment_team",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Assessment team members and their roles",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("system", "System"),
                            ("asset", "Asset"),
                            ("process", "Process"),
                            ("department", "Department"),
                            ("project", "Project"),
                        ],
                        help_text="Type of target being assessed",
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(
                        db_index=True, help_text="ID of the target being assessed"
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        help_text="Cached name of the assessment target", max_length=255
                    ),
                ),
                (
                    "included_scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Specific scopes included in the assessment",
                    ),
                ),
                (
                    "excluded_scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Scopes explicitly excluded from assessment",
                    ),
                ),
                (
                    "assessment_boundaries",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of assessment boundaries",
                        null=True,
                    ),
                ),
                (
                    "requirement_assessment_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of requirement assessments in this compliance assessment",
                    ),
                ),
                (
                    "control_assessment_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of control assessments in this compliance assessment",
                    ),
                ),
                (
                    "evidence_collection_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of evidence collections for this assessment",
                    ),
                ),
                (
                    "required_evidence_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Types of evidence required for this assessment",
                    ),
                ),
                (
                    "compliance_finding_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of findings from this assessment",
                    ),
                ),
                (
                    "compliance_exception_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of exceptions granted for this assessment",
                    ),
                ),
                (
                    "overall_compliance_score",
                    models.FloatField(
                        default=0.0, help_text="Overall compliance score (0.0-100.0)"
                    ),
                ),
                (
                    "compliance_level",
                    models.CharField(
                        choices=[
                            ("non_compliant", "Non-Compliant"),
                            ("limited", "Limited"),
                            ("moderate", "Moderate"),
                            ("substantial", "Substantial"),
                            ("full", "Full"),
                        ],
                        default="limited",
                        help_text="Overall compliance level",
                        max_length=20,
                    ),
                ),
                (
                    "total_requirements",
                    models.IntegerField(
                        default=0, help_text="Total number of requirements in scope"
                    ),
                ),
                (
                    "assessed_requirements",
                    models.IntegerField(
                        default=0, help_text="Number of requirements assessed"
                    ),
                ),
                (
                    "compliant_requirements",
                    models.IntegerField(
                        default=0, help_text="Number of requirements found compliant"
                    ),
                ),
                (
                    "non_compliant_requirements",
                    models.IntegerField(
                        default=0,
                        help_text="Number of requirements found non-compliant",
                    ),
                ),
                (
                    "not_applicable_requirements",
                    models.IntegerField(
                        default=0,
                        help_text="Number of requirements deemed not applicable",
                    ),
                ),
                (
                    "compensating_controls_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of compensating controls identified",
                    ),
                ),
                (
                    "risk_assessment_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of risk assessments related to this compliance assessment",
                    ),
                ),
                (
                    "residual_risks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Residual risks identified during assessment",
                    ),
                ),
                (
                    "approval_required",
                    models.BooleanField(
                        default=True, help_text="Whether formal approval is required"
                    ),
                ),
                (
                    "approved_by_user_id",
                    models.UUIDField(
                        blank=True, help_text="User ID of the approver", null=True
                    ),
                ),
                (
                    "approved_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of the approver",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, help_text="Date of formal approval", null=True
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from the approval process",
                        null=True,
                    ),
                ),
                (
                    "review_frequency",
                    models.CharField(
                        choices=[
                            ("continuous", "Continuous"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                            ("biennial", "Biennial"),
                        ],
                        default="annually",
                        help_text="Frequency of assessment reviews",
                        max_length=50,
                    ),
                ),
                (
                    "last_review_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last assessment review",
                        null=True,
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, help_text="Date of next scheduled review", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Notes from assessment reviews", null=True
                    ),
                ),
                (
                    "certification_body",
                    models.CharField(
                        blank=True,
                        help_text="Certification body or auditor",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "certification_standard",
                    models.CharField(
                        blank=True,
                        help_text="Specific certification standard",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "certification_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="not_started",
                        help_text="Certification status",
                        max_length=50,
                    ),
                ),
                (
                    "certification_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of certification achievement",
                        null=True,
                    ),
                ),
                (
                    "certification_expiry",
                    models.DateField(
                        blank=True, help_text="Date of certification expiry", null=True
                    ),
                ),
                (
                    "related_asset_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related asset IDs from Asset context",
                    ),
                ),
                (
                    "related_control_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related control IDs from Control Library context",
                    ),
                ),
                (
                    "related_risk_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related risk IDs from Risk Registers context",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Assessment tags for organization",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional assessment properties",
                    ),
                ),
                (
                    "assessment_methodology",
                    models.TextField(
                        blank=True,
                        help_text="Detailed assessment methodology used",
                        null=True,
                    ),
                ),
                (
                    "tools_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tools and systems used in the assessment",
                    ),
                ),
                (
                    "regulatory_requirements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Regulatory requirements this assessment addresses",
                    ),
                ),
                (
                    "compliance_deadlines",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Important compliance deadlines",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_assessments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="comp_assess_status_idx"),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="comp_assess_target_idx",
                    ),
                    models.Index(
                        fields=["primary_framework"], name="comp_assess_framework_idx"
                    ),
                    models.Index(
                        fields=["assessment_lead_user_id"], name="comp_assess_lead_idx"
                    ),
                    models.Index(
                        fields=["planned_completion_date"], name="comp_assess_due_idx"
                    ),
                    models.Index(
                        fields=["overall_compliance_score"],
                        name="comp_assess_score_idx",
                    ),
                    models.Index(
                        fields=["certification_status"], name="comp_assess_cert_idx"
                    ),
                    models.Index(
                        fields=["next_review_date"], name="comp_assess_review_idx"
                    ),
                    models.Index(fields=["created_at"], name="comp_assess_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "compliance_assessment_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID of the compliance assessment this exception relates to",
                    ),
                ),
                (
                    "exception_id",
                    models.CharField(
                        help_text="Unique exception identifier (e.g., 'EXC-2024-001')",
                        max_length=100,
                    ),
                ),
                (
                    "exception_title",
                    models.CharField(
                        help_text="Title/summary of the exception", max_length=500
                    ),
                ),
                (
                    "exception_description",
                    models.TextField(
                        help_text="Detailed description of the exception request"
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("temporary_waiver", "Temporary Waiver"),
                            ("permanent_exception", "Permanent Exception"),
                            ("compensating_control", "Compensating Control"),
                            ("risk_acceptance", "Risk Acceptance"),
                            (
                                "alternative_implementation",
                                "Alternative Implementation",
                            ),
                            ("delayed_compliance", "Delayed Compliance"),
                        ],
                        default="temporary_waiver",
                        help_text="Type of compliance exception",
                        max_length=26,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        help_text="Compliance framework this exception relates to",
                        max_length=100,
                    ),
                ),
                (
                    "requirement_id",
                    models.CharField(
                        blank=True,
                        help_text="Specific requirement identifier (e.g., 'AC-1')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "requirement_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the related requirement",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        help_text="Current status of the exception",
                        max_length=15,
                    ),
                ),
                (
                    "business_justification",
                    models.TextField(
                        help_text="Business justification for the exception"
                    ),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Risk assessment supporting the exception",
                        null=True,
                    ),
                ),
                (
                    "impact_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Impact assessment of granting the exception",
                        null=True,
                    ),
                ),
                (
                    "compensating_controls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Compensating controls implemented",
                    ),
                ),
                (
                    "compensating_controls_effectiveness",
                    models.CharField(
                        choices=[
                            ("not_assessed", "Not Assessed"),
                            ("inadequate", "Inadequate"),
                            ("adequate", "Adequate"),
                            ("strong", "Strong"),
                            ("exceeds", "Exceeds Requirements"),
                        ],
                        default="not_assessed",
                        help_text="Effectiveness of compensating controls",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when exception becomes effective",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Date when exception expires", null=True
                    ),
                ),
                (
                    "auto_renewal",
                    models.BooleanField(
                        default=False, help_text="Whether exception auto-renews"
                    ),
                ),
                (
                    "renewal_period_months",
                    models.IntegerField(
                        blank=True, help_text="Auto-renewal period in months", null=True
                    ),
                ),
                (
                    "max_renewals",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of renewals allowed",
                        null=True,
                    ),
                ),
                (
                    "renewal_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times exception has been renewed",
                    ),
                ),
                (
                    "approval_required",
                    models.BooleanField(
                        default=True, help_text="Whether formal approval is required"
                    ),
                ),
                (
                    "approval_workflow",
                    models.CharField(
                        choices=[
                            ("single_approver", "Single Approver"),
                            ("dual_approval", "Dual Approval"),
                            ("committee_review", "Committee Review"),
                            ("board_approval", "Board Approval"),
                        ],
                        default="single_approver",
                        help_text="Approval workflow required",
                        max_length=50,
                    ),
                ),
                (
                    "approved_by_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of primary approver",
                        null=True,
                    ),
                ),
                (
                    "approved_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of primary approver",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, help_text="Date of primary approval", null=True
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(
                        blank=True, help_text="Notes from primary approval", null=True
                    ),
                ),
                (
                    "secondary_approved_by_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of secondary approver",
                        null=True,
                    ),
                ),
                (
                    "secondary_approved_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of secondary approver",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "secondary_approval_date",
                    models.DateField(
                        blank=True, help_text="Date of secondary approval", null=True
                    ),
                ),
                (
                    "secondary_approval_notes",
                    models.TextField(
                        blank=True, help_text="Notes from secondary approval", null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection", null=True
                    ),
                ),
                (
                    "rejected_by_user_id",
                    models.UUIDField(
                        blank=True,
                        help_text="User ID of person who rejected",
                        null=True,
                    ),
                ),
                (
                    "rejected_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of person who rejected",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "rejection_date",
                    models.DateField(
                        blank=True, help_text="Date of rejection", null=True
                    ),
                ),
                (
                    "requested_by_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of person who requested the exception",
                        null=True,
                    ),
                ),
                (
                    "requested_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of person who requested the exception",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "owned_by_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID responsible for exception management",
                        null=True,
                    ),
                ),
                (
                    "owned_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username responsible for exception management",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "monitoring_required",
                    models.BooleanField(
                        default=True, help_text="Whether ongoing monitoring is required"
                    ),
                ),
                (
                    "monitoring_frequency",
                    models.CharField(
                        choices=[
                            ("continuous", "Continuous"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        default="quarterly",
                        help_text="Frequency of exception monitoring",
                        max_length=20,
                    ),
                ),
                (
                    "last_review_date",
                    models.DateField(
                        blank=True, help_text="Date of last exception review", null=True
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, help_text="Date of next scheduled review", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Notes from exception reviews", null=True
                    ),
                ),
                (
                    "associated_risks",
                    models.JSONField(
                        blank=True, default=list, help_text="IDs of associated risks"
                    ),
                ),
                (
                    "risk_acceptance_level",
                    models.CharField(
                        choices=[
                            ("not_assessed", "Not Assessed"),
                            ("accepted", "Accepted"),
                            ("conditionally_accepted", "Conditionally Accepted"),
                            ("not_accepted", "Not Accepted"),
                        ],
                        default="not_assessed",
                        help_text="Level of risk acceptance",
                        max_length=22,
                    ),
                ),
                (
                    "risk_mitigation_plan",
                    models.TextField(
                        blank=True,
                        help_text="Plan to mitigate accepted risks",
                        null=True,
                    ),
                ),
                (
                    "implementation_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost of implementing exception/compensation",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "ongoing_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ongoing cost of maintaining exception",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "resource_impact",
                    models.TextField(
                        blank=True,
                        help_text="Impact on resources and operations",
                        null=True,
                    ),
                ),
                (
                    "supporting_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of supporting documents",
                    ),
                ),
                (
                    "evidence_of_effectiveness",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Evidence demonstrating exception effectiveness",
                    ),
                ),
                (
                    "related_finding_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of related compliance findings",
                    ),
                ),
                (
                    "related_requirement_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of related requirement assessments",
                    ),
                ),
                (
                    "related_control_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="IDs of related controls"
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True,
                        help_text="Conditions that must be met for exception to remain valid",
                        null=True,
                    ),
                ),
                (
                    "constraints",
                    models.TextField(
                        blank=True,
                        help_text="Constraints and limitations of the exception",
                        null=True,
                    ),
                ),
                (
                    "triggers_for_review",
                    models.TextField(
                        blank=True,
                        help_text="Triggers that would require exception review",
                        null=True,
                    ),
                ),
                (
                    "audit_trail",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Audit trail of changes and decisions",
                    ),
                ),
                (
                    "compliance_impact",
                    models.TextField(
                        blank=True,
                        help_text="Overall impact on compliance posture",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        help_text="Exception priority",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Exception category for organization",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Exception tags for organization",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional properties",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_exceptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["compliance_assessment_id"],
                        name="exception_assessment_idx",
                    ),
                    models.Index(fields=["status"], name="exception_status_idx"),
                    models.Index(fields=["exception_type"], name="exception_type_idx"),
                    models.Index(
                        fields=["approved_by_user_id"], name="exception_approver_idx"
                    ),
                    models.Index(fields=["end_date"], name="exception_expiry_idx"),
                    models.Index(
                        fields=["next_review_date"], name="exception_review_idx"
                    ),
                    models.Index(fields=["created_at"], name="exception_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "compliance_assessment_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID of the compliance assessment this finding belongs to",
                    ),
                ),
                (
                    "finding_id",
                    models.CharField(
                        help_text="Unique finding identifier (e.g., 'FIND-2024-001')",
                        max_length=100,
                    ),
                ),
                (
                    "finding_title",
                    models.CharField(
                        help_text="Title/summary of the finding", max_length=500
                    ),
                ),
                (
                    "finding_description",
                    models.TextField(help_text="Detailed description of the finding"),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("non_conformity", "Non-Conformity"),
                            ("observation", "Observation"),
                            (
                                "opportunity_for_improvement",
                                "Opportunity for Improvement",
                            ),
                            ("positive_finding", "Positive Finding"),
                            ("minor_deficiency", "Minor Deficiency"),
                            ("major_deficiency", "Major Deficiency"),
                        ],
                        default="non_conformity",
                        help_text="Type of finding",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("informational", "Informational"),
                        ],
                        default="medium",
                        help_text="Severity level of the finding",
                        max_length=15,
                    ),
                ),
                (
                    "impact_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the impact of this finding",
                        null=True,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        help_text="Compliance framework this finding relates to",
                        max_length=100,
                    ),
                ),
                (
                    "requirement_id",
                    models.CharField(
                        blank=True,
                        help_text="Specific requirement identifier (e.g., 'AC-1')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "requirement_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the related requirement",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("remediated", "Remediated"),
                            ("closed", "Closed"),
                            ("dismissed", "Dismissed"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        help_text="Current status of the finding",
                        max_length=15,
                    ),
                ),
                (
                    "root_cause",
                    models.TextField(
                        blank=True,
                        help_text="Root cause analysis of the finding",
                        null=True,
                    ),
                ),
                (
                    "immediate_cause",
                    models.TextField(
                        blank=True,
                        help_text="Immediate cause of the finding",
                        null=True,
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="Evidence supporting the finding",
                        null=True,
                    ),
                ),
                (
                    "supporting_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of supporting documents",
                    ),
                ),
                (
                    "remediation_required",
                    models.BooleanField(
                        default=True, help_text="Whether remediation is required"
                    ),
                ),
                (
                    "remediation_plan",
                    models.TextField(
                        blank=True, help_text="Detailed remediation plan", null=True
                    ),
                ),
                (
                    "remediation_steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Step-by-step remediation actions",
                    ),
                ),
                (
                    "remediation_owner_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID responsible for remediation",
                        null=True,
                    ),
                ),
                (
                    "remediation_owner_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of remediation owner",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "remediation_team",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Team members involved in remediation",
                    ),
                ),
                (
                    "remediation_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Deadline for remediation completion",
                        null=True,
                    ),
                ),
                (
                    "remediation_start_date",
                    models.DateField(
                        blank=True, help_text="Date remediation was started", null=True
                    ),
                ),
                (
                    "remediation_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Date remediation was completed",
                        null=True,
                    ),
                ),
                (
                    "remediation_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("deferred", "Deferred"),
                        ],
                        default="not_started",
                        help_text="Status of remediation efforts",
                        max_length=20,
                    ),
                ),
                (
                    "remediation_progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "associated_risks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of associated risks from Risk Registers",
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Risk score associated with this finding (0.0-100.0)",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated cost of remediation",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "estimated_effort_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated effort in person-days",
                        null=True,
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual cost incurred",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "actual_effort_days",
                    models.IntegerField(
                        blank=True, help_text="Actual effort in person-days", null=True
                    ),
                ),
                (
                    "verification_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether verification of remediation is required",
                    ),
                ),
                (
                    "verification_method",
                    models.TextField(
                        blank=True,
                        help_text="Method used to verify remediation",
                        null=True,
                    ),
                ),
                (
                    "verification_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of remediation verification",
                        null=True,
                    ),
                ),
                (
                    "verification_result",
                    models.CharField(
                        choices=[
                            ("not_verified", "Not Verified"),
                            ("verified_effective", "Verified Effective"),
                            ("verified_partially", "Verified Partially"),
                            ("not_effective", "Not Effective"),
                            ("cannot_verify", "Cannot Verify"),
                        ],
                        default="not_verified",
                        help_text="Result of remediation verification",
                        max_length=20,
                    ),
                ),
                (
                    "approval_required",
                    models.BooleanField(
                        default=False, help_text="Whether formal approval is required"
                    ),
                ),
                (
                    "approved_by_user_id",
                    models.UUIDField(
                        blank=True, help_text="User ID of the approver", null=True
                    ),
                ),
                (
                    "approved_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of the approver",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, help_text="Date of approval", null=True
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether follow-up monitoring is required",
                    ),
                ),
                (
                    "follow_up_frequency",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        default="none",
                        help_text="Frequency of follow-up monitoring",
                        max_length=20,
                    ),
                ),
                (
                    "next_follow_up_date",
                    models.DateField(
                        blank=True, help_text="Date of next follow-up", null=True
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from follow-up activities",
                        null=True,
                    ),
                ),
                (
                    "identified_by_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of person who identified the finding",
                        null=True,
                    ),
                ),
                (
                    "identified_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of person who identified the finding",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "assigned_to_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID assigned to address the finding",
                        null=True,
                    ),
                ),
                (
                    "assigned_to_username",
                    models.CharField(
                        blank=True,
                        help_text="Username assigned to address the finding",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Notes from reviews", null=True
                    ),
                ),
                (
                    "audit_trail",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Audit trail of changes and actions",
                    ),
                ),
                (
                    "related_requirement_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of related requirement assessments",
                    ),
                ),
                (
                    "related_control_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="IDs of related controls"
                    ),
                ),
                (
                    "related_asset_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="IDs of related assets"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Finding category for organization",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True,
                        help_text="Finding subcategory",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Finding tags for organization",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional properties",
                    ),
                ),
                (
                    "priority_score",
                    models.IntegerField(
                        default=0, help_text="Calculated priority score (auto-updated)"
                    ),
                ),
            ],
            options={
                "db_table": "compliance_findings",
                "ordering": ["-priority_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["compliance_assessment_id"],
                        name="finding_assessment_idx",
                    ),
                    models.Index(fields=["status"], name="finding_status_idx"),
                    models.Index(fields=["severity"], name="finding_severity_idx"),
                    models.Index(fields=["finding_type"], name="finding_type_idx"),
                    models.Index(
                        fields=["remediation_owner_user_id"], name="finding_owner_idx"
                    ),
                    models.Index(
                        fields=["remediation_deadline"], name="finding_deadline_idx"
                    ),
                    models.Index(
                        fields=["verification_result"], name="finding_verification_idx"
                    ),
                    models.Index(
                        fields=["priority_score"], name="finding_priority_idx"
                    ),
                    models.Index(fields=["created_at"], name="finding_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequirementAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "compliance_assessment_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID of the parent compliance assessment",
                    ),
                ),
                (
                    "requirement_id",
                    models.CharField(
                        help_text="Unique requirement identifier (e.g., 'AC-1', 'SI-3')",
                        max_length=100,
                    ),
                ),
                (
                    "requirement_title",
                    models.CharField(
                        help_text="Title/name of the requirement", max_length=500
                    ),
                ),
                (
                    "requirement_description",
                    models.TextField(help_text="Full description of the requirement"),
                ),
                (
                    "framework",
                    models.CharField(
                        help_text="Compliance framework (e.g., 'NIST SP 800-53', 'ISO 27001')",
                        max_length=100,
                    ),
                ),
                (
                    "framework_section",
                    models.CharField(
                        blank=True,
                        help_text="Framework section or category",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "framework_version",
                    models.CharField(
                        blank=True,
                        help_text="Framework version",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("evidence_collected", "Evidence Collected"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_started",
                        help_text="Current assessment status",
                        max_length=20,
                    ),
                ),
                (
                    "assessment_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("compensating_control", "Compensating Control"),
                            ("not_applicable", "Not Applicable"),
                            ("insufficient_evidence", "Insufficient Evidence"),
                        ],
                        help_text="Result of the requirement assessment",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "compliance_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Compliance score for this requirement (0.0-100.0)",
                    ),
                ),
                (
                    "assessment_notes",
                    models.TextField(
                        blank=True,
                        help_text="Detailed assessment notes and rationale",
                        null=True,
                    ),
                ),
                (
                    "assessment_methodology",
                    models.TextField(
                        blank=True,
                        help_text="Methodology used for assessment",
                        null=True,
                    ),
                ),
                (
                    "evidence_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of evidence items supporting this assessment",
                    ),
                ),
                (
                    "required_evidence_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Types of evidence required for compliance",
                    ),
                ),
                (
                    "evidence_sufficiency",
                    models.CharField(
                        choices=[
                            ("insufficient", "Insufficient"),
                            ("adequate", "Adequate"),
                            ("comprehensive", "Comprehensive"),
                        ],
                        default="insufficient",
                        help_text="Assessment of evidence sufficiency",
                        max_length=20,
                    ),
                ),
                (
                    "implemented_controls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Controls implemented to meet this requirement",
                    ),
                ),
                (
                    "compensating_controls",
                    models.JSONField(
                        blank=True, default=list, help_text="Compensating controls used"
                    ),
                ),
                (
                    "control_effectiveness",
                    models.CharField(
                        choices=[
                            ("not_implemented", "Not Implemented"),
                            ("partially_implemented", "Partially Implemented"),
                            ("fully_implemented", "Fully Implemented"),
                            ("exceeds_requirements", "Exceeds Requirements"),
                        ],
                        default="not_implemented",
                        help_text="Effectiveness of implemented controls",
                        max_length=21,
                    ),
                ),
                (
                    "associated_risks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Risks associated with non-compliance",
                    ),
                ),
                (
                    "risk_mitigation_effectiveness",
                    models.CharField(
                        choices=[
                            ("inadequate", "Inadequate"),
                            ("adequate", "Adequate"),
                            ("strong", "Strong"),
                        ],
                        default="adequate",
                        help_text="Effectiveness of risk mitigation",
                        max_length=20,
                    ),
                ),
                (
                    "assessor_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of the assessor",
                        null=True,
                    ),
                ),
                (
                    "assessor_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of the assessor",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "reviewer_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of the reviewer",
                        null=True,
                    ),
                ),
                (
                    "reviewer_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of the reviewer",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "assessment_start_date",
                    models.DateField(
                        blank=True, help_text="Date assessment was started", null=True
                    ),
                ),
                (
                    "assessment_completion_date",
                    models.DateField(
                        blank=True, help_text="Date assessment was completed", null=True
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True, help_text="Date of formal review", null=True
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, help_text="Date of approval", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the review process", null=True
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from the approval process",
                        null=True,
                    ),
                ),
                (
                    "remediation_required",
                    models.BooleanField(
                        default=False, help_text="Whether remediation is required"
                    ),
                ),
                (
                    "remediation_plan",
                    models.TextField(
                        blank=True, help_text="Detailed remediation plan", null=True
                    ),
                ),
                (
                    "remediation_owner_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID responsible for remediation",
                        null=True,
                    ),
                ),
                (
                    "remediation_owner_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of remediation owner",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "remediation_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Deadline for remediation completion",
                        null=True,
                    ),
                ),
                (
                    "remediation_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        help_text="Status of remediation efforts",
                        max_length=20,
                    ),
                ),
                (
                    "related_finding_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of related compliance findings",
                    ),
                ),
                (
                    "exception_granted",
                    models.BooleanField(
                        default=False, help_text="Whether an exception has been granted"
                    ),
                ),
                (
                    "exception_id",
                    models.UUIDField(
                        blank=True, help_text="ID of granted exception", null=True
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        help_text="Assessment priority",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Assessment tags for organization",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional properties",
                    ),
                ),
                (
                    "mapped_control_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of mapped controls from Control Library",
                    ),
                ),
                (
                    "mapped_risk_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of mapped risks from Risk Registers",
                    ),
                ),
            ],
            options={
                "db_table": "requirement_assessments",
                "ordering": ["framework", "requirement_id"],
                "indexes": [
                    models.Index(
                        fields=["compliance_assessment_id"],
                        name="req_assessment_parent_idx",
                    ),
                    models.Index(fields=["status"], name="req_assessment_status_idx"),
                    models.Index(
                        fields=["assessment_result"], name="req_assessment_result_idx"
                    ),
                    models.Index(
                        fields=["framework"], name="req_assessment_framework_idx"
                    ),
                    models.Index(
                        fields=["assessor_user_id"], name="req_assessment_assessor_idx"
                    ),
                    models.Index(
                        fields=["remediation_deadline"],
                        name="req_assessment_deadline_idx",
                    ),
                    models.Index(
                        fields=["compliance_score"], name="req_assessment_score_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="req_assessment_created_idx"
                    ),
                ],
                "unique_together": {("compliance_assessment_id", "requirement_id")},
            },
        ),
    ]
