# Generated by Django 5.2.9 on 2026-01-23 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BCPPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(help_text="Name of the BCP plan", max_length=255),
                ),
                (
                    "plan_description",
                    models.TextField(
                        help_text="Description of the BCP plan scope and objectives"
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(
                        help_text="Unique plan identifier (e.g., BCP-2024-001)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        help_text="Plan scope (e.g., 'Enterprise', 'Department', 'System')",
                        max_length=100,
                    ),
                ),
                (
                    "covered_processes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Business processes covered by this plan",
                    ),
                ),
                (
                    "covered_assets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Critical assets covered by this plan",
                    ),
                ),
                (
                    "geographical_scope",
                    models.CharField(
                        blank=True,
                        help_text="Geographical areas covered by the plan",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Current plan status",
                        max_length=15,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", help_text="Plan version", max_length=20
                    ),
                ),
                (
                    "plan_owner_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of plan owner",
                        null=True,
                    ),
                ),
                (
                    "plan_owner_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of plan owner",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "plan_coordinator_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of plan coordinator",
                        null=True,
                    ),
                ),
                (
                    "plan_coordinator_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of plan coordinator",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "risk_assessment",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Business impact analysis and risk assessment",
                    ),
                ),
                (
                    "bia_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether Business Impact Analysis is completed",
                    ),
                ),
                (
                    "bia_date",
                    models.DateField(
                        blank=True, help_text="Date BIA was completed", null=True
                    ),
                ),
                (
                    "recovery_strategies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recovery strategies for different scenarios",
                    ),
                ),
                (
                    "rto_objectives",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Recovery Time Objectives by process/asset",
                    ),
                ),
                (
                    "rpo_objectives",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Recovery Point Objectives by process/asset",
                    ),
                ),
                (
                    "emergency_contacts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Emergency contact information",
                    ),
                ),
                (
                    "response_procedures",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Incident response procedures",
                    ),
                ),
                (
                    "recovery_procedures",
                    models.JSONField(
                        blank=True, default=list, help_text="Recovery procedures"
                    ),
                ),
                (
                    "communication_plan",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Communication plan for stakeholders",
                    ),
                ),
                (
                    "test_schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Testing schedule and procedures",
                    ),
                ),
                (
                    "last_test_date",
                    models.DateField(
                        blank=True, help_text="Date of last plan test", null=True
                    ),
                ),
                (
                    "next_test_date",
                    models.DateField(
                        blank=True, help_text="Date of next scheduled test", null=True
                    ),
                ),
                (
                    "test_results",
                    models.JSONField(
                        blank=True, default=list, help_text="Results from plan tests"
                    ),
                ),
                (
                    "approved_by_user_id",
                    models.UUIDField(
                        blank=True, help_text="User ID of approver", null=True
                    ),
                ),
                (
                    "approved_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of approver",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, help_text="Date of plan approval", null=True
                    ),
                ),
                (
                    "review_schedule",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("biannual", "Biannual"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="annual",
                        help_text="Plan review frequency",
                        max_length=20,
                    ),
                ),
                (
                    "last_review_date",
                    models.DateField(
                        blank=True, help_text="Date of last plan review", null=True
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, help_text="Date of next scheduled review", null=True
                    ),
                ),
                (
                    "effectiveness_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("poor", "Poor"),
                            ("fair", "Fair"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        help_text="Overall plan effectiveness rating",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "improvement_areas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Identified areas for improvement",
                    ),
                ),
                (
                    "related_risks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related risks from Risk Registers",
                    ),
                ),
                (
                    "related_assets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related assets from Asset context",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Plan tags for organization"
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional properties",
                    ),
                ),
            ],
            options={
                "db_table": "bcp_plans",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="bcp_plan_status_idx"),
                    models.Index(fields=["scope"], name="bcp_plan_scope_idx"),
                    models.Index(
                        fields=["plan_owner_user_id"], name="bcp_plan_owner_idx"
                    ),
                    models.Index(fields=["next_test_date"], name="bcp_plan_test_idx"),
                    models.Index(
                        fields=["next_review_date"], name="bcp_plan_review_idx"
                    ),
                    models.Index(fields=["created_at"], name="bcp_plan_created_idx"),
                ],
            },
        ),
    ]
