# Generated by Django 5.2.9 on 2026-01-23 02:17

import core.domain.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "permissionIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of permission IDs"
                    ),
                ),
                (
                    "userIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of user IDs in this group"
                    ),
                ),
                (
                    "builtin",
                    models.BooleanField(
                        default=False, help_text="Built-in groups cannot be deleted"
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "db_table": "organization_groups",
                "indexes": [
                    models.Index(fields=["name"], name="organizatio_name_41869c_idx"),
                    models.Index(
                        fields=["lifecycle_state"],
                        name="organizatio_lifecyc_b9f501_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "parentOrgUnitId",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "childOrgUnitIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of child organizational unit IDs"
                    ),
                ),
                (
                    "ownerUserIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of owner user IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Organizational Unit",
                "verbose_name_plural": "Organizational Units",
                "db_table": "organization_org_units",
                "indexes": [
                    models.Index(
                        fields=["parentOrgUnitId", "lifecycle_state"],
                        name="organizatio_parentO_28cb3b_idx",
                    ),
                    models.Index(fields=["name"], name="organizatio_name_c6df10_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrgUnitOverview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("org_unit_id", models.UUIDField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("ref_id", models.CharField(blank=True, max_length=100, null=True)),
                ("lifecycle_state", models.CharField(db_index=True, max_length=20)),
                ("child_count", models.IntegerField(default=0)),
                ("owner_count", models.IntegerField(default=0)),
                ("user_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Org Unit Overview",
                "verbose_name_plural": "Org Unit Overviews",
                "db_table": "organization_org_unit_overviews",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="organizatio_lifecyc_93a4c3_idx",
                    ),
                    models.Index(fields=["name"], name="organizatio_name_f3c275_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResponsibilityAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("process", "Process"),
                            ("service", "Service"),
                            ("risk", "Risk"),
                            ("control", "Control"),
                            ("policy", "Policy"),
                            ("project", "Project"),
                            ("data_asset", "Data Asset"),
                            ("data_flow", "Data Flow"),
                            ("third_party", "Third Party"),
                            ("org_unit", "Organizational Unit"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("subject_id", models.UUIDField(db_index=True)),
                ("userId", models.UUIDField(db_index=True)),
                ("role", models.CharField(db_index=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Responsibility Assignment",
                "verbose_name_plural": "Responsibility Assignments",
                "db_table": "organization_responsibility_assignments",
                "indexes": [
                    models.Index(
                        fields=["subject_type", "subject_id"],
                        name="organizatio_subject_33dacf_idx",
                    ),
                    models.Index(
                        fields=["userId"], name="organizatio_userId_835bee_idx"
                    ),
                    models.Index(fields=["role"], name="organizatio_role_252b00_idx"),
                ],
                "unique_together": {("subject_type", "subject_id", "userId", "role")},
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="invited",
                        max_length=20,
                    ),
                ),
                (
                    "groupIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of group IDs the user belongs to"
                    ),
                ),
                (
                    "orgUnitIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True,
                        help_text="Array of organizational unit IDs the user belongs to",
                    ),
                ),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("observation", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "organization_users",
                "indexes": [
                    models.Index(fields=["email"], name="organizatio_email_63d23a_idx"),
                    models.Index(
                        fields=["lifecycle_state"],
                        name="organizatio_lifecyc_a0a3b2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserOverview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.UUIDField(db_index=True, unique=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lifecycle_state", models.CharField(db_index=True, max_length=20)),
                ("group_count", models.IntegerField(default=0)),
                ("org_unit_count", models.IntegerField(default=0)),
                ("responsibility_count", models.IntegerField(default=0)),
                ("group_names", models.JSONField(blank=True, default=list)),
                ("org_unit_names", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Overview",
                "verbose_name_plural": "User Overviews",
                "db_table": "organization_user_overviews",
                "indexes": [
                    models.Index(fields=["email"], name="organizatio_email_d742b7_idx"),
                    models.Index(
                        fields=["lifecycle_state"],
                        name="organizatio_lifecyc_097233_idx",
                    ),
                ],
            },
        ),
    ]
