# Generated by Django 5.2.9 on 2026-01-23 00:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0015_remove_databreach_new_assigned_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "consent_id",
                    models.CharField(
                        help_text="Unique consent identifier (e.g., CONS-2024-001)",
                        max_length=100,
                    ),
                ),
                (
                    "data_subject_id",
                    models.CharField(
                        help_text="Identifier for the data subject (e.g., user ID, email)",
                        max_length=255,
                    ),
                ),
                (
                    "data_subject_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("employee", "Employee"),
                            ("website_user", "Website User"),
                            ("prospect", "Prospect"),
                            ("supplier", "Supplier"),
                            ("other", "Other"),
                        ],
                        default="customer",
                        help_text="Type of data subject",
                        max_length=50,
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False, help_text="Whether consent has been given"
                    ),
                ),
                (
                    "consent_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when consent was given",
                        null=True,
                    ),
                ),
                (
                    "consent_method",
                    models.CharField(
                        choices=[
                            ("digital_signature", "Digital Signature"),
                            ("checkbox", "Checkbox/Click"),
                            ("written", "Written Consent"),
                            ("verbal", "Verbal Consent"),
                            ("implied", "Implied Consent"),
                            ("opt_in_email", "Opt-in Email"),
                            ("opt_in_form", "Opt-in Form"),
                        ],
                        help_text="Method used to obtain consent",
                        max_length=50,
                    ),
                ),
                (
                    "processing_purposes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Specific purposes for which consent is given",
                    ),
                ),
                (
                    "data_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Categories of personal data covered by consent",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Third parties that may receive the data",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date from which consent is valid",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date until which consent is valid",
                        null=True,
                    ),
                ),
                (
                    "is_permanent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether consent is permanent (no expiry)",
                    ),
                ),
                (
                    "withdrawn",
                    models.BooleanField(
                        default=False, help_text="Whether consent has been withdrawn"
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when consent was withdrawn",
                        null=True,
                    ),
                ),
                (
                    "withdrawal_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("digital_request", "Digital Request"),
                            ("email", "Email Request"),
                            ("phone", "Phone Request"),
                            ("written", "Written Request"),
                            ("account_deletion", "Account Deletion"),
                            ("unsubscribe", "Unsubscribe Link"),
                        ],
                        help_text="Method used to withdraw consent",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "withdrawal_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided for withdrawal",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("withdrawn", "Withdrawn"),
                            ("revoked", "Revoked"),
                            ("pending_verification", "Pending Verification"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending_verification",
                        help_text="Current status of the consent",
                        max_length=20,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Whether consent has been verified"
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when consent was verified",
                        null=True,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("automated", "Automated Verification"),
                            ("manual_review", "Manual Review"),
                            ("third_party", "Third Party Verification"),
                            ("legal_review", "Legal Review"),
                        ],
                        help_text="Method used to verify consent",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "consent_language",
                    models.CharField(
                        default="en",
                        help_text="Language in which consent was obtained",
                        max_length=10,
                    ),
                ),
                (
                    "consent_text",
                    models.TextField(
                        blank=True,
                        help_text="Full text of the consent statement",
                        null=True,
                    ),
                ),
                (
                    "privacy_policy_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of privacy policy at time of consent",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "terms_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of terms at time of consent",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "granular_consents",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Granular consent options (e.g., {'marketing': true, 'analytics': false})",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True,
                        help_text="System or application where consent was obtained",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "source_page",
                    models.CharField(
                        blank=True,
                        help_text="Page or form where consent was obtained",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        help_text="IP address from which consent was given",
                        max_length=45,
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string from consent submission",
                        null=True,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="Country code where consent was obtained",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Region/state where consent was obtained",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        choices=[
                            ("consent", "Consent (Article 6(1)(a))"),
                            ("contract", "Contract (Article 6(1)(b))"),
                            ("legal_obligation", "Legal Obligation (Article 6(1)(c))"),
                            ("vital_interests", "Vital Interests (Article 6(1)(d))"),
                            ("public_task", "Public Task (Article 6(1)(e))"),
                            (
                                "legitimate_interests",
                                "Legitimate Interests (Article 6(1)(f))",
                            ),
                        ],
                        default="consent",
                        help_text="Legal basis for processing",
                        max_length=50,
                    ),
                ),
                (
                    "legitimate_interests",
                    models.TextField(
                        blank=True,
                        help_text="Description of legitimate interests (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "special_category_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether consent includes special category data processing",
                    ),
                ),
                (
                    "special_category_legal_bases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Legal bases for special category data processing",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Consent record version"),
                ),
                (
                    "previous_versions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Previous versions of this consent record",
                    ),
                ),
                (
                    "created_by_system",
                    models.CharField(
                        blank=True,
                        help_text="System that created the consent record",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "last_modified_by",
                    models.CharField(
                        blank=True,
                        help_text="System/user that last modified the record",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "audit_trail",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Audit trail of changes to the consent record",
                    ),
                ),
                (
                    "related_data_assets",
                    models.JSONField(
                        blank=True, default=list, help_text="IDs of related data assets"
                    ),
                ),
                (
                    "related_processing_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of related processing activities",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Consent tags for organization",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional properties",
                    ),
                ),
            ],
            options={
                "db_table": "privacy_consent_records",
                "ordering": ["-consent_date"],
                "indexes": [
                    models.Index(
                        fields=["data_subject_id"], name="consent_subject_idx"
                    ),
                    models.Index(fields=["status"], name="consent_status_idx"),
                    models.Index(fields=["consent_date"], name="consent_date_idx"),
                    models.Index(fields=["valid_until"], name="consent_expiry_idx"),
                    models.Index(fields=["withdrawn"], name="consent_withdrawn_idx"),
                    models.Index(
                        fields=["legal_basis"], name="consent_legal_basis_idx"
                    ),
                    models.Index(fields=["source_system"], name="consent_source_idx"),
                    models.Index(fields=["created_at"], name="consent_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(
                        help_text="Name/identifier of the data asset", max_length=255
                    ),
                ),
                (
                    "asset_description",
                    models.TextField(
                        help_text="Description of the data asset and its contents"
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(
                        help_text="Unique asset identifier (e.g., DATA-PII-001)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "primary_data_category",
                    models.CharField(
                        choices=[
                            ("personal_data", "Personal Data"),
                            ("sensitive_personal_data", "Sensitive Personal Data"),
                            ("special_category_data", "Special Category Data"),
                            ("criminal_conviction_data", "Criminal Conviction Data"),
                            ("genetic_data", "Genetic Data"),
                            ("biometric_data", "Biometric Data"),
                            ("health_data", "Health Data"),
                            ("financial_data", "Financial Data"),
                            ("communication_data", "Communication Data"),
                            ("location_data", "Location Data"),
                            ("online_identifier_data", "Online Identifier Data"),
                            ("racial_ethnic_data", "Racial/Ethnic Origin Data"),
                            ("political_opinion_data", "Political Opinion Data"),
                            ("religious_belief_data", "Religious Belief Data"),
                            ("trade_union_data", "Trade Union Membership Data"),
                            ("sexual_orientation_data", "Sexual Orientation Data"),
                        ],
                        default="personal_data",
                        help_text="Primary category of personal data",
                        max_length=30,
                    ),
                ),
                (
                    "data_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="All applicable data categories for this asset",
                    ),
                ),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                            ("highly_restricted", "Highly Restricted"),
                        ],
                        default="confidential",
                        help_text="Privacy sensitivity level",
                        max_length=20,
                    ),
                ),
                (
                    "data_subject_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Types of data subjects (e.g., customers, employees, website visitors)",
                    ),
                ),
                (
                    "estimated_data_subjects",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated number of data subjects",
                        null=True,
                    ),
                ),
                (
                    "processing_purposes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Purposes for which the data is processed",
                    ),
                ),
                (
                    "legal_bases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Legal bases for processing (GDPR Article 6/9)",
                    ),
                ),
                (
                    "legitimate_interests",
                    models.TextField(
                        blank=True,
                        help_text="Description of legitimate interests for processing",
                        null=True,
                    ),
                ),
                (
                    "data_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sources from which data is collected",
                    ),
                ),
                (
                    "collection_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Methods used to collect the data",
                    ),
                ),
                (
                    "consent_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether consent is required for collection",
                    ),
                ),
                (
                    "consent_mechanisms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Mechanisms used to obtain consent",
                    ),
                ),
                (
                    "storage_locations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Locations where data is stored",
                    ),
                ),
                (
                    "retention_schedule",
                    models.TextField(
                        blank=True,
                        help_text="Data retention schedule and justification",
                        null=True,
                    ),
                ),
                (
                    "retention_period_days",
                    models.IntegerField(
                        blank=True, help_text="Retention period in days", null=True
                    ),
                ),
                (
                    "disposal_methods",
                    models.JSONField(
                        blank=True, default=list, help_text="Methods for data disposal"
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recipients or categories of recipients",
                    ),
                ),
                (
                    "third_party_processors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Third party processors involved",
                    ),
                ),
                (
                    "international_transfers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="International data transfers and safeguards",
                    ),
                ),
                (
                    "security_measures",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Security measures applied to protect the data",
                    ),
                ),
                (
                    "encryption_methods",
                    models.JSONField(
                        blank=True, default=list, help_text="Encryption methods used"
                    ),
                ),
                (
                    "access_controls",
                    models.JSONField(
                        blank=True, default=list, help_text="Access control measures"
                    ),
                ),
                (
                    "pia_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether Privacy Impact Assessment is required",
                    ),
                ),
                (
                    "pia_completed",
                    models.BooleanField(
                        default=False, help_text="Whether PIA has been completed"
                    ),
                ),
                (
                    "pia_date",
                    models.DateField(
                        blank=True, help_text="Date PIA was completed", null=True
                    ),
                ),
                (
                    "pia_findings",
                    models.TextField(
                        blank=True,
                        help_text="Key findings from Privacy Impact Assessment",
                        null=True,
                    ),
                ),
                (
                    "dpo_review_required",
                    models.BooleanField(
                        default=False, help_text="Whether DPO review is required"
                    ),
                ),
                (
                    "dpo_reviewed",
                    models.BooleanField(
                        default=False, help_text="Whether DPO has reviewed"
                    ),
                ),
                (
                    "dpo_review_date",
                    models.DateField(
                        blank=True, help_text="Date of DPO review", null=True
                    ),
                ),
                (
                    "dpo_comments",
                    models.TextField(
                        blank=True,
                        help_text="Comments from Data Protection Officer",
                        null=True,
                    ),
                ),
                (
                    "subject_rights_supported",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Data subject rights supported for this asset",
                    ),
                ),
                (
                    "right_of_access_mechanism",
                    models.TextField(
                        blank=True,
                        help_text="Mechanism for handling right of access requests",
                        null=True,
                    ),
                ),
                (
                    "right_of_rectification_mechanism",
                    models.TextField(
                        blank=True,
                        help_text="Mechanism for handling right of rectification requests",
                        null=True,
                    ),
                ),
                (
                    "right_of_erasure_mechanism",
                    models.TextField(
                        blank=True,
                        help_text="Mechanism for handling right of erasure requests",
                        null=True,
                    ),
                ),
                (
                    "privacy_risks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Privacy risks associated with this data asset",
                    ),
                ),
                (
                    "risk_mitigation_measures",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Risk mitigation measures implemented",
                    ),
                ),
                (
                    "residual_privacy_risks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Residual privacy risks after mitigation",
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("under_review", "Under Review"),
                            ("remediation_required", "Remediation Required"),
                            ("exempt", "Exempt"),
                        ],
                        default="under_review",
                        help_text="Current compliance status",
                        max_length=20,
                    ),
                ),
                (
                    "compliance_issues",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Outstanding compliance issues",
                    ),
                ),
                (
                    "last_audit_date",
                    models.DateField(
                        blank=True, help_text="Date of last privacy audit", null=True
                    ),
                ),
                (
                    "next_audit_date",
                    models.DateField(
                        blank=True, help_text="Date of next scheduled audit", null=True
                    ),
                ),
                (
                    "audit_findings",
                    models.TextField(
                        blank=True, help_text="Findings from privacy audits", null=True
                    ),
                ),
                (
                    "data_owner_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of the data owner",
                        null=True,
                    ),
                ),
                (
                    "data_owner_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of the data owner",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "data_steward_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of the data steward",
                        null=True,
                    ),
                ),
                (
                    "data_steward_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of the data steward",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "dpo_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of the Data Protection Officer",
                        null=True,
                    ),
                ),
                (
                    "dpo_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of the Data Protection Officer",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the system where data resides",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "database_name",
                    models.CharField(
                        blank=True,
                        help_text="Database where data is stored",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "table_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Database table names containing this data",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Asset tags for organization",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional properties",
                    ),
                ),
                (
                    "related_asset_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related asset IDs from Asset context",
                    ),
                ),
                (
                    "related_control_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related control IDs from Control Library",
                    ),
                ),
                (
                    "related_risk_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related risk IDs from Risk Registers",
                    ),
                ),
            ],
            options={
                "db_table": "privacy_module_data_assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["primary_data_category"], name="data_asset_category_idx"
                    ),
                    models.Index(
                        fields=["sensitivity_level"], name="data_asset_sensitivity_idx"
                    ),
                    models.Index(
                        fields=["compliance_status"], name="data_asset_compliance_idx"
                    ),
                    models.Index(fields=["pia_required"], name="data_asset_pia_idx"),
                    models.Index(
                        fields=["data_owner_user_id"], name="data_asset_owner_idx"
                    ),
                    models.Index(
                        fields=["next_audit_date"], name="data_asset_audit_idx"
                    ),
                    models.Index(fields=["created_at"], name="data_asset_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        help_text="Unique request identifier (e.g., DSR-2024-001)",
                        max_length=100,
                    ),
                ),
                (
                    "data_subject_id",
                    models.CharField(
                        help_text="Identifier for the data subject (email, user ID, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "data_subject_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("employee", "Employee"),
                            ("website_user", "Website User"),
                            ("prospect", "Prospect"),
                            ("supplier", "Supplier"),
                            ("other", "Other"),
                        ],
                        default="customer",
                        help_text="Type of data subject",
                        max_length=50,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for communication",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for communication",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(
                        blank=True,
                        help_text="Postal address for communication",
                        null=True,
                    ),
                ),
                (
                    "primary_right",
                    models.CharField(
                        choices=[
                            ("access", "Right of Access (Article 15)"),
                            ("rectification", "Right of Rectification (Article 16)"),
                            ("erasure", "Right to Erasure (Article 17)"),
                            ("restriction", "Right to Restriction (Article 18)"),
                            ("portability", "Right to Data Portability (Article 20)"),
                            ("objection", "Right to Object (Article 21)"),
                            (
                                "automated_decision_making",
                                "Rights re Automated Decision Making (Article 22)",
                            ),
                            ("multiple_rights", "Multiple Rights"),
                        ],
                        help_text="Primary right being requested",
                        max_length=30,
                    ),
                ),
                (
                    "rights_requested",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="All rights requested in this submission",
                    ),
                ),
                (
                    "request_description",
                    models.TextField(
                        help_text="Description of the request and what the data subject wants"
                    ),
                ),
                (
                    "request_scope",
                    models.TextField(
                        blank=True,
                        help_text="Scope of the request (specific data, time periods, etc.)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("verification_pending", "Verification Pending"),
                            ("verification_failed", "Verification Failed"),
                            ("processing", "Processing"),
                            ("information_requested", "Information Requested"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("appeal_pending", "Appeal Pending"),
                            ("appeal_completed", "Appeal Completed"),
                        ],
                        default="received",
                        help_text="Current status of the rights request",
                        max_length=25,
                    ),
                ),
                (
                    "identity_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether data subject identity has been verified",
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email_verification", "Email Verification"),
                            ("document_verification", "Document Verification"),
                            ("knowledge_based", "Knowledge-Based Authentication"),
                            ("third_party", "Third Party Verification"),
                            ("legal_request", "Legal Authority Request"),
                        ],
                        help_text="Method used to verify identity",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "verification_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when identity was verified",
                        null=True,
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when request was received",
                    ),
                ),
                (
                    "processing_start_date",
                    models.DateField(
                        blank=True, help_text="Date when processing began", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Date by which request must be fulfilled (GDPR 30 days)",
                        null=True,
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when request was completed",
                        null=True,
                    ),
                ),
                (
                    "assigned_to_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID assigned to process this request",
                        null=True,
                    ),
                ),
                (
                    "assigned_to_username",
                    models.CharField(
                        blank=True,
                        help_text="Username assigned to process this request",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True, help_text="Internal processing notes", null=True
                    ),
                ),
                (
                    "data_located",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Systems/locations where data was found",
                    ),
                ),
                (
                    "data_collected",
                    models.BooleanField(
                        default=False,
                        help_text="Whether required data has been collected",
                    ),
                ),
                (
                    "data_reviewed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether collected data has been reviewed",
                    ),
                ),
                (
                    "response_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("portal", "Online Portal"),
                            ("mail", "Physical Mail"),
                            ("phone", "Phone"),
                            ("in_person", "In Person"),
                        ],
                        default="email",
                        help_text="Method used to provide response",
                        max_length=50,
                    ),
                ),
                (
                    "response_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether response has been sent to data subject",
                    ),
                ),
                (
                    "response_date",
                    models.DateField(
                        blank=True, help_text="Date when response was sent", null=True
                    ),
                ),
                (
                    "response_summary",
                    models.TextField(
                        blank=True,
                        help_text="Summary of the response provided",
                        null=True,
                    ),
                ),
                (
                    "rejected",
                    models.BooleanField(
                        default=False, help_text="Whether request was rejected"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection", null=True
                    ),
                ),
                (
                    "rejection_date",
                    models.DateField(
                        blank=True, help_text="Date of rejection", null=True
                    ),
                ),
                (
                    "appeal_requested",
                    models.BooleanField(
                        default=False,
                        help_text="Whether data subject appealed the decision",
                    ),
                ),
                (
                    "appeal_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when appeal was requested",
                        null=True,
                    ),
                ),
                (
                    "appeal_reason",
                    models.TextField(
                        blank=True, help_text="Reason for appeal", null=True
                    ),
                ),
                (
                    "appeal_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upheld", "Decision Upheld"),
                            ("overturned", "Decision Overturned"),
                            ("modified", "Decision Modified"),
                        ],
                        help_text="Result of appeal",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "appeal_decision_date",
                    models.DateField(
                        blank=True, help_text="Date of appeal decision", null=True
                    ),
                ),
                (
                    "legal_review_required",
                    models.BooleanField(
                        default=False, help_text="Whether legal review was required"
                    ),
                ),
                (
                    "legal_review_completed",
                    models.BooleanField(
                        default=False, help_text="Whether legal review was completed"
                    ),
                ),
                (
                    "legal_review_date",
                    models.DateField(
                        blank=True, help_text="Date of legal review", null=True
                    ),
                ),
                (
                    "legal_findings",
                    models.TextField(
                        blank=True, help_text="Findings from legal review", null=True
                    ),
                ),
                (
                    "communication_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Log of all communications with data subject",
                    ),
                ),
                (
                    "related_data_assets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of data assets involved in this request",
                    ),
                ),
                (
                    "related_consent_records",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of related consent records",
                    ),
                ),
                (
                    "related_processing_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of related processing activities",
                    ),
                ),
                (
                    "audit_trail",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Audit trail of all actions taken",
                    ),
                ),
                (
                    "compliance_checklist",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Compliance checklist items and status",
                    ),
                ),
                (
                    "processing_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Hours spent processing this request",
                        max_digits=6,
                    ),
                ),
                (
                    "processing_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost incurred processing this request",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        help_text="Processing priority",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct_request", "Direct Request"),
                            ("portal", "Online Portal"),
                            ("email", "Email"),
                            ("phone", "Phone Call"),
                            ("legal_request", "Legal Authority Request"),
                            ("third_party", "Third Party Request"),
                        ],
                        default="direct_request",
                        help_text="How the request was submitted",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Request tags for organization",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional properties",
                    ),
                ),
            ],
            options={
                "db_table": "privacy_data_subject_rights",
                "ordering": ["-received_date"],
                "indexes": [
                    models.Index(fields=["data_subject_id"], name="dsr_subject_idx"),
                    models.Index(fields=["status"], name="dsr_status_idx"),
                    models.Index(fields=["primary_right"], name="dsr_right_type_idx"),
                    models.Index(
                        fields=["assigned_to_user_id"], name="dsr_assigned_idx"
                    ),
                    models.Index(fields=["due_date"], name="dsr_due_date_idx"),
                    models.Index(fields=["received_date"], name="dsr_received_idx"),
                    models.Index(fields=["verification_date"], name="dsr_verified_idx"),
                    models.Index(fields=["completion_date"], name="dsr_completed_idx"),
                    models.Index(fields=["created_at"], name="dsr_created_idx"),
                ],
            },
        ),
    ]
