# Generated by Django 5.2.9 on 2026-01-23 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThirdPartyEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Name of the third party entity", max_length=255
                    ),
                ),
                (
                    "entity_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the third party entity",
                        null=True,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="Unique entity identifier (e.g., TP-2024-001)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("vendor", "Vendor"),
                            ("supplier", "Supplier"),
                            ("partner", "Partner"),
                            ("contractor", "Contractor"),
                            ("consultant", "Consultant"),
                            ("cloud_provider", "Cloud Provider"),
                            ("other", "Other"),
                        ],
                        default="vendor",
                        help_text="Type of third party entity",
                        max_length=20,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Industry sector",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country of operation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "headquarters_location",
                    models.CharField(
                        blank=True,
                        help_text="Headquarters location",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Entity website", null=True),
                ),
                (
                    "contact_information",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Primary contact information",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospective", "Prospective"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="prospective",
                        help_text="Current relationship status",
                        max_length=15,
                    ),
                ),
                (
                    "inherent_risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Inherent risk level",
                        max_length=10,
                    ),
                ),
                (
                    "residual_risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Residual risk level after controls",
                        max_length=10,
                    ),
                ),
                (
                    "risk_assessment_date",
                    models.DateField(
                        blank=True, help_text="Date of last risk assessment", null=True
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0, help_text="Quantitative risk score (0.0-100.0)"
                    ),
                ),
                (
                    "contracts",
                    models.JSONField(
                        blank=True, default=list, help_text="Associated contracts"
                    ),
                ),
                (
                    "active_contracts_count",
                    models.IntegerField(
                        default=0, help_text="Number of active contracts"
                    ),
                ),
                (
                    "assessments",
                    models.JSONField(
                        blank=True, default=list, help_text="Completed assessments"
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("under_review", "Under Review"),
                            ("not_assessed", "Not Assessed"),
                        ],
                        default="not_assessed",
                        help_text="Overall compliance status",
                        max_length=20,
                    ),
                ),
                (
                    "last_assessment_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last compliance assessment",
                        null=True,
                    ),
                ),
                (
                    "next_assessment_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of next scheduled assessment",
                        null=True,
                    ),
                ),
                (
                    "criticality_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Business criticality level",
                        max_length=10,
                    ),
                ),
                (
                    "business_impact",
                    models.TextField(
                        blank=True,
                        help_text="Description of business impact if disrupted",
                        null=True,
                    ),
                ),
                (
                    "performance_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("poor", "Poor"),
                            ("fair", "Fair"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        help_text="Overall performance rating",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "quality_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Quality and performance metrics",
                    ),
                ),
                (
                    "security_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("poor", "Poor"),
                            ("fair", "Fair"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        help_text="Security posture rating",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "data_processing",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data processing activities and safeguards",
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual revenue (if public)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "employee_count",
                    models.IntegerField(
                        blank=True, help_text="Number of employees", null=True
                    ),
                ),
                (
                    "relationship_owner_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of relationship owner",
                        null=True,
                    ),
                ),
                (
                    "relationship_owner_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of relationship owner",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "relationship_manager_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of relationship manager",
                        null=True,
                    ),
                ),
                (
                    "relationship_manager_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of relationship manager",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "last_review_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last relationship review",
                        null=True,
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, help_text="Date of next scheduled review", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from relationship reviews",
                        null=True,
                    ),
                ),
                (
                    "related_assets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related assets from Asset context",
                    ),
                ),
                (
                    "related_risks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related risks from Risk Registers",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Entity tags for organization",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional properties",
                    ),
                ),
            ],
            options={
                "db_table": "third_party_entities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["entity_type"], name="tp_entity_type_idx"),
                    models.Index(fields=["status"], name="tp_entity_status_idx"),
                    models.Index(
                        fields=["inherent_risk_level"], name="tp_entity_risk_idx"
                    ),
                    models.Index(
                        fields=["compliance_status"], name="tp_entity_compliance_idx"
                    ),
                    models.Index(
                        fields=["criticality_level"], name="tp_entity_criticality_idx"
                    ),
                    models.Index(
                        fields=["relationship_owner_user_id"],
                        name="tp_entity_owner_idx",
                    ),
                    models.Index(
                        fields=["next_assessment_date"], name="tp_entity_assessment_idx"
                    ),
                    models.Index(fields=["created_at"], name="tp_entity_created_idx"),
                ],
            },
        ),
    ]
