"""
Built-in Assessment Artifact Templates

Pre-built evidence request templates for common frameworks and platform
combinations. Users select a template profile instead of uploading a TSV.

Each template item follows the same contract as a parsed TSV row:
  controls, category, artifact_request, periodicity, platform_tags,
  primary_artifact_type, collection_channel, commands, config_paths
"""

from __future__ import annotations

from typing import Any

# ── Template Registry ────────────────────────────────────────────────────

TEMPLATES: dict[str, dict[str, Any]] = {}


def _register(key: str, meta: dict[str, Any], items: list[dict[str, Any]]):
    TEMPLATES[key] = {"meta": meta, "items": items}


def get_template(key: str) -> dict[str, Any] | None:
    return TEMPLATES.get(key)


def list_templates() -> list[dict[str, Any]]:
    return [
        {
            "key": key,
            "name": tpl["meta"]["name"],
            "description": tpl["meta"]["description"],
            "framework": tpl["meta"]["framework"],
            "platforms": tpl["meta"]["platforms"],
            "item_count": len(tpl["items"]),
        }
        for key, tpl in TEMPLATES.items()
    ]


# ── Helper to build items concisely ─────────────────────────────────────

def _item(
    controls: list[str],
    category: str,
    request: str,
    *,
    periodicity: str = "on_demand",
    artifact_type: str = "generic_evidence",
    channel: str = "manual_collection",
    platforms: list[str] | None = None,
    commands: list[str] | None = None,
    config_paths: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "controls": controls,
        "category": category,
        "artifact_request": request,
        "periodicity": periodicity,
        "primary_artifact_type": artifact_type,
        "collection_channel": channel,
        "platform_tags": platforms or [],
        "commands": commands or [],
        "config_paths": config_paths or [],
    }


# ═══════════════════════════════════════════════════════════════════════
#  TEMPLATE: FedRAMP Moderate — AWS + RHEL 7 Ecosystem
# ═══════════════════════════════════════════════════════════════════════

_FEDRAMP_MOD_AWS_RHEL = []

# ── AC — Access Control ──────────────────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["AC-1"], "Policy", "Access Control Policy and Procedures document",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["AC-2"], "Records", "Complete listing of all system user accounts with roles and last login dates",
          periodicity="quarterly", artifact_type="records", channel="tool_export",
          platforms=["AWS", "LINUX"],
          commands=["aws iam list-users --output table", "aws iam list-groups --output table",
                    "cat /etc/passwd", "cat /etc/group"]),
    _item(["AC-2"], "Records", "Evidence of account review and recertification for the past quarter",
          periodicity="quarterly", artifact_type="records", channel="governance_records"),
    _item(["AC-2(1)"], "Configuration", "AWS IAM password policy and account lifecycle automation configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"],
          commands=["aws iam get-account-password-policy"]),
    _item(["AC-2(2)"], "Records", "Evidence of temporary/emergency account removal or expiration within defined timeframes",
          periodicity="quarterly", artifact_type="records", channel="tool_export",
          platforms=["AWS"],
          commands=["aws iam list-users --query 'Users[?PasswordLastUsed==`null`]'"]),
    _item(["AC-2(3)"], "Configuration", "Configuration showing automatic disabling of inactive accounts after 90 days",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"]),
    _item(["AC-2(4)", "AC-2(7)", "AU-5", "AU-6"], "Configuration",
          "Alert configuration for account creation, modification, disabling, removal, and privilege escalation events",
          periodicity="monthly", artifact_type="configuration_snapshot", channel="tool_export",
          platforms=["AWS", "SPLUNK"],
          commands=["aws cloudwatch describe-alarms --alarm-name-prefix IAM"]),
    _item(["AC-2(9)"], "Configuration", "Shared/group account authorization and usage restrictions",
          artifact_type="records", channel="document_repository"),
    _item(["AC-2(10)"], "Configuration", "Shared/group account credential change procedures upon membership change",
          artifact_type="procedure_document", channel="document_repository"),
    _item(["AC-3"], "Configuration", "Access enforcement mechanism configuration (IAM policies, SELinux, file permissions)",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "LINUX"],
          commands=["aws iam list-policies --scope Local --output table",
                    "getenforce", "cat /etc/selinux/config"]),
    _item(["AC-4"], "Configuration", "Network information flow enforcement — VPC security groups, NACLs, and flow logs",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"],
          commands=["aws ec2 describe-security-groups --output table",
                    "aws ec2 describe-network-acls --output table",
                    "aws ec2 describe-flow-logs --output table"]),
    _item(["AC-5"], "Records", "Separation of duties matrix showing conflicting roles are not co-assigned",
          artifact_type="matrix_or_mapping", channel="document_repository"),
    _item(["AC-6", "AC-6(1)", "AC-6(2)"], "Configuration",
          "Least privilege implementation — IAM role policies, sudo configuration, privileged user listing",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "LINUX"],
          commands=["aws iam list-attached-user-policies --user-name <admin>",
                    "cat /etc/sudoers", "cat /etc/sudoers.d/*"]),
    _item(["AC-6(5)"], "Configuration", "Privileged account listing and restriction to security functions only",
          periodicity="quarterly", artifact_type="records", channel="tool_export",
          platforms=["AWS"],
          commands=["aws iam get-account-authorization-details --filter LocalManagedPolicy"]),
    _item(["AC-6(9)"], "Configuration", "Auditing configuration for privileged function execution",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX", "SPLUNK"],
          config_paths=["/etc/audit/audit.rules"]),
    _item(["AC-6(10)"], "Configuration", "Configuration preventing non-privileged users from executing privileged functions",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          config_paths=["/etc/security/access.conf"]),
    _item(["AC-7"], "Configuration", "Unsuccessful logon attempt lockout configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          config_paths=["/etc/pam.d/system-auth", "/etc/pam.d/password-auth"]),
    _item(["AC-8"], "Configuration", "System use notification banner displayed before login",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          commands=["cat /etc/issue", "cat /etc/issue.net", "cat /etc/motd"],
          config_paths=["/etc/ssh/sshd_config"]),
    _item(["AC-10"], "Configuration", "Concurrent session control configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          config_paths=["/etc/security/limits.conf"]),
    _item(["AC-11", "AC-11(1)"], "Configuration", "Session lock configuration after 15 minutes of inactivity with pattern-obscuring display",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          commands=["grep -i tmout /etc/profile /etc/bashrc"]),
    _item(["AC-12"], "Configuration", "Session termination configuration for inactive sessions",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX", "AWS"],
          commands=["grep -i ClientAliveInterval /etc/ssh/sshd_config"]),
    _item(["AC-14"], "Records", "List of actions permitted without identification/authentication and justification",
          artifact_type="records", channel="document_repository"),
    _item(["AC-17", "AC-17(1)", "AC-17(2)"], "Configuration",
          "Remote access configuration — VPN, SSH, and encryption settings",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX", "NETWORK_BOUNDARY"],
          commands=["cat /etc/ssh/sshd_config", "cat /etc/openvpn/server.conf"],
          config_paths=["/etc/ssh/sshd_config"]),
    _item(["AC-17(3)"], "Configuration", "Managed access control points for remote access routing",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "NETWORK_BOUNDARY"],
          commands=["aws ec2 describe-route-tables --output table"]),
    _item(["AC-17(4)"], "Records", "Authorization records for remote access privileged commands and security-relevant information access",
          artifact_type="records", channel="governance_records"),
    _item(["AC-18"], "Configuration", "Wireless access restrictions and authorization configuration",
          artifact_type="configuration_snapshot", channel="document_repository"),
    _item(["AC-19"], "Policy", "Mobile device access control policy and configuration",
          artifact_type="policy_document", channel="document_repository"),
    _item(["AC-20"], "Policy", "Use of external information systems policy and agreements",
          artifact_type="policy_document", channel="document_repository"),
    _item(["AC-22"], "Records", "Publicly accessible content review and authorization records",
          periodicity="quarterly", artifact_type="records", channel="governance_records"),
])

# ── AT — Awareness and Training ─────────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["AT-1"], "Policy", "Security Awareness and Training Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["AT-2"], "Records", "Security awareness training records for all users — past 365 days",
          periodicity="annual", artifact_type="training_artifact", channel="system_of_record_export"),
    _item(["AT-2(2)"], "Records", "Insider threat awareness training completion records",
          periodicity="annual", artifact_type="training_artifact", channel="system_of_record_export"),
    _item(["AT-3"], "Records", "Role-based security training records for privileged users and security personnel",
          periodicity="annual", artifact_type="training_artifact", channel="system_of_record_export"),
    _item(["AT-4"], "Records", "Training records retention and individual training documentation",
          periodicity="annual", artifact_type="records", channel="system_of_record_export"),
])

# ── AU — Audit and Accountability ───────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["AU-1"], "Policy", "Audit and Accountability Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["AU-2"], "Configuration", "Auditable events definition and configuration — CloudTrail, auditd, Splunk",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "LINUX", "SPLUNK"],
          commands=["aws cloudtrail describe-trails --output table",
                    "aws cloudtrail get-trail-status --name <trail>",
                    "auditctl -l"],
          config_paths=["/etc/audit/audit.rules", "/etc/audit/auditd.conf"]),
    _item(["AU-2"], "Records", "Audit event review coordination records — at least annually",
          periodicity="annual", artifact_type="records", channel="governance_records"),
    _item(["AU-3", "AU-3(1)"], "Configuration",
          "Audit record content configuration — timestamp, source, outcome, identity, and additional detail fields",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX", "SPLUNK"],
          config_paths=["/etc/audit/auditd.conf"]),
    _item(["AU-4"], "Configuration", "Audit log storage capacity allocation and monitoring",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "LINUX"],
          commands=["aws s3api get-bucket-lifecycle-configuration --bucket <audit-bucket>",
                    "df -h /var/log/audit"]),
    _item(["AU-5"], "Configuration", "Audit processing failure alert configuration — alerts to security personnel on storage exhaustion or failure",
          artifact_type="configuration_snapshot", channel="tool_export",
          platforms=["AWS", "SPLUNK"],
          commands=["aws cloudwatch describe-alarms --alarm-name-prefix Audit"]),
    _item(["AU-6", "AU-6(1)"], "Records",
          "Audit log review reports — weekly reviews of audit records for inappropriate or unusual activity",
          periodicity="weekly", artifact_type="report", channel="tool_export",
          platforms=["SPLUNK"]),
    _item(["AU-6(3)"], "Configuration", "Centralized audit log correlation and analysis configuration",
          artifact_type="configuration_snapshot", channel="tool_export",
          platforms=["SPLUNK"],
          config_paths=["/opt/splunk/etc/system/local/inputs.conf",
                        "/opt/splunk/etc/system/local/outputs.conf"]),
    _item(["AU-7", "AU-7(1)"], "Configuration", "Audit reduction and report generation capability — Splunk search/report configuration",
          artifact_type="configuration_snapshot", channel="tool_export",
          platforms=["SPLUNK"]),
    _item(["AU-8", "AU-8(1)"], "Configuration", "Time synchronization configuration — NTP/Chrony settings and authoritative time source",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX", "AWS"],
          commands=["ntpstat", "chronyc tracking", "cat /etc/chrony.conf",
                    "timedatectl status"]),
    _item(["AU-9"], "Configuration", "Audit information protection — access controls on audit logs and CloudTrail log file validation",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "LINUX"],
          commands=["aws cloudtrail get-trail --name <trail>",
                    "ls -la /var/log/audit/",
                    "aws s3api get-bucket-policy --bucket <audit-bucket>"]),
    _item(["AU-9(4)"], "Configuration", "Audit log access restricted to subset of privileged users",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          commands=["getfacl /var/log/audit/"]),
    _item(["AU-11"], "Configuration", "Audit record retention configuration — minimum 90 days online, 1 year total",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "SPLUNK"],
          commands=["aws s3api get-bucket-lifecycle-configuration --bucket <audit-bucket>"]),
    _item(["AU-12"], "Configuration", "Audit generation configuration providing system-wide audit trail across all components",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "LINUX"],
          commands=["aws cloudtrail get-trail-status --name <trail>",
                    "systemctl status auditd"]),
])

# ── CA — Assessment, Authorization, and Monitoring ───────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["CA-1"], "Policy", "Security Assessment and Authorization Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["CA-2", "CA-2(1)"], "Plan", "Security assessment plan with independent assessor engagement",
          artifact_type="plan_document", channel="document_repository"),
    _item(["CA-3"], "Records", "System interconnection agreements (ISAs/MOUs) for all external connections",
          periodicity="annual", artifact_type="records", channel="document_repository"),
    _item(["CA-5"], "Records", "Plan of Action and Milestones (POA&M) — current with all open findings",
          periodicity="monthly", artifact_type="records", channel="system_of_record_export"),
    _item(["CA-6"], "Records", "Authorization to Operate (ATO) letter and authorization decision",
          artifact_type="records", channel="document_repository"),
    _item(["CA-7"], "Plan", "Continuous monitoring strategy and plan",
          periodicity="annual", artifact_type="plan_document", channel="document_repository"),
    _item(["CA-7"], "Records", "Continuous monitoring status reports — monthly deliverables",
          periodicity="monthly", artifact_type="report", channel="report_export"),
    _item(["CA-8"], "Report", "Penetration test report — at least annual",
          periodicity="annual", artifact_type="report", channel="report_export"),
    _item(["CA-9"], "Records", "Internal system connection authorizations and documentation",
          artifact_type="records", channel="document_repository"),
])

# ── CM — Configuration Management ───────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["CM-1"], "Policy", "Configuration Management Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["CM-2", "CM-2(1)"], "Configuration",
          "Current system baseline configuration — OS, middleware, application component versions",
          periodicity="annual", artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX", "AWS"],
          commands=["uname -a", "cat /etc/redhat-release", "rpm -qa --last | head -50",
                    "aws ec2 describe-instances --query 'Reservations[].Instances[].{ID:InstanceId,Type:InstanceType,AMI:ImageId}' --output table"]),
    _item(["CM-2(3)"], "Records", "Evidence of baseline retention for prior configuration versions",
          periodicity="annual", artifact_type="records", channel="tool_export",
          platforms=["AWS"],
          commands=["aws ec2 describe-images --owners self --output table"]),
    _item(["CM-2(7)"], "Configuration", "Configuration of additional security measures for high-risk travel systems",
          artifact_type="configuration_snapshot", channel="document_repository"),
    _item(["CM-3", "CM-3(2)"], "Records",
          "Configuration change control records — change requests, approvals, and implementation evidence",
          periodicity="monthly", artifact_type="records", channel="system_of_record_export"),
    _item(["CM-4"], "Records", "Security impact analysis records for system changes",
          periodicity="monthly", artifact_type="records", channel="system_of_record_export"),
    _item(["CM-5"], "Configuration", "Access restrictions for change — who can deploy, modify configs, and apply patches",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "LINUX"],
          commands=["aws iam list-attached-group-policies --group-name Deployers"]),
    _item(["CM-6"], "Configuration",
          "Configuration settings enforcement — RHEL STIG/CIS benchmark compliance scan results",
          periodicity="monthly", artifact_type="scan_evidence", channel="scanner_export",
          platforms=["LINUX", "NESSUS"]),
    _item(["CM-6"], "Configuration", "AWS configuration compliance — AWS Config rule evaluation results",
          periodicity="monthly", artifact_type="configuration_snapshot", channel="tool_export",
          platforms=["AWS"],
          commands=["aws configservice describe-compliance-by-config-rule --output table"]),
    _item(["CM-7", "CM-7(1)"], "Configuration",
          "Least functionality — disabled services, blocked ports, removed unnecessary software",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          commands=["systemctl list-unit-files --state=enabled",
                    "rpm -qa", "cat /etc/hosts.deny"]),
    _item(["CM-7(2)"], "Configuration", "Software whitelisting/blacklisting configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"]),
    _item(["CM-7(5)"], "Configuration", "Authorized software list and evidence of unauthorized software detection",
          periodicity="monthly", artifact_type="records", channel="tool_export",
          platforms=["LINUX"]),
    _item(["CM-8", "CM-8(1)"], "Records",
          "System component inventory — hardware, software, firmware with update tracking",
          periodicity="quarterly", artifact_type="inventory_listing", channel="tool_export",
          platforms=["AWS"],
          commands=["aws ec2 describe-instances --output table",
                    "aws rds describe-db-instances --output table",
                    "aws s3api list-buckets --output table",
                    "aws elasticache describe-cache-clusters --output table"]),
    _item(["CM-8(3)"], "Configuration", "Automated unauthorized component detection configuration",
          periodicity="monthly", artifact_type="configuration_snapshot", channel="tool_export",
          platforms=["AWS"],
          commands=["aws config describe-config-rules --output table"]),
    _item(["CM-9"], "Plan", "Configuration management plan",
          periodicity="annual", artifact_type="plan_document", channel="document_repository"),
    _item(["CM-10"], "Records", "Software usage restrictions and license tracking",
          periodicity="annual", artifact_type="records", channel="system_of_record_export"),
    _item(["CM-11"], "Configuration", "User-installed software restrictions and policy enforcement",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"]),
])

# ── CP — Contingency Planning ────────────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["CP-1"], "Policy", "Contingency Planning Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["CP-2", "CP-2(1)", "CP-2(3)", "CP-2(8)"], "Plan",
          "Information System Contingency Plan (ISCP) with designated roles, recovery priorities, and BIA",
          periodicity="annual", artifact_type="plan_document", channel="document_repository"),
    _item(["CP-3"], "Records", "Contingency plan training records",
          periodicity="annual", artifact_type="training_artifact", channel="system_of_record_export"),
    _item(["CP-4", "CP-4(1)"], "Records", "Contingency plan test results and lessons learned",
          periodicity="annual", artifact_type="report", channel="report_export"),
    _item(["CP-6", "CP-6(1)", "CP-6(3)"], "Configuration",
          "Alternate storage site configuration — S3 cross-region replication, EBS snapshots, geographic separation",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"],
          commands=["aws s3api get-bucket-replication --bucket <primary-bucket>",
                    "aws ec2 describe-snapshots --owner-ids self --output table"]),
    _item(["CP-7", "CP-7(1)", "CP-7(3)"], "Configuration",
          "Alternate processing site configuration — multi-AZ deployment, failover capabilities",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"],
          commands=["aws ec2 describe-availability-zones --output table",
                    "aws rds describe-db-instances --query 'DBInstances[].{ID:DBInstanceIdentifier,MultiAZ:MultiAZ}' --output table",
                    "aws autoscaling describe-auto-scaling-groups --output table"]),
    _item(["CP-9", "CP-9(1)"], "Configuration",
          "System backup configuration and backup testing evidence",
          periodicity="monthly", artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"],
          commands=["aws rds describe-db-snapshots --db-instance-identifier <db> --output table",
                    "aws ec2 describe-snapshots --owner-ids self --query 'Snapshots[?StartTime>=`2025-01-01`]' --output table"]),
    _item(["CP-10"], "Records", "System recovery and reconstitution test evidence",
          periodicity="annual", artifact_type="report", channel="report_export"),
])

# ── IA — Identification and Authentication ───────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["IA-1"], "Policy", "Identification and Authentication Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["IA-2", "IA-2(1)", "IA-2(2)", "IA-2(12)"], "Configuration",
          "Multi-factor authentication configuration for privileged and non-privileged users",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"],
          commands=["aws iam get-account-summary",
                    "aws iam list-virtual-mfa-devices --output table"]),
    _item(["IA-3"], "Configuration", "Device identification and authentication configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "NETWORK_BOUNDARY"]),
    _item(["IA-4"], "Records", "Identifier management — user ID assignment, reuse prevention, and disabling after inactivity",
          periodicity="quarterly", artifact_type="records", channel="tool_export",
          platforms=["AWS"],
          commands=["aws iam generate-credential-report",
                    "aws iam get-credential-report"]),
    _item(["IA-5", "IA-5(1)"], "Configuration",
          "Password complexity and authenticator management configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "LINUX"],
          commands=["aws iam get-account-password-policy"],
          config_paths=["/etc/pam.d/system-auth", "/etc/login.defs"]),
    _item(["IA-5(2)"], "Configuration", "PKI-based authentication — certificate validation and trust chain configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          commands=["openssl s_client -connect <host>:443 -showcerts"],
          config_paths=["/etc/pki/tls/certs/"]),
    _item(["IA-5(11)"], "Configuration", "Hardware token / PIV credential configuration for authentication",
          artifact_type="configuration_snapshot", channel="document_repository"),
    _item(["IA-6"], "Configuration", "Authenticator feedback obscuring configuration — password masking on login",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"]),
    _item(["IA-7"], "Configuration", "Cryptographic module authentication — FIPS 140-2 validated modules",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          commands=["cat /proc/sys/crypto/fips_enabled",
                    "openssl version"]),
    _item(["IA-8", "IA-8(1)", "IA-8(2)", "IA-8(3)", "IA-8(4)"], "Configuration",
          "Non-organizational user identification/authentication — federated identity, PIV acceptance",
          artifact_type="configuration_snapshot", channel="document_repository"),
])

# ── IR — Incident Response ───────────────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["IR-1"], "Policy", "Incident Response Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["IR-2"], "Records", "Incident response training records",
          periodicity="annual", artifact_type="training_artifact", channel="system_of_record_export"),
    _item(["IR-3", "IR-3(2)"], "Records", "Incident response testing/exercise results with coordination across related plans",
          periodicity="annual", artifact_type="report", channel="report_export"),
    _item(["IR-4", "IR-4(1)"], "Records",
          "Incident handling records — detection, analysis, containment, eradication, recovery documentation",
          periodicity="monthly", artifact_type="records", channel="system_of_record_export"),
    _item(["IR-5"], "Records", "Incident tracking and monitoring — open/closed incident metrics",
          periodicity="monthly", artifact_type="report", channel="tool_export"),
    _item(["IR-6", "IR-6(1)"], "Records",
          "Incident reporting records — US-CERT notifications and automated reporting configuration",
          periodicity="monthly", artifact_type="records", channel="system_of_record_export"),
    _item(["IR-7", "IR-7(1)"], "Records", "Incident response assistance resources and support contacts",
          artifact_type="records", channel="document_repository"),
    _item(["IR-8"], "Plan", "Incident Response Plan with roles, responsibilities, and escalation procedures",
          periodicity="annual", artifact_type="plan_document", channel="document_repository"),
    _item(["IR-9"], "Records", "Information spillage response procedures and evidence of any spillage handling",
          artifact_type="procedure_document", channel="document_repository"),
])

# ── MA — Maintenance ─────────────────────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["MA-1"], "Policy", "Maintenance Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["MA-2"], "Records", "Controlled maintenance records — scheduled and unscheduled maintenance activities",
          periodicity="quarterly", artifact_type="records", channel="system_of_record_export"),
    _item(["MA-3", "MA-3(1)", "MA-3(2)"], "Records",
          "Maintenance tool authorization, inspection, and media handling procedures",
          artifact_type="procedure_document", channel="document_repository"),
    _item(["MA-4", "MA-4(2)"], "Records", "Non-local maintenance records with strong authentication evidence",
          periodicity="quarterly", artifact_type="records", channel="system_of_record_export"),
    _item(["MA-5"], "Records", "Maintenance personnel authorization and escort records",
          periodicity="quarterly", artifact_type="records", channel="governance_records"),
    _item(["MA-6"], "Records", "Timely maintenance records — MTTR metrics and spare parts availability",
          periodicity="quarterly", artifact_type="records", channel="system_of_record_export"),
])

# ── MP — Media Protection ───────────────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["MP-1"], "Policy", "Media Protection Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["MP-2"], "Configuration", "Media access restriction configuration — EBS encryption, S3 bucket policies",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"],
          commands=["aws ec2 describe-volumes --query 'Volumes[].{ID:VolumeId,Encrypted:Encrypted}' --output table",
                    "aws s3api get-bucket-encryption --bucket <bucket>"]),
    _item(["MP-3"], "Records", "Media marking procedures and evidence of marking compliance",
          artifact_type="procedure_document", channel="document_repository"),
    _item(["MP-4"], "Configuration", "Media storage protection — encryption at rest configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"],
          commands=["aws kms list-keys --output table"]),
    _item(["MP-5"], "Records", "Media transport protection procedures and records",
          artifact_type="procedure_document", channel="document_repository"),
    _item(["MP-6", "MP-6(2)"], "Records", "Media sanitization records with NIST SP 800-88 compliance",
          periodicity="quarterly", artifact_type="records", channel="governance_records"),
])

# ── PE — Physical and Environmental Protection ──────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["PE-1"], "Policy", "Physical and Environmental Protection Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["PE-2"], "Records", "Physical access authorization records and access lists",
          periodicity="quarterly", artifact_type="records", channel="governance_records"),
    _item(["PE-3"], "Records", "Physical access control evidence — badge logs, visitor records, locked facility evidence (AWS data center inherits)",
          periodicity="quarterly", artifact_type="records", channel="governance_records",
          platforms=["AWS"]),
    _item(["PE-6", "PE-6(1)"], "Records", "Physical access monitoring — review of access logs and intrusion alarm records",
          periodicity="monthly", artifact_type="records", channel="governance_records"),
    _item(["PE-8"], "Records", "Visitor access records — past 365 days",
          periodicity="quarterly", artifact_type="records", channel="governance_records"),
    _item(["PE-9"], "Configuration", "Power equipment and cabling protection (inherited from AWS)",
          artifact_type="records", channel="document_repository", platforms=["AWS"]),
    _item(["PE-10"], "Configuration", "Emergency shutoff capability documentation (inherited from AWS)",
          artifact_type="records", channel="document_repository", platforms=["AWS"]),
    _item(["PE-11"], "Configuration", "Emergency power — UPS/generator configuration (inherited from AWS)",
          artifact_type="records", channel="document_repository", platforms=["AWS"]),
    _item(["PE-12"], "Configuration", "Emergency lighting documentation (inherited from AWS)",
          artifact_type="records", channel="document_repository", platforms=["AWS"]),
    _item(["PE-13", "PE-13(3)"], "Records", "Fire protection and suppression system records (inherited from AWS)",
          artifact_type="records", channel="document_repository", platforms=["AWS"]),
    _item(["PE-14"], "Configuration", "Temperature/humidity control documentation (inherited from AWS)",
          artifact_type="records", channel="document_repository", platforms=["AWS"]),
    _item(["PE-15"], "Configuration", "Water damage protection documentation (inherited from AWS)",
          artifact_type="records", channel="document_repository", platforms=["AWS"]),
    _item(["PE-16"], "Records", "Delivery and removal authorization and tracking records",
          periodicity="quarterly", artifact_type="records", channel="governance_records"),
    _item(["PE-17"], "Records", "Alternate work site security verification records",
          periodicity="annual", artifact_type="records", channel="governance_records"),
])

# ── PL — Planning ────────────────────────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["PL-1"], "Policy", "Security Planning Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["PL-2", "PL-2(3)"], "Plan", "System Security Plan (SSP) — current version with plan coordination",
          periodicity="annual", artifact_type="plan_document", channel="document_repository"),
    _item(["PL-4", "PL-4(1)"], "Records", "Rules of behavior with social media/networking restrictions — signed by all users",
          periodicity="annual", artifact_type="records", channel="governance_records"),
])

# ── PS — Personnel Security ──────────────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["PS-1"], "Policy", "Personnel Security Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["PS-2"], "Records", "Position risk designation records for all system-related positions",
          periodicity="annual", artifact_type="records", channel="governance_records"),
    _item(["PS-3"], "Records", "Personnel screening records — background investigations completed before access",
          periodicity="annual", artifact_type="records", channel="governance_records"),
    _item(["PS-4"], "Records", "Personnel termination records — access revocation evidence within required timeframes",
          periodicity="quarterly", artifact_type="records", channel="governance_records"),
    _item(["PS-5"], "Records", "Personnel transfer records — access review and modification evidence",
          periodicity="quarterly", artifact_type="records", channel="governance_records"),
    _item(["PS-6"], "Records", "Access agreements — signed NDAs and acceptable use agreements",
          periodicity="annual", artifact_type="records", channel="governance_records"),
    _item(["PS-7"], "Records", "Third-party personnel security requirements and compliance evidence",
          periodicity="annual", artifact_type="records", channel="governance_records"),
    _item(["PS-8"], "Records", "Personnel sanctions process records",
          periodicity="annual", artifact_type="procedure_document", channel="document_repository"),
])

# ── RA — Risk Assessment ────────────────────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["RA-1"], "Policy", "Risk Assessment Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["RA-2"], "Records", "Security categorization (FIPS 199) documentation with rationale",
          artifact_type="records", channel="document_repository"),
    _item(["RA-3"], "Report", "Risk assessment report — at least annual or upon significant change",
          periodicity="annual", artifact_type="report", channel="report_export"),
    _item(["RA-5", "RA-5(1)", "RA-5(2)", "RA-5(5)"], "Scan",
          "Vulnerability scan results — monthly OS/infrastructure scans and web application scans",
          periodicity="monthly", artifact_type="scan_evidence", channel="scanner_export",
          platforms=["NESSUS", "LINUX", "AWS"]),
    _item(["RA-5(3)"], "Configuration", "Vulnerability scanning coverage breadth/depth — scan policy configuration",
          artifact_type="configuration_snapshot", channel="scanner_export",
          platforms=["NESSUS"]),
    _item(["RA-5(8)"], "Records", "Vulnerability scan review and remediation tracking — POA&M updates",
          periodicity="monthly", artifact_type="records", channel="system_of_record_export"),
])

# ── SA — System and Services Acquisition ─────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["SA-1"], "Policy", "System and Services Acquisition Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["SA-2"], "Records", "Security resource allocation in system development lifecycle",
          artifact_type="records", channel="document_repository"),
    _item(["SA-3"], "Records", "System development lifecycle (SDLC) documentation with security integration",
          artifact_type="records", channel="document_repository"),
    _item(["SA-4"], "Records", "Acquisition contracts with security requirements and functional specifications",
          artifact_type="records", channel="document_repository"),
    _item(["SA-4(2)"], "Records", "Security design and implementation documentation from developers",
          artifact_type="records", channel="document_repository"),
    _item(["SA-5"], "Records", "System documentation — administrator and user guides with security configuration guidance",
          artifact_type="records", channel="document_repository"),
    _item(["SA-8"], "Records", "Security engineering principles documentation applied in system design",
          artifact_type="records", channel="document_repository"),
    _item(["SA-9"], "Records", "External information system service agreements — SLAs, security requirements",
          periodicity="annual", artifact_type="records", channel="document_repository"),
    _item(["SA-10"], "Configuration", "Developer configuration management — source control, build pipeline, and change tracking",
          artifact_type="configuration_snapshot", channel="tool_export",
          platforms=["JENKINS"]),
    _item(["SA-11"], "Records", "Developer security testing and evaluation results — SAST/DAST scan evidence",
          periodicity="quarterly", artifact_type="scan_evidence", channel="scanner_export"),
])

# ── SC — System and Communications Protection ───────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["SC-1"], "Policy", "System and Communications Protection Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["SC-2"], "Configuration", "Application partitioning — separation of user and management functionality",
          artifact_type="configuration_snapshot", channel="document_repository"),
    _item(["SC-4"], "Configuration", "Information in shared resources protection — memory, disk, cache clearing",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"]),
    _item(["SC-5"], "Configuration", "Denial of service protection — rate limiting, AWS Shield, WAF rules",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "WEB_APP"],
          commands=["aws wafv2 list-web-acls --scope REGIONAL --output table"]),
    _item(["SC-7", "SC-7(3)", "SC-7(4)", "SC-7(5)", "SC-7(7)"], "Configuration",
          "Boundary protection — VPC architecture, security groups, managed interfaces, deny-by-default",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "NETWORK_BOUNDARY"],
          commands=["aws ec2 describe-vpcs --output table",
                    "aws ec2 describe-security-groups --output table",
                    "aws ec2 describe-network-acls --output table"]),
    _item(["SC-7(8)"], "Configuration", "Route traffic through managed proxy/firewall for external connections",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "NETWORK_BOUNDARY"],
          commands=["aws ec2 describe-route-tables --output table"]),
    _item(["SC-8", "SC-8(1)"], "Configuration",
          "Transmission confidentiality and integrity — TLS/encryption configuration for data in transit",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX", "AWS"],
          commands=["openssl s_client -connect <host>:443 -tls1_2",
                    "aws elbv2 describe-listeners --load-balancer-arn <arn> --output table"],
          config_paths=["/etc/ssl/", "/etc/pki/tls/"]),
    _item(["SC-10"], "Configuration", "Network session disconnect after 30 minutes inactivity for remote access",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          commands=["grep ClientAliveInterval /etc/ssh/sshd_config",
                    "grep ClientAliveCountMax /etc/ssh/sshd_config"]),
    _item(["SC-12"], "Configuration", "Cryptographic key establishment and management — KMS configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"],
          commands=["aws kms list-keys --output table",
                    "aws kms describe-key --key-id <key-id>"]),
    _item(["SC-13"], "Configuration", "FIPS-validated cryptographic module usage evidence",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          commands=["cat /proc/sys/crypto/fips_enabled",
                    "openssl version"]),
    _item(["SC-15"], "Configuration", "Collaborative computing device configuration — remote activation prevention",
          artifact_type="configuration_snapshot", channel="document_repository"),
    _item(["SC-17"], "Records", "PKI certificate management — valid certificates from approved CAs",
          periodicity="quarterly", artifact_type="records", channel="tool_export",
          platforms=["AWS", "LINUX"],
          commands=["aws acm list-certificates --output table"]),
    _item(["SC-18"], "Configuration", "Mobile code restrictions — browser/Java/ActiveX settings",
          artifact_type="configuration_snapshot", channel="document_repository"),
    _item(["SC-19"], "Configuration", "Voice over IP (VoIP) security configuration if applicable",
          artifact_type="configuration_snapshot", channel="document_repository"),
    _item(["SC-20", "SC-21", "SC-22"], "Configuration",
          "DNS security — DNSSEC, name resolution integrity and authentication",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS", "DNS_EMAIL_AUTH"],
          commands=["aws route53 get-dnssec --hosted-zone-id <zone>"]),
    _item(["SC-23"], "Configuration", "Session authenticity — anti-session-hijacking measures and CSRF protection",
          artifact_type="configuration_snapshot", channel="document_repository",
          platforms=["WEB_APP"]),
    _item(["SC-28", "SC-28(1)"], "Configuration",
          "Data at rest encryption — EBS, RDS, S3 encryption configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["AWS"],
          commands=["aws rds describe-db-instances --query 'DBInstances[].{ID:DBInstanceIdentifier,Encrypted:StorageEncrypted}' --output table",
                    "aws s3api get-bucket-encryption --bucket <bucket>"]),
])

# ── SI — System and Information Integrity ────────────────────────────

_FEDRAMP_MOD_AWS_RHEL.extend([
    _item(["SI-1"], "Policy", "System and Information Integrity Policy and Procedures",
          periodicity="annual", artifact_type="policy_document", channel="document_repository"),
    _item(["SI-2", "SI-2(2)"], "Records",
          "Flaw remediation — patch management records and automated patch status reporting",
          periodicity="monthly", artifact_type="records", channel="tool_export",
          platforms=["LINUX", "AWS"],
          commands=["yum updateinfo list security", "yum check-update",
                    "aws ssm describe-instance-patch-states --output table"]),
    _item(["SI-3", "SI-3(1)", "SI-3(2)"], "Configuration",
          "Malicious code protection — antimalware/EDR configuration, automatic updates, and real-time scanning",
          artifact_type="configuration_snapshot", channel="tool_export",
          platforms=["LINUX", "TREND_MICRO"]),
    _item(["SI-4", "SI-4(1)", "SI-4(2)", "SI-4(4)", "SI-4(5)"], "Configuration",
          "Information system monitoring — IDS/IPS, GuardDuty, CloudWatch alarms, and Splunk alert configuration",
          periodicity="weekly", artifact_type="configuration_snapshot", channel="tool_export",
          platforms=["AWS", "SPLUNK"],
          commands=["aws guardduty list-detectors --output table",
                    "aws guardduty get-detector --detector-id <id>",
                    "aws cloudwatch describe-alarms --output table"]),
    _item(["SI-4"], "Records", "System monitoring alert review and triage records",
          periodicity="weekly", artifact_type="records", channel="tool_export",
          platforms=["SPLUNK"]),
    _item(["SI-5"], "Records", "Security alerts and advisories — receipt, dissemination, and action records",
          periodicity="monthly", artifact_type="records", channel="system_of_record_export"),
    _item(["SI-6"], "Records", "Security function verification — integrity checks and self-test results",
          periodicity="quarterly", artifact_type="records", channel="tool_export"),
    _item(["SI-7", "SI-7(1)"], "Configuration",
          "Software and information integrity — file integrity monitoring configuration (AIDE/OSSEC/Tripwire)",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          commands=["aide --check"],
          config_paths=["/etc/aide.conf"]),
    _item(["SI-8", "SI-8(1)", "SI-8(2)"], "Configuration",
          "Spam protection — email filtering configuration with automatic updates and centralized management",
          artifact_type="configuration_snapshot", channel="tool_export",
          platforms=["DNS_EMAIL_AUTH"]),
    _item(["SI-10"], "Configuration", "Information input validation — application input validation configuration",
          artifact_type="configuration_snapshot", channel="document_repository",
          platforms=["WEB_APP"]),
    _item(["SI-11"], "Configuration", "Error handling — error messages that don't reveal sensitive information",
          artifact_type="configuration_snapshot", channel="document_repository",
          platforms=["WEB_APP"]),
    _item(["SI-12"], "Records", "Information handling and retention procedures compliance evidence",
          periodicity="annual", artifact_type="records", channel="governance_records"),
    _item(["SI-16"], "Configuration", "Memory protection — ASLR, DEP/NX, stack protection configuration",
          artifact_type="configuration_snapshot", channel="cli_capture",
          platforms=["LINUX"],
          commands=["cat /proc/sys/kernel/randomize_va_space",
                    "dmesg | grep NX"]),
])

# Register the template
_register(
    "fedramp_moderate_aws_rhel7",
    meta={
        "name": "FedRAMP Moderate — AWS + RHEL 7",
        "description": (
            "Complete NIST 800-53 Rev 4 evidence request template for a FedRAMP Moderate "
            "system running on AWS with RHEL 7 hosts. Covers all 17 control families with "
            "~200 evidence items including CLI commands, configuration paths, and periodic "
            "collection schedules (weekly/monthly/quarterly/annual)."
        ),
        "framework": "NIST 800-53 Rev 4",
        "baseline": "FedRAMP Moderate",
        "platforms": ["AWS", "RHEL7", "LINUX", "ORACLE_DB", "POSTGRES_DB", "SPLUNK",
                      "NESSUS", "TREND_MICRO", "JENKINS", "NETWORK_BOUNDARY"],
    },
    items=_FEDRAMP_MOD_AWS_RHEL,
)
