# Generated by Django 5.2.9 on 2026-01-23 05:51

import django.core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0132_eventstore"),
        ("evidence_automation", "0001_initial"),
        ("iam", "0018_cacheversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConMonActivityConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "requirement_urn",
                    models.CharField(
                        help_text="URN of the ConMon schedule requirement",
                        max_length=500,
                        verbose_name="Requirement URN",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Activity Name"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "frequency_override",
                    models.CharField(
                        choices=[
                            ("inherit", "Use Default"),
                            ("continuous", "Continuous"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Every 2 Weeks"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                            ("biennial", "Every 2 Years"),
                            ("triennial", "Every 3 Years"),
                            ("event_driven", "Event-Driven"),
                        ],
                        default="inherit",
                        max_length=20,
                        verbose_name="Frequency Override",
                    ),
                ),
                (
                    "custom_schedule",
                    models.JSONField(
                        blank=True,
                        help_text="Custom schedule JSON matching TaskTemplate schedule format",
                        null=True,
                        verbose_name="Custom Schedule",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "applied_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="conmon_activities",
                        to="core.appliedcontrol",
                        verbose_name="Applied Controls",
                    ),
                ),
                (
                    "assigned_actors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Override profile-level assignment for this activity",
                        related_name="conmon_activity_configs",
                        to="core.actor",
                        verbose_name="Assigned Actors",
                    ),
                ),
                (
                    "evidence_rules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="conmon_activities",
                        to="evidence_automation.evidencecollectionrule",
                        verbose_name="Evidence Collection Rules",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "task_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conmon_activity_config",
                        to="core.tasktemplate",
                        verbose_name="Task Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "ConMon Activity Configuration",
                "verbose_name_plural": "ConMon Activity Configurations",
            },
        ),
        migrations.CreateModel(
            name="ConMonExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("period_start", models.DateField(verbose_name="Period Start")),
                ("period_end", models.DateField(verbose_name="Period End")),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("completed_late", "Completed Late"),
                            ("missed", "Missed"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("partial", "Partial"),
                            ("not_assessed", "Not Assessed"),
                        ],
                        default="not_assessed",
                        max_length=20,
                        verbose_name="Result",
                    ),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completed Date"
                    ),
                ),
                ("findings", models.TextField(blank=True, verbose_name="Findings")),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                (
                    "activity_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="continuous_monitoring.conmonactivityconfig",
                        verbose_name="Activity Configuration",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conmon_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completed By",
                    ),
                ),
                (
                    "evidences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="conmon_executions",
                        to="core.evidence",
                        verbose_name="Evidences",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "task_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conmon_executions",
                        to="core.tasknode",
                        verbose_name="Task Node",
                    ),
                ),
            ],
            options={
                "verbose_name": "ConMon Execution",
                "verbose_name_plural": "ConMon Executions",
                "ordering": ["-period_start", "-due_date"],
            },
        ),
        migrations.CreateModel(
            name="ConMonProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("fedramp_low", "FedRAMP Low"),
                            ("fedramp_moderate", "FedRAMP Moderate"),
                            ("fedramp_high", "FedRAMP High"),
                            ("iso_27001", "ISO 27001"),
                            ("soc_2", "SOC 2"),
                            ("nist_csf", "NIST CSF"),
                            ("cmmc_l1", "CMMC Level 1"),
                            ("cmmc_l2", "CMMC Level 2"),
                            ("cmmc_l3", "CMMC Level 3"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                        verbose_name="Profile Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "implementation_groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of implementation group ref_ids to include",
                        verbose_name="Implementation Groups",
                    ),
                ),
                (
                    "notification_lead_days",
                    models.IntegerField(
                        default=7,
                        help_text="Days before due date to send reminders",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Notification Lead Days",
                    ),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Notifications Enabled"
                    ),
                ),
                (
                    "assigned_actors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="conmon_profiles",
                        to="core.actor",
                        verbose_name="Assigned Actors",
                    ),
                ),
                (
                    "base_framework",
                    models.ForeignKey(
                        blank=True,
                        help_text="Framework to use as basis for ConMon activities",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conmon_profiles",
                        to="core.framework",
                        verbose_name="Base Framework",
                    ),
                ),
                (
                    "compliance_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conmon_profiles",
                        to="core.complianceassessment",
                        verbose_name="Compliance Assessment",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "ConMon Profile",
                "verbose_name_plural": "ConMon Profiles",
            },
        ),
        migrations.CreateModel(
            name="ConMonMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("completion_rate", "Activity Completion Rate"),
                            ("on_time_rate", "On-Time Completion Rate"),
                            ("evidence_freshness", "Evidence Freshness"),
                            ("vuln_remediation_time", "Vulnerability Remediation Time"),
                            ("poam_aging", "POA&M Aging"),
                            ("scan_compliance", "Scan Compliance"),
                            ("control_effectiveness", "Control Effectiveness"),
                            ("incident_response_time", "Incident Response Time"),
                        ],
                        max_length=50,
                        verbose_name="Metric Type",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Period Start")),
                ("period_end", models.DateField(verbose_name="Period End")),
                ("value", models.FloatField(verbose_name="Value")),
                (
                    "target",
                    models.FloatField(blank=True, null=True, verbose_name="Target"),
                ),
                (
                    "unit",
                    models.CharField(default="%", max_length=20, verbose_name="Unit"),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("up", "Improving"),
                            ("down", "Declining"),
                            ("stable", "Stable"),
                        ],
                        default="stable",
                        max_length=10,
                        verbose_name="Trend",
                    ),
                ),
                (
                    "trend_value",
                    models.FloatField(
                        default=0,
                        help_text="Change from previous period",
                        verbose_name="Trend Value",
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed breakdown of metric components",
                        verbose_name="Breakdown",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="continuous_monitoring.conmonprofile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ConMon Metric",
                "verbose_name_plural": "ConMon Metrics",
                "ordering": ["-period_end", "metric_type"],
            },
        ),
        migrations.AddField(
            model_name="conmonactivityconfig",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_configs",
                to="continuous_monitoring.conmonprofile",
                verbose_name="Profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conmonactivityconfig",
            unique_together={("profile", "requirement_urn")},
        ),
    ]
