# Generated by Django 5.2.9 on 2026-01-23 00:53

import core.domain.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("objective", models.TextField(blank=True, null=True)),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("policy", "Policy"),
                            ("process", "Process"),
                            ("technical", "Technical"),
                            ("physical", "Physical"),
                            ("procedure", "Procedure"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "legalRequirementIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of legal requirement IDs",
                        size=None,
                    ),
                ),
                (
                    "relatedControlIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of related control IDs",
                        size=None,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Control",
                "verbose_name_plural": "Controls",
                "db_table": "control_library_controls",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state", "control_type"],
                        name="control_lib_lifecyc_95e700_idx",
                    ),
                    models.Index(fields=["name"], name="control_lib_name_061e13_idx"),
                    models.Index(
                        fields=["ref_id"], name="control_lib_ref_id_23c611_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ControlImplementation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("controlId", models.UUIDField(db_index=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("service", "Service"),
                            ("process", "Process"),
                            ("third_party", "Third Party"),
                            ("org_unit", "Organizational Unit"),
                            ("data_flow", "Data Flow"),
                            ("data_asset", "Data Asset"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("target_id", models.UUIDField(db_index=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("implemented", "Implemented"),
                            ("operating", "Operating"),
                            ("ineffective", "Ineffective"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "ownerUserIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of owner user IDs",
                        size=None,
                    ),
                ),
                (
                    "evidenceIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of evidence IDs",
                        size=None,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("ad_hoc", "Ad Hoc"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        db_index=True,
                        default="ad_hoc",
                        max_length=20,
                    ),
                ),
                (
                    "last_tested_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "effectiveness_rating",
                    models.IntegerField(
                        blank=True, help_text="Effectiveness rating (1-5)", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Control Implementation",
                "verbose_name_plural": "Control Implementations",
                "db_table": "control_library_control_implementations",
                "indexes": [
                    models.Index(
                        fields=["controlId", "target_type", "target_id"],
                        name="control_lib_control_eb042c_idx",
                    ),
                    models.Index(
                        fields=["lifecycle_state"],
                        name="control_lib_lifecyc_b83945_idx",
                    ),
                    models.Index(
                        fields=["last_tested_at"], name="control_lib_last_te_8105fe_idx"
                    ),
                ],
                "unique_together": {("controlId", "target_type", "target_id")},
            },
        ),
        migrations.CreateModel(
            name="ControlOverview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("control_id", models.UUIDField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("ref_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "control_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("lifecycle_state", models.CharField(db_index=True, max_length=20)),
                ("implementation_count", models.IntegerField(default=0)),
                (
                    "implementation_status_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of implementation statuses by lifecycle state",
                    ),
                ),
                ("evidence_count", models.IntegerField(default=0)),
                ("related_control_count", models.IntegerField(default=0)),
                ("legal_requirement_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Control Overview",
                "verbose_name_plural": "Control Overviews",
                "db_table": "control_library_control_overviews",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="control_lib_lifecyc_28a0d2_idx",
                    ),
                    models.Index(
                        fields=["control_type"], name="control_lib_control_ba4ddb_idx"
                    ),
                    models.Index(fields=["name"], name="control_lib_name_25499d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("link", "Link"),
                            ("system_record", "System Record"),
                        ],
                        db_index=True,
                        default="upload",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("collected", "Collected"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="collected",
                        max_length=20,
                    ),
                ),
                ("uri", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "collected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Evidence Item",
                "verbose_name_plural": "Evidence Items",
                "db_table": "control_library_evidence_items",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state", "source_type"],
                        name="control_lib_lifecyc_d330e9_idx",
                    ),
                    models.Index(
                        fields=["collected_at"], name="control_lib_collect_9b74ba_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="control_lib_expires_89c57e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "policy_version",
                    models.CharField(db_index=True, default="1.0", max_length=50),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "ownerUserIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of owner user IDs",
                        size=None,
                    ),
                ),
                (
                    "relatedControlIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of related control IDs",
                        size=None,
                    ),
                ),
                (
                    "applicableOrgUnitIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of applicable organizational unit IDs",
                        size=None,
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "review_cadence_days",
                    models.IntegerField(
                        blank=True, help_text="Days between reviews", null=True
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "db_table": "control_library_policies",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="control_lib_lifecyc_b3b91a_idx",
                    ),
                    models.Index(
                        fields=["title", "version"], name="control_lib_title_56939c_idx"
                    ),
                    models.Index(
                        fields=["publication_date"],
                        name="control_lib_publica_52a72b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyAcknowledgement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("policyId", models.UUIDField(db_index=True)),
                ("policy_version", models.CharField(db_index=True, max_length=50)),
                ("userId", models.UUIDField(db_index=True)),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("clickwrap", "Clickwrap"),
                            ("training", "Training"),
                            ("doc_sign", "Document Signing"),
                        ],
                        db_index=True,
                        default="clickwrap",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Policy Acknowledgement",
                "verbose_name_plural": "Policy Acknowledgements",
                "db_table": "control_library_policy_acknowledgements",
                "indexes": [
                    models.Index(
                        fields=["policyId", "userId"],
                        name="control_lib_policyI_8f8a1d_idx",
                    ),
                    models.Index(
                        fields=["acknowledged_at"],
                        name="control_lib_acknowl_d63ae5_idx",
                    ),
                ],
                "unique_together": {("policyId", "policy_version", "userId")},
            },
        ),
    ]
