# Generated by Django 5.2.9 on 2026-02-07 02:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="POAMItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "weakness_id",
                    models.CharField(
                        help_text="Unique identifier for the weakness (e.g., V-12345, APP-001)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title/description of the weakness", max_length=500
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the weakness"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("assessment", "Security Assessment"),
                            ("audit", "Security Audit"),
                            ("inspection", "Security Inspection"),
                            ("scan", "Vulnerability Scan"),
                            ("incident", "Security Incident"),
                            ("manual", "Manual Entry"),
                            ("other", "Other"),
                        ],
                        default="assessment",
                        help_text="Source of the weakness identification",
                        max_length=20,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to source document/report",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "system_group_id",
                    models.UUIDField(
                        db_index=True, help_text="Associated system group"
                    ),
                ),
                (
                    "assessment_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Associated compliance assessment",
                        null=True,
                    ),
                ),
                (
                    "vulnerability_finding_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Associated vulnerability finding",
                        null=True,
                    ),
                ),
                (
                    "control_id",
                    models.CharField(
                        blank=True,
                        help_text="Associated security control (e.g., AC-2, IA-5)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cci_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="Associated CCI IDs"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="moderate",
                        help_text="Risk/severity level of the weakness",
                        max_length=20,
                    ),
                ),
                (
                    "impact_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of potential impact",
                        null=True,
                    ),
                ),
                (
                    "likelihood",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="moderate",
                        help_text="Likelihood of exploitation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("deferred", "Deferred"),
                        ],
                        default="draft",
                        help_text="Current status of the POA&M item",
                        max_length=20,
                    ),
                ),
                (
                    "identified_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date the weakness was identified",
                    ),
                ),
                (
                    "submitted_date",
                    models.DateField(
                        blank=True, help_text="Date the POA&M was submitted", null=True
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, help_text="Date the POA&M was approved", null=True
                    ),
                ),
                (
                    "estimated_completion_date",
                    models.DateField(
                        blank=True, help_text="Estimated completion date", null=True
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True, help_text="Actual completion date", null=True
                    ),
                ),
                (
                    "responsible_organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization responsible for remediation",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "point_of_contact",
                    models.CharField(
                        blank=True,
                        help_text="Primary point of contact",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "remediation_plan",
                    models.TextField(
                        blank=True, help_text="Detailed remediation plan", null=True
                    ),
                ),
                (
                    "resources_required",
                    models.TextField(
                        blank=True,
                        help_text="Resources required for remediation",
                        null=True,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated cost for remediation",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "milestones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of remediation milestones with dates and descriptions",
                    ),
                ),
                (
                    "has_deviation",
                    models.BooleanField(
                        default=False, help_text="Whether a deviation request exists"
                    ),
                ),
                (
                    "deviation_justification",
                    models.TextField(
                        blank=True,
                        help_text="Justification for deviation if applicable",
                        null=True,
                    ),
                ),
                (
                    "deviation_approved",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether deviation was approved",
                        null=True,
                    ),
                ),
                (
                    "deviation_approval_date",
                    models.DateField(
                        blank=True, help_text="Date deviation was approved", null=True
                    ),
                ),
                (
                    "evidence_before",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Evidence of weakness before remediation",
                    ),
                ),
                (
                    "evidence_after",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Evidence of remediation completion",
                    ),
                ),
                (
                    "supporting_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional supporting documents",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="General comments and notes", null=True
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="POA&M tags for organization",
                    ),
                ),
                (
                    "last_reviewed_date",
                    models.DateField(
                        blank=True, help_text="Date of last status review", null=True
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, help_text="Date of next scheduled review", null=True
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this weakness has occurred before",
                    ),
                ),
            ],
            options={
                "db_table": "poam_items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["system_group_id", "status"],
                        name="poam_system_status_idx",
                    ),
                    models.Index(fields=["assessment_id"], name="poam_assessment_idx"),
                    models.Index(
                        fields=["vulnerability_finding_id"], name="poam_finding_idx"
                    ),
                    models.Index(fields=["control_id"], name="poam_control_idx"),
                    models.Index(fields=["status"], name="poam_status_idx"),
                    models.Index(fields=["risk_level"], name="poam_risk_level_idx"),
                    models.Index(
                        fields=["estimated_completion_date"],
                        name="poam_completion_date_idx",
                    ),
                    models.Index(fields=["weakness_id"], name="poam_weakness_id_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deviation_type",
                    models.CharField(
                        choices=[
                            ("false_positive", "False Positive"),
                            ("vendor_dependency", "Vendor Dependency"),
                            ("risk_adjustment", "Risk Adjustment"),
                            ("compensating_control", "Compensating Control"),
                            ("operational_requirement", "Operational Requirement"),
                        ],
                        help_text="Category of the deviation request",
                        max_length=30,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Detailed justification for the deviation"
                    ),
                ),
                (
                    "compensating_controls",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of compensating controls in place (required for compensating_control type)",
                    ),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Risk assessment describing residual risk with this deviation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="draft",
                        help_text="Current workflow status of the deviation request",
                        max_length=20,
                    ),
                ),
                (
                    "requested_by",
                    models.CharField(
                        help_text="Name or identifier of the person requesting the deviation",
                        max_length=255,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the deviation was initially requested",
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name or identifier of the reviewer",
                        max_length=255,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the deviation was reviewed",
                        null=True,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes from the reviewer explaining their decision",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this deviation expires and must be re-evaluated. Leave blank for no expiration.",
                        null=True,
                    ),
                ),
                (
                    "poam_item",
                    models.ForeignKey(
                        help_text="The POA&M item this deviation request is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deviation_requests",
                        to="poam.poamitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deviation Request",
                "verbose_name_plural": "Deviation Requests",
                "db_table": "poam_deviation_requests",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["poam_item", "status"], name="deviation_poam_status_idx"
                    ),
                    models.Index(fields=["status"], name="deviation_status_idx"),
                    models.Index(fields=["deviation_type"], name="deviation_type_idx"),
                    models.Index(
                        fields=["expiration_date"], name="deviation_expiration_idx"
                    ),
                ],
            },
        ),
    ]
