# Generated by Django 5.2.9 on 2026-02-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VendorToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="URL-safe access token sent to the vendor.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of the token for verification.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        help_text="UUID of the vendor Entity this token belongs to."
                    ),
                ),
                (
                    "questionnaire_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the Questionnaire this token grants access to.",
                        null=True,
                    ),
                ),
                (
                    "entity_assessment_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the EntityAssessment this token is associated with.",
                        null=True,
                    ),
                ),
                (
                    "vendor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the vendor contact who received this token.",
                        max_length=254,
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name for the vendor contact.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Expiry timestamp after which the token is no longer valid."
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the most recent use of this token.",
                        null=True,
                    ),
                ),
                (
                    "is_revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this token has been manually revoked.",
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        default=0,
                        help_text="Maximum number of times this token can be used (0 = unlimited).",
                    ),
                ),
                (
                    "use_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this token has been used."
                    ),
                ),
            ],
            options={
                "db_table": "vendor_portal_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["entity_id"], name="vpt_entity_idx"),
                    models.Index(fields=["expires_at"], name="vpt_expires_idx"),
                    models.Index(fields=["token_hash"], name="vpt_hash_idx"),
                ],
            },
        ),
    ]
