WITH role_permission_backfill(role_name, permission) AS (
  VALUES
    ('Administrator', 'view_entity'),
    ('Administrator', 'add_entity'),
    ('Administrator', 'change_entity'),
    ('Administrator', 'view_solution'),
    ('Administrator', 'add_solution'),
    ('Administrator', 'change_solution'),
    ('Administrator', 'view_contract'),
    ('Administrator', 'add_contract'),
    ('Administrator', 'change_contract'),
    ('Administrator', 'view_entityassessment'),
    ('Administrator', 'add_entityassessment'),
    ('Administrator', 'change_entityassessment'),
    ('Administrator', 'view_processing'),
    ('Administrator', 'add_processing'),
    ('Administrator', 'change_processing'),
    ('Administrator', 'view_rightrequest'),
    ('Administrator', 'add_rightrequest'),
    ('Administrator', 'change_rightrequest'),
    ('Administrator', 'view_databreach'),
    ('Administrator', 'add_databreach'),
    ('Administrator', 'change_databreach'),
    ('Administrator', 'view_bia'),
    ('Administrator', 'add_bia'),
    ('Administrator', 'change_bia'),
    ('Domain Manager', 'view_entity'),
    ('Domain Manager', 'view_solution'),
    ('Domain Manager', 'view_contract'),
    ('Domain Manager', 'view_entityassessment'),
    ('Domain Manager', 'view_processing'),
    ('Domain Manager', 'view_rightrequest'),
    ('Domain Manager', 'view_databreach'),
    ('Domain Manager', 'view_bia'),
    ('Analyst', 'view_entity'),
    ('Analyst', 'add_entity'),
    ('Analyst', 'change_entity'),
    ('Analyst', 'view_solution'),
    ('Analyst', 'add_solution'),
    ('Analyst', 'change_solution'),
    ('Analyst', 'view_contract'),
    ('Analyst', 'add_contract'),
    ('Analyst', 'change_contract'),
    ('Analyst', 'view_entityassessment'),
    ('Analyst', 'add_entityassessment'),
    ('Analyst', 'change_entityassessment'),
    ('Analyst', 'view_processing'),
    ('Analyst', 'add_processing'),
    ('Analyst', 'change_processing'),
    ('Analyst', 'view_rightrequest'),
    ('Analyst', 'add_rightrequest'),
    ('Analyst', 'change_rightrequest'),
    ('Analyst', 'view_databreach'),
    ('Analyst', 'add_databreach'),
    ('Analyst', 'change_databreach'),
    ('Analyst', 'view_bia'),
    ('Analyst', 'add_bia'),
    ('Analyst', 'change_bia'),
    ('Reader', 'view_entity'),
    ('Reader', 'view_solution'),
    ('Reader', 'view_contract'),
    ('Reader', 'view_entityassessment'),
    ('Reader', 'view_processing'),
    ('Reader', 'view_rightrequest'),
    ('Reader', 'view_databreach'),
    ('Reader', 'view_bia')
)
INSERT OR IGNORE INTO role_permissions (role_id, permission)
SELECT roles.id, role_permission_backfill.permission
FROM roles
INNER JOIN role_permission_backfill
  ON role_permission_backfill.role_name = roles.name
WHERE roles.builtin = 1;
