# Generated by Django 5.2.9 on 2026-01-23 00:53

import core.domain.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Internal file path for storage",
                        max_length=500,
                        unique=True,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "content_type",
                    models.CharField(help_text="MIME content type", max_length=100),
                ),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA-256 hash of file content", max_length=128
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot"),
                            ("document", "Document"),
                            ("evidence", "Evidence"),
                            ("configuration", "Configuration File"),
                            ("log", "Log File"),
                            ("report", "Report"),
                            ("certificate", "Certificate"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of artifact",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Artifact title", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Artifact description and context",
                        null=True,
                    ),
                ),
                (
                    "system_group_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Associated system group",
                        null=True,
                    ),
                ),
                (
                    "checklist_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Associated STIG checklist",
                        null=True,
                    ),
                ),
                (
                    "vulnerability_finding_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Associated vulnerability finding",
                        null=True,
                    ),
                ),
                (
                    "nessus_scan_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Associated Nessus scan",
                        null=True,
                    ),
                ),
                (
                    "control_id",
                    models.CharField(
                        blank=True,
                        help_text="Associated RMF control (e.g., AC-2, IA-5)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cci_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="Associated CCI IDs"
                    ),
                ),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal Use"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        help_text="Security classification level",
                        max_length=15,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether artifact is publicly accessible",
                    ),
                ),
                (
                    "access_list",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of users/groups with access (if not public)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether artifact is active/available"
                    ),
                ),
                (
                    "retention_period_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Retention period in days (null = indefinite)",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiration date for automatic cleanup",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Artifact tags for organization",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source of the artifact (e.g., 'manual_upload', 'nessus_scan')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Artifact version or revision",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "rmf_operations_artifacts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["system_group_id"], name="rmf_artifact_sysgrp_idx"
                    ),
                    models.Index(
                        fields=["checklist_id"], name="rmf_artifact_checklist_idx"
                    ),
                    models.Index(
                        fields=["vulnerability_finding_id"],
                        name="rmf_artifact_finding_idx",
                    ),
                    models.Index(
                        fields=["nessus_scan_id"], name="rmf_artifact_scan_idx"
                    ),
                    models.Index(
                        fields=["artifact_type", "is_active"],
                        name="rmf_artifact_type_active_idx",
                    ),
                    models.Index(
                        fields=["control_id"], name="rmf_artifact_control_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="rmf_artifact_expires_idx"
                    ),
                    models.Index(
                        fields=["security_level"], name="rmf_artifact_security_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(help_text="User who performed the action"),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username for display purposes", max_length=150
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("import_ckl", "Import CKL"),
                            ("export_ckl", "Export CKL"),
                            ("bulk_update", "Bulk Update"),
                            ("compliance_check", "Compliance Check"),
                            ("activate", "Activate"),
                            ("archive", "Archive"),
                            ("assign_system", "Assign to System"),
                            ("remove_from_system", "Remove from System"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("system_group", "System Group"),
                            ("stig_checklist", "STIG Checklist"),
                            ("vulnerability_finding", "Vulnerability Finding"),
                            ("checklist_score", "Checklist Score"),
                            ("nessus_scan", "Nessus Scan"),
                        ],
                        help_text="Type of entity affected",
                        max_length=21,
                    ),
                ),
                ("entity_id", models.UUIDField(help_text="ID of the affected entity")),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Human-readable entity name/title", max_length=255
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="Previous values before the change",
                        null=True,
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="New values after the change", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string from the request",
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Session identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        help_text="Request correlation ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the operation was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if operation failed",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "rmf_operations_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id"], name="rmf_audit_user_idx"),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="rmf_audit_entity_idx"
                    ),
                    models.Index(fields=["action_type"], name="rmf_audit_action_idx"),
                    models.Index(fields=["created_at"], name="rmf_audit_created_idx"),
                    models.Index(fields=["success"], name="rmf_audit_success_idx"),
                    models.Index(
                        fields=["correlation_id"], name="rmf_audit_correlation_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChecklistScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "checklistId",
                    models.UUIDField(
                        db_index=True, help_text="ID of the STIG checklist", unique=True
                    ),
                ),
                (
                    "systemGroupId",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the system group (for system-level aggregation)",
                        null=True,
                    ),
                ),
                (
                    "hostName",
                    models.CharField(
                        db_index=True,
                        help_text="Hostname from checklist",
                        max_length=255,
                    ),
                ),
                (
                    "stigType",
                    models.CharField(
                        db_index=True, help_text="STIG type", max_length=255
                    ),
                ),
                (
                    "totalCat1Open",
                    models.IntegerField(
                        default=0, help_text="Total CAT I open vulnerabilities"
                    ),
                ),
                (
                    "totalCat1NotAFinding",
                    models.IntegerField(
                        default=0, help_text="Total CAT I not a finding vulnerabilities"
                    ),
                ),
                (
                    "totalCat1NotApplicable",
                    models.IntegerField(
                        default=0,
                        help_text="Total CAT I not applicable vulnerabilities",
                    ),
                ),
                (
                    "totalCat1NotReviewed",
                    models.IntegerField(
                        default=0, help_text="Total CAT I not reviewed vulnerabilities"
                    ),
                ),
                (
                    "totalCat2Open",
                    models.IntegerField(
                        default=0, help_text="Total CAT II open vulnerabilities"
                    ),
                ),
                (
                    "totalCat2NotAFinding",
                    models.IntegerField(
                        default=0,
                        help_text="Total CAT II not a finding vulnerabilities",
                    ),
                ),
                (
                    "totalCat2NotApplicable",
                    models.IntegerField(
                        default=0,
                        help_text="Total CAT II not applicable vulnerabilities",
                    ),
                ),
                (
                    "totalCat2NotReviewed",
                    models.IntegerField(
                        default=0, help_text="Total CAT II not reviewed vulnerabilities"
                    ),
                ),
                (
                    "totalCat3Open",
                    models.IntegerField(
                        default=0, help_text="Total CAT III open vulnerabilities"
                    ),
                ),
                (
                    "totalCat3NotAFinding",
                    models.IntegerField(
                        default=0,
                        help_text="Total CAT III not a finding vulnerabilities",
                    ),
                ),
                (
                    "totalCat3NotApplicable",
                    models.IntegerField(
                        default=0,
                        help_text="Total CAT III not applicable vulnerabilities",
                    ),
                ),
                (
                    "totalCat3NotReviewed",
                    models.IntegerField(
                        default=0,
                        help_text="Total CAT III not reviewed vulnerabilities",
                    ),
                ),
                (
                    "lastCalculatedAt",
                    models.DateTimeField(
                        db_index=True, help_text="When the score was last calculated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Score",
                "verbose_name_plural": "Checklist Scores",
                "db_table": "rmf_checklist_scores",
                "ordering": ["-lastCalculatedAt"],
                "indexes": [
                    models.Index(
                        fields=["checklistId"], name="rmf_checkli_checkli_a34260_idx"
                    ),
                    models.Index(
                        fields=["systemGroupId"], name="rmf_checkli_systemG_840350_idx"
                    ),
                    models.Index(
                        fields=["stigType"], name="rmf_checkli_stigTyp_d6878c_idx"
                    ),
                    models.Index(
                        fields=["lastCalculatedAt"],
                        name="rmf_checkli_lastCal_26e947_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NessusScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "systemGroupId",
                    models.UUIDField(
                        db_index=True, help_text="Associated system group for this scan"
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original Nessus scan filename", max_length=255
                    ),
                ),
                (
                    "raw_xml_content",
                    models.TextField(help_text="Complete raw Nessus XML scan data"),
                ),
                (
                    "scan_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the Nessus scan was performed",
                        null=True,
                    ),
                ),
                (
                    "scanner_version",
                    models.CharField(
                        blank=True,
                        help_text="Nessus scanner version",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "policy_name",
                    models.CharField(
                        blank=True,
                        help_text="Nessus scan policy name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "total_hosts",
                    models.IntegerField(
                        default=0, help_text="Total number of hosts scanned"
                    ),
                ),
                (
                    "total_vulnerabilities",
                    models.IntegerField(
                        default=0, help_text="Total number of vulnerabilities found"
                    ),
                ),
                (
                    "scan_duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration of the scan in seconds",
                        null=True,
                    ),
                ),
                (
                    "critical_count",
                    models.IntegerField(
                        default=0, help_text="Critical severity vulnerabilities"
                    ),
                ),
                (
                    "high_count",
                    models.IntegerField(
                        default=0, help_text="High severity vulnerabilities"
                    ),
                ),
                (
                    "medium_count",
                    models.IntegerField(
                        default=0, help_text="Medium severity vulnerabilities"
                    ),
                ),
                (
                    "low_count",
                    models.IntegerField(
                        default=0, help_text="Low severity vulnerabilities"
                    ),
                ),
                (
                    "info_count",
                    models.IntegerField(default=0, help_text="Informational findings"),
                ),
                (
                    "correlated_checklist_ids",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="CKL checklists correlated with this scan",
                        size=None,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom tags for organization",
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        help_text="Current processing status of the scan",
                        max_length=20,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "rmf_operations_nessus_scans",
                "ordering": ["-scan_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["systemGroupId"], name="rmf_nessus_sysgrp_idx"
                    ),
                    models.Index(fields=["scan_date"], name="rmf_nessus_scan_date_idx"),
                    models.Index(
                        fields=["processing_status"], name="rmf_nessus_status_idx"
                    ),
                    models.Index(fields=["created_at"], name="rmf_nessus_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StigChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "systemGroupId",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the system group this checklist belongs to",
                        null=True,
                    ),
                ),
                (
                    "hostName",
                    models.CharField(
                        db_index=True,
                        help_text="Hostname of the asset being checked",
                        max_length=255,
                    ),
                ),
                (
                    "stigType",
                    models.CharField(
                        db_index=True,
                        help_text="STIG type (e.g., 'Windows Server 2019')",
                        max_length=255,
                    ),
                ),
                (
                    "stigRelease",
                    models.CharField(
                        help_text="STIG release info (e.g., 'Release: 2.5')",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="STIG version number", max_length=50),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current lifecycle state",
                        max_length=20,
                    ),
                ),
                (
                    "assetInfo",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Asset information from CKL file (HOST_NAME, HOST_IP, etc.)",
                    ),
                ),
                (
                    "rawCklData",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete CKL file structure for export",
                    ),
                ),
                (
                    "isWebDatabase",
                    models.BooleanField(
                        default=False, help_text="Whether this is a web/database STIG"
                    ),
                ),
                (
                    "webDatabaseSite",
                    models.CharField(
                        blank=True,
                        help_text="Web site/application name",
                        max_length=255,
                    ),
                ),
                (
                    "webDatabaseInstance",
                    models.CharField(
                        blank=True, help_text="Database instance name", max_length=255
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("computing", "Computing"),
                            ("network", "Network"),
                            ("storage", "Storage"),
                            ("application", "Application"),
                            ("database", "Database"),
                            ("web_server", "Web Server"),
                            ("other", "Other"),
                        ],
                        default="computing",
                        help_text="Type of asset this checklist applies to",
                        max_length=20,
                    ),
                ),
                (
                    "vulnerabilityFindingIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of vulnerability finding IDs in this checklist",
                        size=None,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Checklist tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "STIG Checklist",
                "verbose_name_plural": "STIG Checklists",
                "db_table": "rmf_stig_checklists",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["systemGroupId", "lifecycle_state"],
                        name="rmf_stig_ch_systemG_dbdb13_idx",
                    ),
                    models.Index(
                        fields=["stigType", "version"],
                        name="rmf_stig_ch_stigTyp_13a2d4_idx",
                    ),
                    models.Index(
                        fields=["hostName"], name="rmf_stig_ch_hostNam_ca305b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="rmf_stig_ch_created_32a238_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="rmf_stig_ch_updated_44cd06_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StigTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Windows Server 2019 Member Server')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Template description and usage notes",
                        null=True,
                    ),
                ),
                (
                    "stig_type",
                    models.CharField(
                        db_index=True,
                        help_text="STIG type (e.g., 'Windows Server 2019')",
                        max_length=255,
                    ),
                ),
                (
                    "stig_release",
                    models.CharField(help_text="STIG release version", max_length=100),
                ),
                (
                    "stig_version",
                    models.CharField(help_text="STIG version number", max_length=50),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("user", "User Template"),
                            ("system", "System Template"),
                            ("benchmark", "Benchmark Template"),
                        ],
                        default="user",
                        help_text="Type of template (user-created, system, or benchmark)",
                        max_length=20,
                    ),
                ),
                (
                    "raw_ckl_content",
                    models.TextField(
                        help_text="Raw CKL template content for instantiation"
                    ),
                ),
                (
                    "benchmark_title",
                    models.CharField(
                        blank=True,
                        help_text="Official benchmark title",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "benchmark_date",
                    models.DateField(
                        blank=True, help_text="Benchmark publication date", null=True
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of checklists created from this template",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this template was last used to create a checklist",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is available for use",
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an official DISA template",
                    ),
                ),
                (
                    "created_from_checklist_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of checklist this template was created from",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Template tags for organization",
                    ),
                ),
                (
                    "compatible_systems",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of compatible system types",
                    ),
                ),
            ],
            options={
                "db_table": "rmf_operations_stig_templates",
                "ordering": ["-usage_count", "-last_used_at", "name"],
                "indexes": [
                    models.Index(
                        fields=["stig_type", "template_type"],
                        name="rmf_template_stig_type_idx",
                    ),
                    models.Index(
                        fields=["is_active", "template_type"],
                        name="rmf_template_active_type_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="rmf_template_created_idx"
                    ),
                    models.Index(fields=["usage_count"], name="rmf_template_usage_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="System name", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="System description", null=True
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current lifecycle state",
                        max_length=20,
                    ),
                ),
                (
                    "checklistIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of STIG checklist IDs in this system",
                        size=None,
                    ),
                ),
                (
                    "assetIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of asset IDs in this system",
                        size=None,
                    ),
                ),
                (
                    "nessusScanIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        help_text="Array of Nessus scan IDs for this system",
                        size=None,
                    ),
                ),
                (
                    "asset_hierarchy",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Asset hierarchy and relationships within this system group",
                    ),
                ),
                (
                    "last_compliance_check",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last compliance verification",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, help_text="System tags"),
                ),
                (
                    "totalChecklists",
                    models.IntegerField(
                        default=0, help_text="Total number of checklists"
                    ),
                ),
                (
                    "totalOpenVulnerabilities",
                    models.IntegerField(
                        default=0,
                        help_text="Total open vulnerabilities across all checklists",
                    ),
                ),
                (
                    "totalCat1Open",
                    models.IntegerField(
                        default=0, help_text="Total CAT I open vulnerabilities"
                    ),
                ),
                (
                    "totalCat2Open",
                    models.IntegerField(
                        default=0, help_text="Total CAT II open vulnerabilities"
                    ),
                ),
                (
                    "totalCat3Open",
                    models.IntegerField(
                        default=0, help_text="Total CAT III open vulnerabilities"
                    ),
                ),
            ],
            options={
                "verbose_name": "System Group",
                "verbose_name_plural": "System Groups",
                "db_table": "rmf_system_groups",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state", "name"],
                        name="rmf_system__lifecyc_5d6c7e_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="rmf_system__created_fee2f7_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="rmf_system__updated_2f3176_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "checklistId",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID of the STIG checklist this finding belongs to",
                    ),
                ),
                (
                    "vulnId",
                    models.CharField(
                        db_index=True,
                        help_text="Vulnerability ID (e.g., 'V-12345')",
                        max_length=50,
                    ),
                ),
                (
                    "stigId",
                    models.CharField(
                        db_index=True, help_text="STIG ID reference", max_length=50
                    ),
                ),
                ("ruleId", models.CharField(help_text="Rule ID", max_length=50)),
                ("ruleTitle", models.CharField(help_text="Rule title", max_length=500)),
                (
                    "ruleDiscussion",
                    models.TextField(
                        blank=True, help_text="Rule discussion/explanation", null=True
                    ),
                ),
                (
                    "checkContent",
                    models.TextField(
                        blank=True, help_text="Check content/procedure", null=True
                    ),
                ),
                (
                    "fixText",
                    models.TextField(
                        blank=True, help_text="Fix text/remediation", null=True
                    ),
                ),
                (
                    "status_data",
                    models.JSONField(
                        default=dict, help_text="Vulnerability status data"
                    ),
                ),
                (
                    "severity_category",
                    models.CharField(
                        db_index=True,
                        help_text="Severity category (cat1, cat2, cat3)",
                        max_length=10,
                    ),
                ),
                (
                    "ruleVersion",
                    models.CharField(
                        blank=True, help_text="Rule version", max_length=50
                    ),
                ),
                (
                    "cciIds",
                    models.JSONField(
                        default=list, help_text="Common Control Identifier IDs"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Finding tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability Finding",
                "verbose_name_plural": "Vulnerability Findings",
                "db_table": "rmf_vulnerability_findings",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["checklistId", "status_data"],
                        name="rmf_vulnera_checkli_5859c5_idx",
                    ),
                    models.Index(
                        fields=["severity_category", "status_data"],
                        name="rmf_vulnera_severit_6a5de2_idx",
                    ),
                    models.Index(
                        fields=["stigId"], name="rmf_vulnera_stigId_1d06c6_idx"
                    ),
                    models.Index(
                        fields=["vulnId"], name="rmf_vulnera_vulnId_9632d7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="rmf_vulnera_created_73ecf2_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="rmf_vulnera_updated_6d8c76_idx"
                    ),
                ],
                "unique_together": {("checklistId", "vulnId")},
            },
        ),
    ]
