# Generated by Django 5.2.9 on 2026-01-23 05:42

import core.domain.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rmf_operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudServiceOffering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="CSO name", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="CSO description", null=True
                    ),
                ),
                (
                    "service_model",
                    models.CharField(
                        choices=[
                            ("IaaS", "Infrastructure as a Service"),
                            ("PaaS", "Platform as a Service"),
                            ("SaaS", "Software as a Service"),
                        ],
                        default="SaaS",
                        help_text="Cloud service model",
                        max_length=20,
                    ),
                ),
                (
                    "deployment_model",
                    models.CharField(
                        choices=[
                            ("public", "Public Cloud"),
                            ("private", "Private Cloud"),
                            ("community", "Community Cloud"),
                            ("hybrid", "Hybrid Cloud"),
                            ("government", "Government-Only Cloud"),
                        ],
                        default="public",
                        help_text="Cloud deployment model",
                        max_length=20,
                    ),
                ),
                (
                    "authorization_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "FedRAMP Ready"),
                            ("in_process", "In Process"),
                            ("authorized", "FedRAMP Authorized"),
                            ("revoked", "Authorization Revoked"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current FedRAMP authorization status",
                        max_length=20,
                    ),
                ),
                (
                    "impact_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        default="moderate",
                        help_text="FedRAMP impact level",
                        max_length=20,
                    ),
                ),
                (
                    "authorization_date",
                    models.DateField(
                        blank=True, help_text="Date of FedRAMP authorization", null=True
                    ),
                ),
                (
                    "authorization_expiration",
                    models.DateField(
                        blank=True, help_text="Authorization expiration date", null=True
                    ),
                ),
                (
                    "last_assessment_date",
                    models.DateField(
                        blank=True, help_text="Date of last assessment", null=True
                    ),
                ),
                (
                    "next_assessment_date",
                    models.DateField(
                        blank=True,
                        help_text="Scheduled next assessment date",
                        null=True,
                    ),
                ),
                (
                    "fedramp_package_id",
                    models.CharField(
                        blank=True,
                        help_text="Official FedRAMP package identifier",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "marketplace_listing_url",
                    models.URLField(
                        blank=True,
                        help_text="FedRAMP Marketplace listing URL",
                        null=True,
                    ),
                ),
                (
                    "authorization_boundary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Authorization boundary definition including components and data flows",
                    ),
                ),
                (
                    "data_centers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of data center regions/locations",
                    ),
                ),
                (
                    "leveraged_services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Leveraged FedRAMP authorized services",
                    ),
                ),
                (
                    "sponsoring_agencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of sponsoring federal agencies",
                    ),
                ),
                (
                    "initial_sponsor",
                    models.CharField(
                        blank=True,
                        help_text="Initial authorizing agency",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "third_party_assessment_org",
                    models.CharField(
                        blank=True,
                        help_text="Third Party Assessment Organization (3PAO)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_3pao_assessment_date",
                    models.DateField(
                        blank=True, help_text="Date of last 3PAO assessment", null=True
                    ),
                ),
                (
                    "total_ksi_count",
                    models.IntegerField(
                        default=0, help_text="Total number of applicable KSIs"
                    ),
                ),
                (
                    "compliant_ksi_count",
                    models.IntegerField(
                        default=0, help_text="Number of compliant KSIs"
                    ),
                ),
                (
                    "ksi_compliance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Overall KSI compliance percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "persistent_validation_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of KSIs with automated persistent validation (target: 70%+)",
                        max_digits=5,
                    ),
                ),
                (
                    "compliance_assessment_ids",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True,
                        help_text="Array of linked compliance assessment IDs",
                        null=True,
                    ),
                ),
                (
                    "system_group_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Linked SystemGroup for RMF operations",
                        null=True,
                    ),
                ),
                (
                    "perimeter_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Linked Perimeter from CISO Assistant core",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, help_text="CSO tags"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cloud Service Offering",
                "verbose_name_plural": "Cloud Service Offerings",
                "db_table": "fedramp_cloud_service_offerings",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["authorization_status", "impact_level"],
                        name="fedramp_clo_authori_652334_idx",
                    ),
                    models.Index(
                        fields=["fedramp_package_id"],
                        name="fedramp_clo_fedramp_3cc6c2_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="fedramp_clo_created_e19be4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KSIImplementation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "cloud_service_offering_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Cloud Service Offering this KSI belongs to",
                    ),
                ),
                (
                    "ksi_urn",
                    models.CharField(
                        help_text="URN reference to the KSI framework requirement",
                        max_length=255,
                    ),
                ),
                (
                    "ksi_ref_id",
                    models.CharField(
                        db_index=True,
                        help_text="KSI reference ID (e.g., KSI-AFR-01)",
                        max_length=50,
                    ),
                ),
                (
                    "ksi_category",
                    models.CharField(
                        db_index=True,
                        help_text="KSI category (e.g., AFR, CED, CMT)",
                        max_length=50,
                    ),
                ),
                (
                    "ksi_name",
                    models.CharField(help_text="KSI name for display", max_length=255),
                ),
                (
                    "applies_to_low",
                    models.BooleanField(
                        default=False, help_text="Applies to Low impact"
                    ),
                ),
                (
                    "applies_to_moderate",
                    models.BooleanField(
                        default=True, help_text="Applies to Moderate impact"
                    ),
                ),
                (
                    "applies_to_high",
                    models.BooleanField(
                        default=True, help_text="Applies to High impact"
                    ),
                ),
                (
                    "implementation_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("implemented", "Implemented"),
                            ("not_applicable", "Not Applicable"),
                            ("partial", "Partially Implemented"),
                        ],
                        db_index=True,
                        default="not_started",
                        help_text="Current implementation status",
                        max_length=20,
                    ),
                ),
                (
                    "implementation_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of how the KSI is implemented",
                        null=True,
                    ),
                ),
                (
                    "implementation_date",
                    models.DateField(
                        blank=True,
                        help_text="Date implementation was completed",
                        null=True,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("not_validated", "Not Validated"),
                            ("manual", "Manual Validation"),
                            ("automated", "Automated Validation"),
                            ("hybrid", "Hybrid (Manual + Automated)"),
                        ],
                        default="not_validated",
                        help_text="How this KSI is validated",
                        max_length=20,
                    ),
                ),
                (
                    "validation_method",
                    models.TextField(
                        blank=True,
                        help_text="Description of validation method/procedure",
                        null=True,
                    ),
                ),
                (
                    "last_validation_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of last validation", null=True
                    ),
                ),
                (
                    "last_validation_result",
                    models.BooleanField(
                        blank=True,
                        help_text="Result of last validation (True=pass, False=fail)",
                        null=True,
                    ),
                ),
                (
                    "validation_frequency_days",
                    models.IntegerField(
                        default=30,
                        help_text="How often this KSI should be validated (days)",
                    ),
                ),
                (
                    "has_persistent_validation",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this KSI has automated persistent validation",
                    ),
                ),
                (
                    "persistent_validation_rule_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the PersistentValidationRule if automated",
                        null=True,
                    ),
                ),
                (
                    "validation_automation_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of validation that is automated",
                        max_digits=5,
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("pending", "Pending Review"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        help_text="Current compliance status",
                        max_length=20,
                    ),
                ),
                (
                    "compliance_notes",
                    models.TextField(
                        blank=True, help_text="Notes on compliance status", null=True
                    ),
                ),
                (
                    "nist_controls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Mapped NIST SP 800-53 controls",
                    ),
                ),
                (
                    "applied_control_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of applied controls that satisfy this KSI",
                    ),
                ),
                (
                    "evidence_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs of evidence artifacts supporting this KSI",
                    ),
                ),
                (
                    "last_evidence_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of most recent evidence", null=True
                    ),
                ),
                (
                    "poam_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of POA&M item if non-compliant",
                        null=True,
                    ),
                ),
                (
                    "remediation_plan",
                    models.TextField(
                        blank=True,
                        help_text="Remediation plan for non-compliance",
                        null=True,
                    ),
                ),
                (
                    "remediation_target_date",
                    models.DateField(
                        blank=True, help_text="Target date for remediation", null=True
                    ),
                ),
                (
                    "assessor_notes",
                    models.TextField(
                        blank=True, help_text="Notes from assessor/auditor", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "KSI Implementation",
                "verbose_name_plural": "KSI Implementations",
                "db_table": "fedramp_ksi_implementations",
                "ordering": ["ksi_category", "ksi_ref_id"],
                "indexes": [
                    models.Index(
                        fields=["cloud_service_offering_id", "compliance_status"],
                        name="fedramp_ksi_cloud_s_bca175_idx",
                    ),
                    models.Index(
                        fields=["ksi_category", "implementation_status"],
                        name="fedramp_ksi_ksi_cat_18f7b1_idx",
                    ),
                    models.Index(
                        fields=["has_persistent_validation"],
                        name="fedramp_ksi_has_per_cd5a1c_idx",
                    ),
                    models.Index(
                        fields=["last_validation_date"],
                        name="fedramp_ksi_last_va_f10edc_idx",
                    ),
                ],
                "unique_together": {("cloud_service_offering_id", "ksi_urn")},
            },
        ),
        migrations.CreateModel(
            name="OngoingAuthorizationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "cloud_service_offering_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Cloud Service Offering this OAR belongs to",
                    ),
                ),
                (
                    "report_title",
                    models.CharField(help_text="Report title", max_length=255),
                ),
                (
                    "reporting_period_quarter",
                    models.CharField(
                        choices=[
                            ("Q1", "Q1 (Jan-Mar)"),
                            ("Q2", "Q2 (Apr-Jun)"),
                            ("Q3", "Q3 (Jul-Sep)"),
                            ("Q4", "Q4 (Oct-Dec)"),
                        ],
                        help_text="Reporting quarter",
                        max_length=2,
                    ),
                ),
                (
                    "reporting_period_year",
                    models.IntegerField(help_text="Reporting year"),
                ),
                (
                    "reporting_period_start",
                    models.DateField(help_text="Start of reporting period"),
                ),
                (
                    "reporting_period_end",
                    models.DateField(help_text="End of reporting period"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("revision", "Revision Required"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current report status",
                        max_length=20,
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        blank=True, help_text="Date report was submitted", null=True
                    ),
                ),
                (
                    "acceptance_date",
                    models.DateTimeField(
                        blank=True, help_text="Date report was accepted", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Report due date", null=True
                    ),
                ),
                (
                    "ksi_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="KSI compliance summary at time of report",
                    ),
                ),
                ("total_ksi_count", models.IntegerField(default=0)),
                ("compliant_ksi_count", models.IntegerField(default=0)),
                ("non_compliant_ksi_count", models.IntegerField(default=0)),
                (
                    "ksi_compliance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "validation_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Persistent validation coverage summary",
                    ),
                ),
                (
                    "persistent_validation_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of KSIs with automated validation",
                        max_digits=5,
                    ),
                ),
                (
                    "validation_pass_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Pass rate of automated validations",
                        max_digits=5,
                    ),
                ),
                (
                    "vulnerability_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Vulnerability summary at time of report",
                    ),
                ),
                ("total_open_vulnerabilities", models.IntegerField(default=0)),
                ("critical_vulnerabilities", models.IntegerField(default=0)),
                ("high_vulnerabilities", models.IntegerField(default=0)),
                ("overdue_vulnerabilities", models.IntegerField(default=0)),
                (
                    "poam_summary",
                    models.JSONField(
                        blank=True, default=dict, help_text="POA&M status summary"
                    ),
                ),
                ("total_poam_items", models.IntegerField(default=0)),
                ("open_poam_items", models.IntegerField(default=0)),
                ("closed_poam_items_this_period", models.IntegerField(default=0)),
                ("overdue_poam_items", models.IntegerField(default=0)),
                (
                    "incident_summary",
                    models.JSONField(
                        blank=True, default=dict, help_text="Security incident summary"
                    ),
                ),
                ("total_incidents", models.IntegerField(default=0)),
                ("security_incidents_reported", models.IntegerField(default=0)),
                (
                    "significant_changes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of significant changes during the period",
                    ),
                ),
                (
                    "has_significant_changes",
                    models.BooleanField(
                        default=False,
                        help_text="Whether there were significant changes",
                    ),
                ),
                (
                    "executive_summary",
                    models.TextField(
                        blank=True, help_text="Executive summary narrative", null=True
                    ),
                ),
                (
                    "risk_posture_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Overall risk posture assessment",
                        null=True,
                    ),
                ),
                (
                    "remediation_activities",
                    models.TextField(
                        blank=True,
                        help_text="Summary of remediation activities",
                        null=True,
                    ),
                ),
                (
                    "cso_attestation",
                    models.BooleanField(
                        default=False, help_text="CSO representative attestation"
                    ),
                ),
                ("cso_attestation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "cso_attestation_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cso_attestation_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from FedRAMP/agency reviewer",
                        null=True,
                    ),
                ),
                (
                    "revision_comments",
                    models.TextField(
                        blank=True, help_text="Comments if revision required", null=True
                    ),
                ),
                (
                    "oscal_export_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of OSCAL export if generated",
                        null=True,
                    ),
                ),
                (
                    "json_export_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to JSON export file",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Ongoing Authorization Report",
                "verbose_name_plural": "Ongoing Authorization Reports",
                "db_table": "fedramp_ongoing_authorization_reports",
                "ordering": ["-reporting_period_year", "-reporting_period_quarter"],
                "indexes": [
                    models.Index(
                        fields=["cloud_service_offering_id", "status"],
                        name="fedramp_ong_cloud_s_aa3638_idx",
                    ),
                    models.Index(
                        fields=["status", "due_date"],
                        name="fedramp_ong_status_340bc7_idx",
                    ),
                    models.Index(
                        fields=["submission_date"],
                        name="fedramp_ong_submiss_78a26a_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "cloud_service_offering_id",
                        "reporting_period_year",
                        "reporting_period_quarter",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="PersistentValidationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Rule name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Rule description", null=True
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("scanner", "Scanner Integration"),
                            ("api", "API Check"),
                            ("config", "Configuration Check"),
                            ("log", "Log Analysis"),
                            ("evidence", "Evidence Check"),
                            ("custom", "Custom Script"),
                            ("manual", "Manual with Reminder"),
                        ],
                        default="api",
                        help_text="Type of validation rule",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("deprecated", "Deprecated"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current rule status",
                        max_length=20,
                    ),
                ),
                (
                    "ksi_ref_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of KSI reference IDs this rule validates",
                    ),
                ),
                (
                    "cloud_service_offering_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="CSO this rule applies to (null for global rules)",
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("continuous", "Continuous (Real-time)"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("on_demand", "On Demand"),
                        ],
                        default="daily",
                        help_text="How often the rule should run",
                        max_length=20,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for custom scheduling",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "next_scheduled_run",
                    models.DateTimeField(
                        blank=True, help_text="Next scheduled execution time", null=True
                    ),
                ),
                (
                    "rule_definition",
                    models.JSONField(
                        default=dict, help_text="Rule definition/configuration"
                    ),
                ),
                (
                    "pass_criteria",
                    models.JSONField(
                        default=dict, help_text="Criteria for determining pass/fail"
                    ),
                ),
                (
                    "fail_threshold",
                    models.IntegerField(
                        default=0,
                        help_text="Number of failures before rule is marked as failing",
                    ),
                ),
                (
                    "warning_threshold",
                    models.IntegerField(
                        default=1, help_text="Number of issues before warning"
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        blank=True,
                        help_text="Integration type (e.g., nessus, qualys, aws_config)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "integration_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Integration-specific configuration",
                    ),
                ),
                (
                    "last_execution",
                    models.DateTimeField(
                        blank=True, help_text="Last execution timestamp", null=True
                    ),
                ),
                (
                    "last_result",
                    models.BooleanField(
                        blank=True,
                        help_text="Result of last execution (pass/fail)",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message from last failed execution",
                        null=True,
                    ),
                ),
                (
                    "consecutive_failures",
                    models.IntegerField(
                        default=0, help_text="Number of consecutive failures"
                    ),
                ),
                (
                    "total_executions",
                    models.IntegerField(
                        default=0, help_text="Total number of executions"
                    ),
                ),
                (
                    "total_passes",
                    models.IntegerField(
                        default=0, help_text="Total number of passed executions"
                    ),
                ),
                (
                    "notify_on_failure",
                    models.BooleanField(
                        default=True, help_text="Send notification on failure"
                    ),
                ),
                (
                    "notification_recipients",
                    models.JSONField(
                        default=list,
                        help_text="Email addresses for failure notifications",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Persistent Validation Rule",
                "verbose_name_plural": "Persistent Validation Rules",
                "db_table": "fedramp_persistent_validation_rules",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["status", "frequency"],
                        name="fedramp_per_status_36cf76_idx",
                    ),
                    models.Index(
                        fields=["cloud_service_offering_id", "status"],
                        name="fedramp_per_cloud_s_a10559_idx",
                    ),
                    models.Index(
                        fields=["next_scheduled_run"],
                        name="fedramp_per_next_sc_eca98b_idx",
                    ),
                    models.Index(
                        fields=["rule_type"], name="fedramp_per_rule_ty_b2ce77_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ValidationExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "validation_rule_id",
                    models.UUIDField(
                        db_index=True, help_text="The validation rule that was executed"
                    ),
                ),
                (
                    "execution_timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the validation was executed",
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        default=0, help_text="Execution duration in milliseconds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        help_text="Execution status",
                        max_length=20,
                    ),
                ),
                ("passed", models.BooleanField(help_text="Whether validation passed")),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Numeric score if applicable",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "result_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed results from execution",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if failed", null=True
                    ),
                ),
                (
                    "findings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of findings/issues discovered",
                    ),
                ),
                (
                    "evidence_collected",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Evidence collected during execution",
                    ),
                ),
                (
                    "screenshot_paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Paths to screenshots if applicable",
                    ),
                ),
                (
                    "executed_by",
                    models.CharField(
                        blank=True,
                        help_text="System or user that triggered execution",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        default="scheduled",
                        help_text="What triggered the execution (scheduled, manual, event)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Execution",
                "verbose_name_plural": "Validation Executions",
                "db_table": "fedramp_validation_executions",
                "ordering": ["-execution_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["validation_rule_id", "execution_timestamp"],
                        name="fedramp_val_validat_465dc3_idx",
                    ),
                    models.Index(
                        fields=["status", "execution_timestamp"],
                        name="fedramp_val_status_cfde4a_idx",
                    ),
                    models.Index(
                        fields=["passed"], name="fedramp_val_passed_aafc03_idx"
                    ),
                ],
            },
        ),
    ]
