# Generated by Django 5.2.9 on 2026-01-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rmf_operations", "0003_change_control_incident_response"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="securityincident",
            new_name="fedramp_sec_cloud_s_9a0ea5_idx",
            old_name="fedramp_inc_cso_status_idx",
        ),
        migrations.RenameIndex(
            model_name="securityincident",
            new_name="fedramp_sec_severit_538ca9_idx",
            old_name="fedramp_inc_sev_status_idx",
        ),
        migrations.RenameIndex(
            model_name="securityincident",
            new_name="fedramp_sec_categor_2a456a_idx",
            old_name="fedramp_inc_cat_status_idx",
        ),
        migrations.RenameIndex(
            model_name="securityincident",
            new_name="fedramp_sec_uscert__646ec1_idx",
            old_name="fedramp_inc_uscert_idx",
        ),
        migrations.RenameIndex(
            model_name="securityincident",
            new_name="fedramp_sec_detecte_8b0e2c_idx",
            old_name="fedramp_inc_detected_idx",
        ),
        migrations.RenameIndex(
            model_name="securityincident",
            new_name="fedramp_sec_uscert__b16c18_idx",
            old_name="fedramp_inc_deadline_idx",
        ),
        migrations.RenameIndex(
            model_name="securityincident",
            new_name="fedramp_sec_created_f6faed_idx",
            old_name="fedramp_inc_created_idx",
        ),
        migrations.RenameIndex(
            model_name="significantchangerequest",
            new_name="fedramp_sig_cloud_s_bdd0d7_idx",
            old_name="fedramp_scr_cso_status_idx",
        ),
        migrations.RenameIndex(
            model_name="significantchangerequest",
            new_name="fedramp_sig_status_622661_idx",
            old_name="fedramp_scr_status_scn_idx",
        ),
        migrations.RenameIndex(
            model_name="significantchangerequest",
            new_name="fedramp_sig_change__32fd69_idx",
            old_name="fedramp_scr_type_status_idx",
        ),
        migrations.RenameIndex(
            model_name="significantchangerequest",
            new_name="fedramp_sig_planned_3b051c_idx",
            old_name="fedramp_scr_planned_date_idx",
        ),
        migrations.RenameIndex(
            model_name="significantchangerequest",
            new_name="fedramp_sig_created_866e1a_idx",
            old_name="fedramp_scr_created_idx",
        ),
        migrations.AlterField(
            model_name="securityincident",
            name="detection_method",
            field=models.CharField(
                blank=True,
                help_text="How the incident was detected (e.g., SIEM alert, user report)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="securityincident",
            name="indicators_of_compromise",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of IOCs (IPs, hashes, domains, etc.)",
            ),
        ),
    ]
