export type ThirdPartyEntity = {
  id: string;
  tenantId: string;
  folderId: string;
  folderName: string;
  parentEntityId: string | null;
  parentEntityName: string | null;
  refId: string | null;
  name: string;
  description: string | null;
  relationship: string | null;
  country: string | null;
  currency: string | null;
  isActive: boolean;
  defaultDependency: number;
  defaultPenetration: number;
  defaultMaturity: number;
  defaultTrust: number;
  defaultCriticality: number;
  mission: string | null;
  referenceLink: string | null;
  doraEntityType: string | null;
  doraEntityHierarchy: string | null;
  doraProviderPersonType: string | null;
  solutionCount: number;
  contractCount: number;
  assessmentCount: number;
  createdAt: string;
  updatedAt: string;
};

export type ThirdPartySolution = {
  id: string;
  tenantId: string;
  folderId: string;
  folderName: string;
  providerEntityId: string;
  providerEntityName: string;
  recipientEntityName: string | null;
  refId: string | null;
  name: string;
  description: string | null;
  isActive: boolean;
  criticality: number;
  referenceLink: string | null;
  doraIctServiceType: string | null;
  storageOfData: boolean;
  dataLocationStorage: string | null;
  dataLocationProcessing: string | null;
  doraDataSensitiveness: string | null;
  doraRelianceLevel: string | null;
  doraSubstitutability: string | null;
  doraNonSubstitutabilityReason: string | null;
  doraHasExitPlan: string | null;
  doraReintegrationPossibility: string | null;
  doraDiscontinuingImpact: string | null;
  doraAlternativeProviders: string | null;
  assetRefs: string[];
  createdAt: string;
  updatedAt: string;
};

export type ThirdPartyContract = {
  id: string;
  tenantId: string;
  folderId: string;
  folderName: string;
  providerEntityId: string;
  providerEntityName: string;
  beneficiaryEntityId: string | null;
  beneficiaryEntityName: string | null;
  refId: string | null;
  name: string;
  description: string | null;
  status: string;
  startDate: string | null;
  endDate: string | null;
  currency: string | null;
  annualExpense: number | null;
  isIntragroup: boolean;
  doraContractualArrangement: string | null;
  governingLawCountry: string | null;
  noticePeriodEntity: number | null;
  noticePeriodProvider: number | null;
  doraExclude: boolean;
  solutions: Array<{
    id: string;
    name: string;
  }>;
  createdAt: string;
  updatedAt: string;
};

export type ThirdPartyAssessment = {
  id: string;
  tenantId: string;
  folderId: string;
  folderName: string;
  entityId: string;
  entityName: string;
  perimeterId: string | null;
  perimeterName: string | null;
  complianceAssessmentId: string | null;
  complianceAssessmentName: string | null;
  refId: string | null;
  name: string;
  status: string;
  criticality: number;
  dependency: number;
  penetration: number;
  maturity: number;
  trust: number;
  conclusion: string | null;
  nextReviewOn: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
};

export type ThirdPartyEntityDetail = {
  entity: ThirdPartyEntity;
  solutions: ThirdPartySolution[];
  contracts: ThirdPartyContract[];
  assessments: ThirdPartyAssessment[];
};
