# Generated by Django 5.2.9 on 2026-01-23 02:17

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0131_assessmentrun_awarenesscampaign_awarenesscompletion_and_more"),
        ("iam", "0018_cacheversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceCollectionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "collection_type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot"),
                            ("configuration", "Configuration Export"),
                            ("log", "Log Export"),
                            ("report", "Report"),
                            ("policy", "Policy Document"),
                            ("inventory", "Asset Inventory"),
                            ("scan_result", "Security Scan Result"),
                            ("audit_log", "Audit Log"),
                            ("user_list", "User/Access List"),
                            ("certificate", "Certificate/Key Info"),
                        ],
                        max_length=50,
                        verbose_name="Collection Type",
                    ),
                ),
                (
                    "query",
                    models.TextField(
                        blank=True,
                        help_text="API query, filter expression, or path",
                        null=True,
                        verbose_name="Query/Filter",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parameters"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        help_text="Override source schedule for this rule",
                        max_length=100,
                        null=True,
                        verbose_name="Schedule Override",
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(default=365, verbose_name="Retention Days"),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "target_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evidence_rules",
                        to="core.appliedcontrol",
                        verbose_name="Target Controls",
                    ),
                ),
                (
                    "target_requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evidence_rules",
                        to="core.requirementassessment",
                        verbose_name="Target Requirements",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence Collection Rule",
                "verbose_name_plural": "Evidence Collection Rules",
            },
        ),
        migrations.CreateModel(
            name="EvidenceCollectionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "items_collected",
                    models.IntegerField(default=0, verbose_name="Items Collected"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "run_log",
                    models.JSONField(blank=True, default=list, verbose_name="Run Log"),
                ),
                (
                    "evidence_created",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_runs",
                        to="core.evidence",
                        verbose_name="Evidence Created",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="evidence_automation.evidencecollectionrule",
                        verbose_name="Rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence Collection Run",
                "verbose_name_plural": "Evidence Collection Runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("aws", "Amazon Web Services"),
                            ("azure", "Microsoft Azure"),
                            ("gcp", "Google Cloud Platform"),
                            ("okta", "Okta Identity"),
                            ("azure_ad", "Azure Active Directory"),
                            ("github", "GitHub"),
                            ("jira", "Jira"),
                            ("servicenow", "ServiceNow"),
                            ("splunk", "Splunk"),
                            ("qualys", "Qualys"),
                            ("tenable", "Tenable"),
                            ("crowdstrike", "CrowdStrike"),
                            ("api", "Custom API"),
                            ("file", "File Upload"),
                            ("manual", "Manual Collection"),
                        ],
                        max_length=50,
                        verbose_name="Source Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("pending", "Pending Configuration"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Connection configuration (API keys, endpoints, etc.)",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "collection_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Collection Enabled"
                    ),
                ),
                (
                    "collection_schedule",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for collection schedule",
                        max_length=100,
                        null=True,
                        verbose_name="Collection Schedule",
                    ),
                ),
                (
                    "last_collection_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Collection"
                    ),
                ),
                (
                    "last_collection_status",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Last Collection Status",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, null=True, verbose_name="Last Error"),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence Source",
                "verbose_name_plural": "Evidence Sources",
            },
        ),
        migrations.AddField(
            model_name="evidencecollectionrule",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_rules",
                to="evidence_automation.evidencesource",
                verbose_name="Source",
            ),
        ),
    ]
