# Generated by Django 5.2.9 on 2026-01-23 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "incident_id",
                    models.CharField(
                        help_text="Unique incident identifier (e.g., INC-2024-001)",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Incident title/summary", max_length=500
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed incident description"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("malware", "Malware Infection"),
                            ("phishing", "Phishing/Social Engineering"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("data_breach", "Data Breach"),
                            ("denial_of_service", "Denial of Service"),
                            ("insider_threat", "Insider Threat"),
                            ("physical_security", "Physical Security"),
                            ("policy_violation", "Policy Violation"),
                            ("third_party_compromise", "Third Party Compromise"),
                            ("supply_chain_attack", "Supply Chain Attack"),
                            ("ransomware", "Ransomware"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Incident category",
                        max_length=30,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True,
                        help_text="More specific incident subcategory",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Incident severity level",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("p1", "P1 - Critical"),
                            ("p2", "P2 - High"),
                            ("p3", "P3 - Medium"),
                            ("p4", "P4 - Low"),
                        ],
                        default="p3",
                        help_text="Incident response priority",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("investigating", "Investigating"),
                            ("contained", "Contained"),
                            ("eradicating", "Eradicating"),
                            ("recovering", "Recovering"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("false_positive", "False Positive"),
                        ],
                        default="detected",
                        help_text="Current incident status",
                        max_length=15,
                    ),
                ),
                (
                    "detection_method",
                    models.CharField(
                        choices=[
                            ("automated_monitoring", "Automated Monitoring"),
                            ("manual_report", "Manual Report"),
                            ("security_tool", "Security Tool Alert"),
                            ("external_report", "External Report"),
                            ("audit_finding", "Audit Finding"),
                            ("customer_report", "Customer Report"),
                            ("other", "Other"),
                        ],
                        help_text="How the incident was detected",
                        max_length=50,
                    ),
                ),
                (
                    "detection_date",
                    models.DateTimeField(
                        help_text="When the incident was first detected"
                    ),
                ),
                (
                    "reported_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the incident was officially reported",
                        null=True,
                    ),
                ),
                (
                    "reported_by_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of person who reported the incident",
                        null=True,
                    ),
                ),
                (
                    "reported_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of person who reported the incident",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "investigation_start_date",
                    models.DateTimeField(
                        blank=True, help_text="When investigation began", null=True
                    ),
                ),
                (
                    "containment_date",
                    models.DateTimeField(
                        blank=True, help_text="When incident was contained", null=True
                    ),
                ),
                (
                    "eradication_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When eradication was completed",
                        null=True,
                    ),
                ),
                (
                    "recovery_date",
                    models.DateTimeField(
                        blank=True, help_text="When recovery was completed", null=True
                    ),
                ),
                (
                    "resolution_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When incident was fully resolved",
                        null=True,
                    ),
                ),
                (
                    "closure_date",
                    models.DateTimeField(
                        blank=True, help_text="When incident was closed", null=True
                    ),
                ),
                (
                    "assigned_analyst_user_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="User ID of assigned incident analyst",
                        null=True,
                    ),
                ),
                (
                    "assigned_analyst_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of assigned incident analyst",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "response_team",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Incident response team members and roles",
                    ),
                ),
                (
                    "affected_systems",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Systems affected by the incident",
                    ),
                ),
                (
                    "affected_assets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Assets affected by the incident",
                    ),
                ),
                (
                    "affected_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Data affected by the incident",
                    ),
                ),
                (
                    "business_impact",
                    models.CharField(
                        choices=[
                            ("none", "No Impact"),
                            ("minimal", "Minimal"),
                            ("moderate", "Moderate"),
                            ("significant", "Significant"),
                            ("severe", "Severe"),
                            ("critical", "Critical"),
                        ],
                        default="minimal",
                        help_text="Business impact level",
                        max_length=20,
                    ),
                ),
                (
                    "impact_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of business impact",
                        null=True,
                    ),
                ),
                (
                    "financial_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated financial impact",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "operational_impact",
                    models.TextField(
                        blank=True,
                        help_text="Operational impact description",
                        null=True,
                    ),
                ),
                (
                    "root_cause",
                    models.TextField(
                        blank=True, help_text="Root cause analysis", null=True
                    ),
                ),
                (
                    "contributing_factors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Contributing factors to the incident",
                    ),
                ),
                (
                    "containment_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Actions taken to contain the incident",
                    ),
                ),
                (
                    "containment_effectiveness",
                    models.CharField(
                        choices=[
                            ("fully_effective", "Fully Effective"),
                            ("partially_effective", "Partially Effective"),
                            ("ineffective", "Ineffective"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_applicable",
                        help_text="Effectiveness of containment actions",
                        max_length=20,
                    ),
                ),
                (
                    "eradication_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Actions taken to eradicate the threat",
                    ),
                ),
                (
                    "eradication_effectiveness",
                    models.CharField(
                        choices=[
                            ("fully_effective", "Fully Effective"),
                            ("partially_effective", "Partially Effective"),
                            ("ineffective", "Ineffective"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_applicable",
                        help_text="Effectiveness of eradication actions",
                        max_length=20,
                    ),
                ),
                (
                    "recovery_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Actions taken to recover from the incident",
                    ),
                ),
                (
                    "recovery_effectiveness",
                    models.CharField(
                        choices=[
                            ("fully_effective", "Fully Effective"),
                            ("partially_effective", "Partially Effective"),
                            ("ineffective", "Ineffective"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_applicable",
                        help_text="Effectiveness of recovery actions",
                        max_length=20,
                    ),
                ),
                (
                    "lessons_learned",
                    models.TextField(
                        blank=True,
                        help_text="Lessons learned from the incident",
                        null=True,
                    ),
                ),
                (
                    "preventive_measures",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Preventive measures recommended",
                    ),
                ),
                (
                    "process_improvements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Process improvements identified",
                    ),
                ),
                (
                    "stakeholders_notified",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Stakeholders who were notified",
                    ),
                ),
                (
                    "external_notifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="External parties notified (regulators, customers, etc.)",
                    ),
                ),
                (
                    "public_disclosure",
                    models.BooleanField(
                        default=False,
                        help_text="Whether incident was publicly disclosed",
                    ),
                ),
                (
                    "disclosure_details",
                    models.TextField(
                        blank=True, help_text="Details of public disclosure", null=True
                    ),
                ),
                (
                    "evidence_collected",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Evidence collected during investigation",
                    ),
                ),
                (
                    "investigation_notes",
                    models.TextField(
                        blank=True, help_text="Detailed investigation notes", null=True
                    ),
                ),
                (
                    "supporting_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Supporting documents and attachments",
                    ),
                ),
                (
                    "time_to_detection",
                    models.DurationField(
                        blank=True,
                        help_text="Time from incident occurrence to detection",
                        null=True,
                    ),
                ),
                (
                    "time_to_containment",
                    models.DurationField(
                        blank=True,
                        help_text="Time from detection to containment",
                        null=True,
                    ),
                ),
                (
                    "time_to_resolution",
                    models.DurationField(
                        blank=True,
                        help_text="Time from detection to resolution",
                        null=True,
                    ),
                ),
                (
                    "nist_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reconnaissance", "Reconnaissance"),
                            ("weaponization", "Weaponization"),
                            ("delivery", "Delivery"),
                            ("exploitation", "Exploitation"),
                            ("installation", "Installation"),
                            ("command_and_control", "Command and Control"),
                            ("actions_on_objectives", "Actions on Objectives"),
                        ],
                        help_text="NIST incident category",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "related_risks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related risks from Risk Registers",
                    ),
                ),
                (
                    "related_findings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Related compliance findings",
                    ),
                ),
                (
                    "related_assets",
                    models.JSONField(
                        blank=True, default=list, help_text="Related assets affected"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Incident tags for organization",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom fields for additional properties",
                    ),
                ),
                (
                    "response_effectiveness_score",
                    models.IntegerField(
                        default=0,
                        help_text="Overall response effectiveness score (0-100)",
                    ),
                ),
            ],
            options={
                "db_table": "security_incidents",
                "ordering": ["-detection_date"],
                "indexes": [
                    models.Index(fields=["status"], name="incident_status_idx"),
                    models.Index(fields=["severity"], name="incident_severity_idx"),
                    models.Index(fields=["category"], name="incident_category_idx"),
                    models.Index(fields=["priority"], name="incident_priority_idx"),
                    models.Index(
                        fields=["detection_date"], name="incident_detection_idx"
                    ),
                    models.Index(
                        fields=["assigned_analyst_user_id"], name="incident_analyst_idx"
                    ),
                    models.Index(
                        fields=["business_impact"], name="incident_impact_idx"
                    ),
                    models.Index(fields=["created_at"], name="incident_created_idx"),
                ],
            },
        ),
    ]
