# Generated by Django 5.2.12 on 2026-03-10 14:46

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("continuous_monitoring", "0001_initial"),
        ("core", "0135_add_assessment_engine_and_version_history_models"),
        ("evidence_automation", "0001_initial"),
        ("iam", "0018_cacheversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("fedramp", "FedRAMP Assessment"),
                            ("nist_800_53", "NIST 800-53"),
                            ("iso_27001", "ISO 27001"),
                            ("soc_2", "SOC 2"),
                            ("cmmc", "CMMC"),
                            ("custom", "Custom"),
                        ],
                        default="fedramp",
                        max_length=30,
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the system being assessed (e.g., MyApp on AWS/RHEL 7)",
                        max_length=255,
                        verbose_name="System Name",
                    ),
                ),
                (
                    "system_description",
                    models.TextField(blank=True, verbose_name="System Description"),
                ),
                (
                    "platform_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="e.g. ['AWS', 'RHEL7', 'ORACLE_DB', 'SPLUNK']",
                        verbose_name="Platform Tags",
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Statistics"
                    ),
                ),
                (
                    "collection_playbooks",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Collection Playbooks"
                    ),
                ),
                (
                    "quality_report",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Quality Report"
                    ),
                ),
                (
                    "indexes",
                    models.JSONField(blank=True, default=dict, verbose_name="Indexes"),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Source File"
                    ),
                ),
                (
                    "compliance_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_packages",
                        to="core.complianceassessment",
                        verbose_name="Compliance Assessment",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artifact Package",
                "verbose_name_plural": "Artifact Packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtifactRequestItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "request_id",
                    models.CharField(
                        help_text="e.g. REQ-0001",
                        max_length=20,
                        verbose_name="Request ID",
                    ),
                ),
                (
                    "source_line",
                    models.IntegerField(default=0, verbose_name="Source Line"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Category"
                    ),
                ),
                (
                    "artifact_request",
                    models.TextField(verbose_name="Artifact Request Text"),
                ),
                (
                    "request_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Request Date"
                    ),
                ),
                (
                    "controls",
                    models.JSONField(
                        default=list,
                        help_text="e.g. ['AC-2', 'AC-2(4)', 'AU-6']",
                        verbose_name="Controls",
                    ),
                ),
                (
                    "control_families",
                    models.JSONField(
                        default=list,
                        help_text="e.g. ['AC', 'AU']",
                        verbose_name="Control Families",
                    ),
                ),
                (
                    "control_domains",
                    models.JSONField(
                        default=list,
                        help_text="e.g. ['Access Control and Authorization']",
                        verbose_name="Control Domains",
                    ),
                ),
                (
                    "workstreams",
                    models.JSONField(default=list, verbose_name="Workstreams"),
                ),
                ("supplemental_references", models.JSONField(default=list)),
                (
                    "primary_artifact_type",
                    models.CharField(
                        choices=[
                            ("system_generated_output", "System-Generated Output"),
                            ("configuration_snapshot", "Configuration Snapshot"),
                            ("command_output", "Command Output"),
                            ("scan_evidence", "Scan Evidence"),
                            ("report", "Report"),
                            ("policy_document", "Policy Document"),
                            ("procedure_document", "Procedure Document"),
                            ("plan_document", "Plan Document"),
                            ("records", "Records"),
                            ("meeting_evidence", "Meeting Evidence"),
                            ("communication_evidence", "Communication Evidence"),
                            ("screenshot", "Screenshot"),
                            ("inventory_listing", "Inventory Listing"),
                            ("training_artifact", "Training Artifact"),
                            ("matrix_or_mapping", "Matrix/Mapping"),
                            ("alert_evidence", "Alert Evidence"),
                            ("ticketing_evidence", "Ticketing Evidence"),
                            ("generic_evidence", "Generic Evidence"),
                        ],
                        default="generic_evidence",
                        max_length=50,
                    ),
                ),
                (
                    "artifact_types",
                    models.JSONField(default=list, verbose_name="All Artifact Types"),
                ),
                (
                    "collection_channel",
                    models.CharField(
                        choices=[
                            ("tool_export", "Tool Export"),
                            ("cli_capture", "CLI Capture"),
                            ("scanner_export", "Scanner Export"),
                            ("report_export", "Report Export"),
                            ("document_repository", "Document Repository"),
                            ("system_of_record_export", "System of Record Export"),
                            ("governance_records", "Governance Records"),
                            ("mail_ticket_export", "Mail/Ticket Export"),
                            ("screenshot_capture", "Screenshot Capture"),
                            ("manual_collection", "Manual Collection"),
                        ],
                        default="manual_collection",
                        max_length=50,
                    ),
                ),
                (
                    "platform_tags",
                    models.JSONField(default=list, verbose_name="Platform Tags"),
                ),
                (
                    "time_scopes",
                    models.JSONField(default=list, verbose_name="Time Scopes"),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("on_demand", "On Demand"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                            ("event_driven", "Event-Driven"),
                            ("continuous", "Continuous"),
                        ],
                        default="on_demand",
                        max_length=20,
                        verbose_name="Periodicity",
                    ),
                ),
                (
                    "commands",
                    models.JSONField(
                        default=list,
                        help_text="Extracted CLI commands for evidence collection",
                        verbose_name="Commands",
                    ),
                ),
                (
                    "config_paths",
                    models.JSONField(
                        default=list,
                        help_text="Extracted config file paths",
                        verbose_name="Config Paths",
                    ),
                ),
                (
                    "bundle_hint",
                    models.JSONField(
                        default=dict,
                        help_text="Suggested file path and extension",
                        verbose_name="Bundle Hint",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_request_items",
                        to="core.evidence",
                        verbose_name="Collected Evidence",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_items",
                        to="assessment_artifacts.artifactpackage",
                        verbose_name="Artifact Package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artifact Request Item",
                "verbose_name_plural": "Artifact Request Items",
                "ordering": ["request_id"],
                "unique_together": {("package", "request_id")},
            },
        ),
        migrations.CreateModel(
            name="EvidenceSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Schedule Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '0 9 * * 1' for weekly Monday at 9 AM",
                        max_length=100,
                        verbose_name="Cron Expression",
                    ),
                ),
                (
                    "control_families",
                    models.JSONField(default=list, verbose_name="Control Families"),
                ),
                ("controls", models.JSONField(default=list, verbose_name="Controls")),
                (
                    "evidence_types",
                    models.JSONField(
                        default=list,
                        help_text="Types of evidence to collect on this schedule",
                        verbose_name="Evidence Types",
                    ),
                ),
                (
                    "platform_tags",
                    models.JSONField(default=list, verbose_name="Platform Tags"),
                ),
                (
                    "collection_actions",
                    models.JSONField(
                        default=list,
                        help_text="Summary of what to collect on each occurrence",
                        verbose_name="Collection Actions",
                    ),
                ),
                (
                    "last_collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Collected"
                    ),
                ),
                (
                    "next_due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Due"
                    ),
                ),
                (
                    "items_count",
                    models.IntegerField(default=0, verbose_name="Items Count"),
                ),
                (
                    "conmon_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_schedules",
                        to="continuous_monitoring.conmonactivityconfig",
                        verbose_name="ConMon Activity",
                    ),
                ),
                (
                    "evidence_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_schedules",
                        to="evidence_automation.evidencecollectionrule",
                        verbose_name="Evidence Collection Rule",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_schedules",
                        to="assessment_artifacts.artifactpackage",
                        verbose_name="Artifact Package",
                    ),
                ),
                (
                    "request_items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="schedules",
                        to="assessment_artifacts.artifactrequestitem",
                        verbose_name="Request Items",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence Schedule",
                "verbose_name_plural": "Evidence Schedules",
                "ordering": ["frequency", "name"],
            },
        ),
    ]
