# Generated by Django 5.2.9 on 2026-01-23 02:17

import core.domain.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("primary", "Primary"), ("support", "Support")],
                        db_index=True,
                        default="support",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_use", "In Use"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "assetClassificationId",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "assetLabelIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of asset label IDs"
                    ),
                ),
                (
                    "businessOwnerOrgUnitIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True,
                        help_text="Array of business owner organizational unit IDs",
                    ),
                ),
                (
                    "systemOwnerUserIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of system owner user IDs"
                    ),
                ),
                (
                    "processIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of process IDs"
                    ),
                ),
                (
                    "dataAssetIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of data asset IDs"
                    ),
                ),
                (
                    "serviceIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of service IDs"
                    ),
                ),
                (
                    "thirdPartyIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of third party IDs"
                    ),
                ),
                (
                    "controlIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of control IDs"
                    ),
                ),
                (
                    "riskIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of risk IDs"
                    ),
                ),
                (
                    "business_value",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "asset_service_assets",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state", "asset_type"],
                        name="asset_servi_lifecyc_de8fa5_idx",
                    ),
                    models.Index(fields=["name"], name="asset_servi_name_245dbb_idx"),
                    models.Index(
                        fields=["ref_id"], name="asset_servi_ref_id_f1059b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetOverview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("asset_id", models.UUIDField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("ref_id", models.CharField(blank=True, max_length=100, null=True)),
                ("asset_type", models.CharField(db_index=True, max_length=20)),
                ("lifecycle_state", models.CharField(db_index=True, max_length=20)),
                ("control_count", models.IntegerField(default=0)),
                (
                    "control_implementation_status_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of control implementation statuses",
                    ),
                ),
                ("risk_count", models.IntegerField(default=0)),
                (
                    "risk_residual_score_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of risk residual scores",
                    ),
                ),
                ("third_party_count", models.IntegerField(default=0)),
                (
                    "third_party_contract_status_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of third party contract statuses",
                    ),
                ),
                (
                    "third_party_assessment_status_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of third party assessment statuses",
                    ),
                ),
                ("service_count", models.IntegerField(default=0)),
                (
                    "service_status_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of service statuses",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asset Overview",
                "verbose_name_plural": "Asset Overviews",
                "db_table": "asset_service_asset_overviews",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="asset_servi_lifecyc_4a8e8b_idx",
                    ),
                    models.Index(
                        fields=["asset_type"], name="asset_servi_asset_t_6169d8_idx"
                    ),
                    models.Index(fields=["name"], name="asset_servi_name_2402c3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "orgUnitIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of organizational unit IDs"
                    ),
                ),
                (
                    "assetIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of asset IDs"
                    ),
                ),
                (
                    "controlIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of control IDs"
                    ),
                ),
                (
                    "riskIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of risk IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Process",
                "verbose_name_plural": "Processes",
                "db_table": "asset_service_processes",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="asset_servi_lifecyc_d86cf4_idx",
                    ),
                    models.Index(fields=["name"], name="asset_servi_name_3477d6_idx"),
                    models.Index(
                        fields=["ref_id"], name="asset_servi_ref_id_0065c1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "serviceClassificationId",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("operational", "Operational"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "assetIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of asset IDs"
                    ),
                ),
                (
                    "thirdPartyIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of third party IDs"
                    ),
                ),
                (
                    "controlIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of control IDs"
                    ),
                ),
                (
                    "riskIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of risk IDs"
                    ),
                ),
                (
                    "contractIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of service contract IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "asset_service_services",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="asset_servi_lifecyc_6fb7ce_idx",
                    ),
                    models.Index(fields=["name"], name="asset_servi_name_d18808_idx"),
                    models.Index(
                        fields=["ref_id"], name="asset_servi_ref_id_983725_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("serviceId", models.UUIDField(db_index=True)),
                ("thirdPartyId", models.UUIDField(db_index=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "renewal_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("key_terms", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service Contract",
                "verbose_name_plural": "Service Contracts",
                "db_table": "asset_service_contracts",
                "indexes": [
                    models.Index(
                        fields=["serviceId", "thirdPartyId"],
                        name="asset_servi_service_61cb03_idx",
                    ),
                    models.Index(
                        fields=["lifecycle_state", "end_date"],
                        name="asset_servi_lifecyc_a323b3_idx",
                    ),
                ],
                "unique_together": {("serviceId", "thirdPartyId", "start_date")},
            },
        ),
    ]
