# Generated by Django 5.2.9 on 2026-01-23 02:17

import core.domain.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0130_remove_organisationobjective_new_assigned_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "assessmentId",
                    models.UUIDField(db_index=True, help_text="ID of the assessment"),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("third_party", "Third Party"),
                            ("org_unit", "Organizational Unit"),
                            ("service", "Service"),
                            ("asset", "Asset"),
                            ("process", "Process"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("target_id", models.UUIDField(db_index=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="invited",
                        max_length=20,
                    ),
                ),
                (
                    "invitedUserIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of invited user IDs"
                    ),
                ),
                (
                    "respondentUserIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of respondent user IDs"
                    ),
                ),
                (
                    "findingIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of finding IDs"
                    ),
                ),
                (
                    "evidenceIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of evidence IDs"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True, help_text="Assessment score", null=True
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of answers: [{questionId, value, notes}]",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Assessment Run",
                "verbose_name_plural": "Assessment Runs",
                "db_table": "compliance_assessment_runs",
                "indexes": [
                    models.Index(
                        fields=["assessmentId", "target_type", "target_id"],
                        name="compliance__assessm_fbf349_idx",
                    ),
                    models.Index(
                        fields=["lifecycle_state"],
                        name="compliance__lifecyc_6ba57a_idx",
                    ),
                    models.Index(
                        fields=["submitted_at"], name="compliance__submitt_c6cb3c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AwarenessCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "programId",
                    models.UUIDField(
                        db_index=True, help_text="ID of the awareness program"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "targetUserIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of target user IDs"
                    ),
                ),
                (
                    "completionIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of completion IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Awareness Campaign",
                "verbose_name_plural": "Awareness Campaigns",
                "db_table": "security_operations_awareness_campaigns",
                "indexes": [
                    models.Index(
                        fields=["programId", "lifecycle_state"],
                        name="security_op_program_c78231_idx",
                    ),
                    models.Index(
                        fields=["start_date"], name="security_op_start_d_8b8bdd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AwarenessCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "campaignId",
                    models.UUIDField(
                        db_index=True, help_text="ID of the awareness campaign"
                    ),
                ),
                ("userId", models.UUIDField(db_index=True, help_text="ID of the user")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Completion score if applicable",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Awareness Completion",
                "verbose_name_plural": "Awareness Completions",
                "db_table": "security_operations_awareness_completions",
                "indexes": [
                    models.Index(
                        fields=["campaignId", "userId"],
                        name="security_op_campaig_473c99_idx",
                    ),
                    models.Index(
                        fields=["status"], name="security_op_status_b12cb5_idx"
                    ),
                    models.Index(
                        fields=["completed_at"], name="security_op_complet_2ec3a4_idx"
                    ),
                ],
                "unique_together": {("campaignId", "userId")},
            },
        ),
        migrations.CreateModel(
            name="AwarenessProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "audienceOrgUnitIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True,
                        help_text="Array of audience organizational unit IDs",
                    ),
                ),
                (
                    "policyIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of related policy IDs"
                    ),
                ),
                (
                    "campaignIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of campaign IDs"
                    ),
                ),
                (
                    "cadence_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Cadence in days (e.g., 30 for monthly)",
                        null=True,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Awareness Program",
                "verbose_name_plural": "Awareness Programs",
                "db_table": "security_operations_awareness_programs",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="security_op_lifecyc_049821_idx",
                    ),
                    models.Index(fields=["name"], name="security_op_name_2f37a1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BcpAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bcpId",
                    models.UUIDField(
                        db_index=True, help_text="ID of the business continuity plan"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("running", "Running"),
                            ("reported", "Reported"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("partial", "Partial"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "evidenceIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of evidence IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "BCP Audit",
                "verbose_name_plural": "BCP Audits",
                "db_table": "business_continuity_bcp_audits",
                "indexes": [
                    models.Index(
                        fields=["bcpId", "lifecycle_state"],
                        name="business_co_bcpId_d830e0_idx",
                    ),
                    models.Index(
                        fields=["performed_at"], name="business_co_perform_ca8615_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BcpTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bcpId",
                    models.UUIDField(
                        db_index=True, help_text="ID of the business continuity plan"
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "owner_user_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "evidenceIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of evidence IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "BCP Task",
                "verbose_name_plural": "BCP Tasks",
                "db_table": "business_continuity_bcp_tasks",
                "indexes": [
                    models.Index(
                        fields=["bcpId", "lifecycle_state"],
                        name="business_co_bcpId_2afe67_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="business_co_due_dat_f468d2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BusinessContinuityPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("exercised", "Exercised"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "orgUnitIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of organizational unit IDs"
                    ),
                ),
                (
                    "processIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of process IDs"
                    ),
                ),
                (
                    "assetIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of asset IDs"
                    ),
                ),
                (
                    "serviceIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of service IDs"
                    ),
                ),
                (
                    "taskIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of BCP task IDs"
                    ),
                ),
                (
                    "auditIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of BCP audit IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Business Continuity Plan",
                "verbose_name_plural": "Business Continuity Plans",
                "db_table": "business_continuity_business_continuity_plans",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="business_co_lifecyc_e6bd25_idx",
                    ),
                    models.Index(fields=["name"], name="business_co_name_4ab000_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("running", "Running"),
                            ("reported", "Reported"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "scopeFrameworkIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of framework IDs in scope"
                    ),
                ),
                (
                    "scopeRequirementIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of requirement IDs in scope"
                    ),
                ),
                (
                    "auditor_org",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "findingIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of finding IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Compliance Audit",
                "verbose_name_plural": "Compliance Audits",
                "db_table": "compliance_compliance_audits",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="compliance__lifecyc_f5c520_idx",
                    ),
                    models.Index(
                        fields=["start_date"], name="compliance__start_d_7725b7_idx"
                    ),
                    models.Index(
                        fields=["auditor_org"], name="compliance__auditor_f52efe_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "requirementId",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID of the requirement this exception applies to",
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for the exception")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by_user_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Compliance Exception",
                "verbose_name_plural": "Compliance Exceptions",
                "db_table": "compliance_compliance_exceptions",
                "indexes": [
                    models.Index(
                        fields=["requirementId", "lifecycle_state"],
                        name="compliance__require_8c050a_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="compliance__expires_4bafb9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("audit", "Audit"),
                            ("assessment", "Assessment"),
                            ("internal_review", "Internal Review"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID of the source (audit, assessment, etc.)",
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("triaged", "Triaged"),
                            ("remediating", "Remediating"),
                            ("verified", "Verified"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "requirementIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of requirement IDs"
                    ),
                ),
                (
                    "controlImplementationIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of control implementation IDs"
                    ),
                ),
                (
                    "remediationTaskIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of remediation task IDs"
                    ),
                ),
                (
                    "evidenceIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of evidence IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Compliance Finding",
                "verbose_name_plural": "Compliance Findings",
                "db_table": "compliance_compliance_findings",
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="compliance__source__77d671_idx",
                    ),
                    models.Index(
                        fields=["lifecycle_state", "severity"],
                        name="compliance__lifecyc_64f2f7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceFramework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "framework_version",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "requirementIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of requirement IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Compliance Framework",
                "verbose_name_plural": "Compliance Frameworks",
                "db_table": "compliance_compliance_frameworks",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="compliance__lifecyc_f72959_idx",
                    ),
                    models.Index(
                        fields=["name", "version"], name="compliance__name_8c723d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "data_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of data category strings",
                    ),
                ),
                (
                    "contains_personal_data",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this asset contains personal data",
                    ),
                ),
                (
                    "retention_policy",
                    models.TextField(
                        blank=True, help_text="Retention policy description", null=True
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "assetIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of asset IDs that store this data"
                    ),
                ),
                (
                    "ownerOrgUnitIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of owner organizational unit IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Data Asset",
                "verbose_name_plural": "Data Assets",
                "db_table": "privacy_data_assets",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="privacy_dat_lifecyc_c7b5ac_idx",
                    ),
                    models.Index(
                        fields=["contains_personal_data"],
                        name="privacy_dat_contain_5a48bb_idx",
                    ),
                    models.Index(fields=["name"], name="privacy_dat_name_3447c5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "purpose",
                    models.TextField(
                        blank=True, help_text="Purpose of the data flow", null=True
                    ),
                ),
                (
                    "source_system_asset_id",
                    models.UUIDField(
                        db_index=True, help_text="ID of the source system asset"
                    ),
                ),
                (
                    "destination_system_asset_id",
                    models.UUIDField(
                        db_index=True, help_text="ID of the destination system asset"
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "dataAssetIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True,
                        help_text="Array of data asset IDs flowing through this flow",
                    ),
                ),
                (
                    "thirdPartyIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True,
                        help_text="Array of third party IDs involved in this flow",
                    ),
                ),
                (
                    "controlImplementationIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of control implementation IDs"
                    ),
                ),
                (
                    "privacyRiskIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of privacy risk IDs"
                    ),
                ),
                (
                    "transfer_mechanisms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of transfer mechanism strings (e.g., API, SFTP, Email)",
                    ),
                ),
                (
                    "encryption_in_transit",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        help_text="Whether data is encrypted in transit",
                        null=True,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Data Flow",
                "verbose_name_plural": "Data Flows",
                "db_table": "privacy_data_flows",
                "indexes": [
                    models.Index(
                        fields=[
                            "source_system_asset_id",
                            "destination_system_asset_id",
                        ],
                        name="privacy_dat_source__b0cc98_idx",
                    ),
                    models.Index(
                        fields=["lifecycle_state"],
                        name="privacy_dat_lifecyc_ccd5d3_idx",
                    ),
                    models.Index(fields=["name"], name="privacy_dat_name_93ce73_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OnlineAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "questionnaireId",
                    models.UUIDField(
                        db_index=True, help_text="ID of the questionnaire"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("third_party", "Third Party"),
                            ("org_unit", "Organizational Unit"),
                            ("service", "Service"),
                            ("asset", "Asset"),
                            ("process", "Process"),
                        ],
                        db_index=True,
                        help_text="Type of entity this assessment targets",
                        max_length=50,
                    ),
                ),
                (
                    "scoring_model",
                    models.CharField(
                        blank=True,
                        help_text="Scoring model for the assessment",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Online Assessment",
                "verbose_name_plural": "Online Assessments",
                "db_table": "compliance_online_assessments",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state"],
                        name="compliance__lifecyc_3dff77_idx",
                    ),
                    models.Index(
                        fields=["questionnaireId"],
                        name="compliance__questio_b556a1_idx",
                    ),
                    models.Index(
                        fields=["target_type"], name="compliance__target__fa4c4f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                (
                    "frameworkId",
                    models.UUIDField(
                        db_index=True, help_text="ID of the compliance framework"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Requirement code (e.g., AC-1)",
                        max_length=100,
                    ),
                ),
                ("statement", models.TextField(help_text="Requirement statement")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "mappedControlIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of mapped control IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Requirement",
                "verbose_name_plural": "Requirements",
                "db_table": "compliance_requirements",
                "indexes": [
                    models.Index(
                        fields=["frameworkId", "code"],
                        name="compliance__framewo_ac6150_idx",
                    ),
                    models.Index(
                        fields=["lifecycle_state"],
                        name="compliance__lifecyc_066547_idx",
                    ),
                ],
                "unique_together": {("frameworkId", "code")},
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "classification_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the incident classification",
                        null=True,
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("triaged", "Triaged"),
                            ("contained", "Contained"),
                            ("eradicated", "Eradicated"),
                            ("recovered", "Recovered"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="reported",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "detection_source",
                    models.CharField(
                        choices=[("internal", "Internal"), ("external", "External")],
                        db_index=True,
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "affectedAssetIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of affected asset IDs"
                    ),
                ),
                (
                    "affectedServiceIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of affected service IDs"
                    ),
                ),
                (
                    "relatedRiskIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of related risk IDs"
                    ),
                ),
                (
                    "evidenceIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of evidence IDs"
                    ),
                ),
                (
                    "timeline",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of timeline events: [{at, action, actorUserId, notes}]",
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("triaged_at", models.DateTimeField(blank=True, null=True)),
                ("contained_at", models.DateTimeField(blank=True, null=True)),
                ("eradicated_at", models.DateTimeField(blank=True, null=True)),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Security Incident",
                "verbose_name_plural": "Security Incidents",
                "db_table": "security_operations_security_incidents",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state", "severity"],
                        name="security_op_lifecyc_df1850_idx",
                    ),
                    models.Index(
                        fields=["reported_at"], name="security_op_reporte_6c479c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ThirdParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=0, help_text="Optimistic locking version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True, help_text="User who created this record", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("active", "Active"),
                            ("offboarding", "Offboarding"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="prospect",
                        max_length=20,
                    ),
                ),
                (
                    "serviceIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True,
                        help_text="Array of service IDs provided by this third party",
                    ),
                ),
                (
                    "contractIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of contract IDs"
                    ),
                ),
                (
                    "assessmentRunIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of assessment run IDs"
                    ),
                ),
                (
                    "riskIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of risk IDs"
                    ),
                ),
                (
                    "controlImplementationIds",
                    core.domain.fields.EmbeddedIdArrayField(
                        blank=True, help_text="Array of control implementation IDs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Third Party",
                "verbose_name_plural": "Third Parties",
                "db_table": "third_party_management_third_parties",
                "indexes": [
                    models.Index(
                        fields=["lifecycle_state", "criticality"],
                        name="third_party_lifecyc_c7cf3b_idx",
                    ),
                    models.Index(fields=["name"], name="third_party_name_a252d0_idx"),
                ],
            },
        ),
    ]
