# Generated by Django 5.2.9 on 2026-01-23 02:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0131_assessmentrun_awarenesscampaign_awarenesscompletion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("event_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "aggregate_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("aggregate_version", models.IntegerField(default=0)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=255)),
                ("payload", models.JSONField()),
            ],
            options={
                "db_table": "domain_events",
                "ordering": ["occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["aggregate_id", "aggregate_version"],
                        name="domain_even_aggrega_98ce93_idx",
                    ),
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="domain_even_event_t_ddcc13_idx",
                    ),
                ],
            },
        ),
    ]
