# Generated by Django 5.2.9 on 2026-01-24 03:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0132_eventstore"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dataasset",
            name="estimated_data_subjects",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Estimated number of data subjects affected by this data asset",
            ),
        ),
        migrations.AddField(
            model_name="dataasset",
            name="pia_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Privacy Impact Assessment was completed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dataasset",
            name="pia_ref_id",
            field=models.CharField(
                blank=True,
                help_text="Reference ID of the completed PIA document",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdparty",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("vendor", "Vendor"),
                    ("partner", "Partner"),
                    ("supplier", "Supplier"),
                    ("contractor", "Contractor"),
                    ("service_provider", "Service Provider"),
                    ("consultant", "Consultant"),
                ],
                db_index=True,
                default="vendor",
                help_text="Type of third party entity",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("trigger", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=list)),
                ("canvas_settings", models.JSONField(default=dict)),
                ("tags", models.JSONField(default=list)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_executions", models.PositiveIntegerField(default=0)),
                ("successful_executions", models.PositiveIntegerField(default=0)),
                ("failed_executions", models.PositiveIntegerField(default=0)),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflows_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflows_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="core.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("execution_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("triggered_by", models.CharField(max_length=50)),
                ("trigger_data", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("context", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                ("output", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("cron", "Cron Expression"),
                            ("interval", "Interval"),
                            ("once", "Run Once"),
                        ],
                        default="cron",
                        max_length=20,
                    ),
                ),
                ("cron_expression", models.CharField(blank=True, max_length=100)),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("run_at", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.PositiveIntegerField(default=0)),
                ("max_runs", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="core.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["next_run_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_id", models.CharField(max_length=100)),
                ("node_type", models.CharField(max_length=50)),
                ("node_name", models.CharField(max_length=200)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.workflowexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("allowed_methods", models.JSONField(default=list)),
                ("rate_limit_per_minute", models.PositiveIntegerField(default=60)),
                ("total_calls", models.PositiveIntegerField(default=0)),
                ("last_called_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="core.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("connection_id", models.CharField(max_length=100)),
                ("source_node_id", models.CharField(max_length=100)),
                ("source_port", models.CharField(max_length=50)),
                ("target_node_id", models.CharField(max_length=100)),
                ("target_port", models.CharField(max_length=50)),
                ("condition", models.TextField(blank=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="core.workflow",
                    ),
                ),
            ],
            options={
                "unique_together": {("workflow", "connection_id")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_id", models.CharField(max_length=100)),
                ("node_type", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("config", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True)),
                ("is_disabled", models.BooleanField(default=False)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="core.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["node_id"],
                "unique_together": {("workflow", "node_id")},
            },
        ),
    ]
