# Generated by Django 5.2.9 on 2026-02-07 14:45

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0133_dataasset_estimated_data_subjects_and_more"),
        ("iam", "0018_cacheversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("user_access", "User access"),
                            ("service_account", "Service account"),
                            ("privileged", "Privileged access"),
                            ("vendor", "Vendor access"),
                        ],
                        default="user_access",
                        max_length=30,
                        verbose_name="Review type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completed date"
                    ),
                ),
                (
                    "findings_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of accounts needing action",
                        verbose_name="Findings count",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("--", "Undefined"),
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-compliant"),
                            ("partial", "Partial"),
                        ],
                        default="--",
                        max_length=20,
                        verbose_name="Result",
                    ),
                ),
                (
                    "applied_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="access_reviews",
                        to="core.appliedcontrol",
                        verbose_name="Applied controls",
                    ),
                ),
                (
                    "evidences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="access_reviews",
                        to="core.evidence",
                        verbose_name="Evidences",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
                (
                    "scope_assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="access_reviews",
                        to="core.asset",
                        verbose_name="Assets in scope",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access review",
                "verbose_name_plural": "Access reviews",
            },
        ),
        migrations.CreateModel(
            name="CryptoAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "crypto_type",
                    models.CharField(
                        choices=[
                            ("tls_certificate", "TLS certificate"),
                            ("ssh_key", "SSH key"),
                            ("api_key", "API key"),
                            ("signing_key", "Signing key"),
                            ("encryption_key", "Encryption key"),
                            ("secret", "Secret"),
                            ("other", "Other"),
                        ],
                        default="tls_certificate",
                        max_length=30,
                        verbose_name="Crypto type",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        blank=True,
                        help_text="e.g. RSA-2048, AES-256, Ed25519",
                        max_length=100,
                        verbose_name="Algorithm",
                    ),
                ),
                (
                    "key_size",
                    models.IntegerField(blank=True, null=True, verbose_name="Key size"),
                ),
                (
                    "issuer",
                    models.CharField(blank=True, max_length=200, verbose_name="Issuer"),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subject"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Serial number"
                    ),
                ),
                (
                    "not_before",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Not before"
                    ),
                ),
                (
                    "not_after",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiration date"
                    ),
                ),
                (
                    "rotation_policy_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Expected rotation interval in days",
                        null=True,
                        verbose_name="Rotation policy (days)",
                    ),
                ),
                (
                    "last_rotated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last rotated"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expiring_soon", "Expiring soon"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "applied_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="crypto_assets",
                        to="core.appliedcontrol",
                        verbose_name="Applied controls",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="crypto_assets",
                        to="core.asset",
                        verbose_name="Assets",
                    ),
                ),
                (
                    "evidences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="crypto_assets",
                        to="core.evidence",
                        verbose_name="Evidences",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crypto_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crypto asset",
                "verbose_name_plural": "Crypto assets",
            },
        ),
        migrations.CreateModel(
            name="DetectionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("siem_rule", "SIEM rule"),
                            ("ids_signature", "IDS signature"),
                            ("edr_policy", "EDR policy"),
                            ("waf_rule", "WAF rule"),
                            ("custom_alert", "Custom alert"),
                            ("log_monitor", "Log monitor"),
                            ("other", "Other"),
                        ],
                        default="siem_rule",
                        max_length=30,
                        verbose_name="Rule type",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        help_text="e.g. CloudTrail, Syslog, Windows Event Log",
                        max_length=200,
                        verbose_name="Data source",
                    ),
                ),
                (
                    "detection_target",
                    models.CharField(
                        blank=True,
                        help_text="What this rule detects",
                        max_length=200,
                        verbose_name="Detection target",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("degraded", "Degraded"),
                            ("disabled", "Disabled"),
                            ("untested", "Untested"),
                        ],
                        default="untested",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_validated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last validated"
                    ),
                ),
                (
                    "last_triggered",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this rule fired (proves it works)",
                        null=True,
                        verbose_name="Last triggered",
                    ),
                ),
                (
                    "false_positive_rate",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="False positive rate",
                    ),
                ),
                (
                    "coverage_gaps",
                    models.TextField(
                        blank=True,
                        help_text="Known blind spots",
                        verbose_name="Coverage gaps",
                    ),
                ),
                (
                    "applied_controls",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Controls this detection supports",
                        related_name="detection_rules",
                        to="core.appliedcontrol",
                        verbose_name="Applied controls",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="detection_rules",
                        to="core.asset",
                        verbose_name="Assets",
                    ),
                ),
                (
                    "evidences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="detection_rules",
                        to="core.evidence",
                        verbose_name="Evidences",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection rule",
                "verbose_name_plural": "Detection rules",
            },
        ),
    ]
