# Generated by Django 5.2.9 on 2026-02-24 01:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0134_add_signal_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("lightning", "Lightning Assessment"),
                            ("master", "Master Assessment"),
                            ("compliance", "Compliance Check"),
                            ("gap", "Gap Analysis"),
                            ("readiness", "Readiness Assessment"),
                        ],
                        default="lightning",
                        max_length=50,
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                ("default_test_cases", models.JSONField(default=list)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-times_used", "name"],
            },
        ),
        migrations.CreateModel(
            name="LightningAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scope", models.JSONField(default=dict)),
                (
                    "scoring_method",
                    models.CharField(
                        choices=[
                            ("pass_fail", "Pass/Fail"),
                            ("percentage", "Percentage"),
                            ("weighted", "Weighted Score"),
                            ("maturity", "Maturity Level"),
                        ],
                        default="pass_fail",
                        max_length=20,
                    ),
                ),
                ("total_controls", models.PositiveIntegerField(default=0)),
                ("tested_controls", models.PositiveIntegerField(default=0)),
                ("passed_controls", models.PositiveIntegerField(default=0)),
                ("failed_controls", models.PositiveIntegerField(default=0)),
                ("not_applicable", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("target_completion", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("results_summary", models.JSONField(default=dict)),
                (
                    "assessors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="lightning_assessments_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lightning_assessments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lightning_assessments",
                        to="core.assessmenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MasterAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("framework_ids", models.JSONField(default=list)),
                ("perimeter_ids", models.JSONField(default=list)),
                (
                    "grouping_method",
                    models.CharField(
                        choices=[
                            ("family", "Control Family"),
                            ("category", "Category"),
                            ("domain", "Security Domain"),
                            ("custom", "Custom Groups"),
                            ("mapping", "Cross-Framework Mapping"),
                        ],
                        default="family",
                        max_length=30,
                    ),
                ),
                ("control_groups", models.JSONField(default=list)),
                ("total_groups", models.PositiveIntegerField(default=0)),
                ("completed_groups", models.PositiveIntegerField(default=0)),
                ("total_controls", models.PositiveIntegerField(default=0)),
                ("tested_controls", models.PositiveIntegerField(default=0)),
                ("enable_inheritance", models.BooleanField(default=True)),
                ("inheritance_rules", models.JSONField(default=dict)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_end", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("results", models.JSONField(default=dict)),
                (
                    "assessors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="master_assessments_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="master_assessments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead_assessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="master_assessments_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="master_assessments_reviewing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LightningAssessmentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("run_number", models.PositiveIntegerField(default=1)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Assessment"),
                            ("retest", "Retest"),
                            ("followup", "Follow-up"),
                            ("validation", "Validation"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("results_snapshot", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lightning_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="core.lightningassessment",
                    ),
                ),
                (
                    "master_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="core.masterassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ControlGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("group_type", models.CharField(blank=True, max_length=50)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("control_references", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_controls", models.PositiveIntegerField(default=0)),
                ("tested_controls", models.PositiveIntegerField(default=0)),
                ("passed_controls", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_control_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "master_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="core.masterassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("control_id", models.CharField(max_length=255)),
                ("control_name", models.CharField(max_length=500)),
                ("test_procedure", models.TextField()),
                ("expected_result", models.TextField(blank=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Test"),
                            ("automated", "Automated Test"),
                            ("interview", "Interview"),
                            ("observation", "Observation"),
                            ("document_review", "Document Review"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "control_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="core.controlgroup",
                    ),
                ),
                (
                    "lightning_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="core.lightningassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "priority"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("partial", "Partial"),
                            ("na", "Not Applicable"),
                            ("not_tested", "Not Tested"),
                        ],
                        default="not_tested",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("actual_result", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("evidence_ids", models.JSONField(default=list)),
                ("findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("tested_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_results_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.testcase",
                    ),
                ),
                (
                    "tested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-tested_at"],
            },
        ),
        migrations.CreateModel(
            name="VersionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("version_label", models.CharField(blank=True, max_length=100)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("restore", "Restored"),
                            ("import", "Imported"),
                            ("bulk", "Bulk Update"),
                        ],
                        default="update",
                        max_length=20,
                    ),
                ),
                ("change_summary", models.CharField(blank=True, max_length=500)),
                ("change_reason", models.TextField(blank=True)),
                ("snapshot_data", models.JSONField()),
                ("changed_fields", models.JSONField(default=list)),
                ("previous_values", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(default=list)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_histories",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Version History",
                "verbose_name_plural": "Version Histories",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="VersionDiff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diff_data", models.JSONField()),
                ("fields_added", models.PositiveIntegerField(default=0)),
                ("fields_removed", models.PositiveIntegerField(default=0)),
                ("fields_changed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs_from",
                        to="core.versionhistory",
                    ),
                ),
                (
                    "to_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs_to",
                        to="core.versionhistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version Diff",
                "verbose_name_plural": "Version Diffs",
            },
        ),
        migrations.CreateModel(
            name="VersionComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("question", "Question"),
                            ("approval", "Approval"),
                            ("rejection", "Rejection"),
                            ("review", "Review"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.versionhistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version Comment",
                "verbose_name_plural": "Version Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VersionSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Snapshot"),
                            ("milestone", "Milestone"),
                            ("release", "Release"),
                            ("audit", "Audit Point"),
                            ("backup", "Backup"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("external_reference", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_protected", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="core.versionhistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version Snapshot",
                "verbose_name_plural": "Version Snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="versionhistory",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_versio_content_a58c05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="versionhistory",
            index=models.Index(
                fields=["content_type", "object_id", "version_number"],
                name="core_versio_content_eeda1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="versionhistory",
            index=models.Index(
                fields=["created_at"], name="core_versio_created_79e543_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="versionhistory",
            index=models.Index(
                fields=["created_by"], name="core_versio_created_521f5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="versionhistory",
            index=models.Index(
                fields=["change_type"], name="core_versio_change__2dcf08_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="versionhistory",
            unique_together={("content_type", "object_id", "version_number")},
        ),
        migrations.AlterUniqueTogether(
            name="versiondiff",
            unique_together={("from_version", "to_version")},
        ),
    ]
