# Generated by Django 5.2.12 on 2026-03-10 20:47

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_artifacts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0135_add_assessment_engine_and_version_history_models"),
        ("iam", "0018_cacheversion"),
        ("tprm", "0011_remove_contract_new_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("in_execution", "In Execution"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Assessment"),
                            ("annual", "Annual Assessment"),
                            ("significant_change", "Significant Change"),
                            ("ad_hoc", "Ad Hoc / Targeted"),
                        ],
                        default="annual",
                        max_length=30,
                    ),
                ),
                ("scope_description", models.TextField(blank=True)),
                (
                    "in_scope_controls",
                    models.JSONField(
                        blank=True, default=list, help_text="Control IDs in scope"
                    ),
                ),
                (
                    "excluded_controls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Control IDs excluded with rationale",
                    ),
                ),
                (
                    "system_boundary",
                    models.TextField(
                        blank=True, help_text="System boundary description"
                    ),
                ),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_end", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_end", models.DateField(blank=True, null=True)),
                (
                    "methodology",
                    models.TextField(
                        blank=True, help_text="Assessment methodology description"
                    ),
                ),
                (
                    "test_procedures",
                    models.JSONField(
                        blank=True, default=list, help_text="Test procedure references"
                    ),
                ),
                (
                    "assessor_organization",
                    models.CharField(
                        blank=True,
                        help_text="3PAO or assessor org name",
                        max_length=255,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "artifact_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_plans",
                        to="assessment_artifacts.artifactpackage",
                    ),
                ),
                (
                    "assessor_team",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assessment_plan_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compliance_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_plans",
                        to="core.complianceassessment",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "lead_assessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_assessment_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Plan",
                "verbose_name_plural": "Assessment Plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuthorizationTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "authorization_type",
                    models.CharField(
                        choices=[
                            ("fedramp_jab", "FedRAMP JAB P-ATO"),
                            ("fedramp_agency", "FedRAMP Agency ATO"),
                            ("fedramp_li_saas", "FedRAMP LI-SaaS"),
                            ("disa_il", "DISA Impact Level"),
                            ("internal_ato", "Internal ATO"),
                            ("stateamp", "StateRAMP"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_preparation", "In Preparation"),
                            ("ready_for_assessment", "Ready for Assessment"),
                            ("in_assessment", "In Assessment"),
                            ("in_remediation", "In Remediation"),
                            ("awaiting_authorization", "Awaiting Authorization"),
                            ("authorized", "Authorized"),
                            ("continuous_monitoring", "Continuous Monitoring"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        default="not_started",
                        max_length=30,
                    ),
                ),
                (
                    "impact_level",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Low, Moderate, High, IL4, IL5",
                        max_length=20,
                    ),
                ),
                ("readiness_assessment_date", models.DateField(blank=True, null=True)),
                ("sap_approved_date", models.DateField(blank=True, null=True)),
                ("assessment_start_date", models.DateField(blank=True, null=True)),
                ("assessment_complete_date", models.DateField(blank=True, null=True)),
                ("sar_delivered_date", models.DateField(blank=True, null=True)),
                ("poam_finalized_date", models.DateField(blank=True, null=True)),
                ("authorization_date", models.DateField(blank=True, null=True)),
                ("authorization_expiry", models.DateField(blank=True, null=True)),
                ("conmon_start_date", models.DateField(blank=True, null=True)),
                (
                    "authorizing_official_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("sponsoring_agency", models.CharField(blank=True, max_length=255)),
                (
                    "tpao_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="3PAO Name"
                    ),
                ),
                (
                    "milestones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {name, target_date, actual_date, status}",
                    ),
                ),
                (
                    "authorizing_official",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_systems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compliance_assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_timeline",
                        to="core.complianceassessment",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "tpao_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessed_timelines",
                        to="tprm.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authorization Timeline",
                "verbose_name_plural": "Authorization Timelines",
                "ordering": ["-authorization_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedResponsibilityMatrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "provider_name",
                    models.CharField(
                        help_text="Cloud Service Provider name", max_length=255
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Customer organization name",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        help_text="Current lifecycle status of this matrix",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When this matrix was approved", null=True
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this matrix",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compliance_assessment",
                    models.ForeignKey(
                        help_text="The compliance assessment this matrix belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibility_matrices",
                        to="core.complianceassessment",
                    ),
                ),
                (
                    "customer_entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Entity record for the customer organization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_responsibility_matrices",
                        to="tprm.entity",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "provider_entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Entity record for the cloud service provider",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provided_responsibility_matrices",
                        to="tprm.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Responsibility Matrix",
                "verbose_name_plural": "Shared Responsibility Matrices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "attestation_type",
                    models.CharField(
                        choices=[
                            ("ato_authorization", "ATO Authorization"),
                            ("assessment_approval", "Assessment Approval"),
                            ("evidence_sign_off", "Evidence Sign-Off"),
                            ("poam_approval", "POA&M Approval"),
                            ("risk_acceptance", "Risk Acceptance"),
                            ("policy_approval", "Policy Approval"),
                            ("system_authorization", "System Authorization"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "authority_level",
                    models.CharField(
                        choices=[
                            ("authorizing_official", "Authorizing Official"),
                            ("isso", "ISSO"),
                            ("issm", "ISSM"),
                            ("system_owner", "System Owner"),
                            ("assessor_lead", "Lead Assessor"),
                            ("executive", "Executive"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "statement",
                    models.TextField(
                        help_text="The attestation statement being signed"
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True,
                        help_text="Conditions or caveats on this attestation",
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "attester_title",
                    models.CharField(
                        blank=True,
                        help_text="Official title at time of attestation",
                        max_length=255,
                    ),
                ),
                ("attester_organization", models.CharField(blank=True, max_length=255)),
                ("attested_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "assessment_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attestations",
                        to="core.assessmentplan",
                    ),
                ),
                (
                    "attester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attestations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compliance_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attestations",
                        to="core.complianceassessment",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supporting_evidence",
                    models.ManyToManyField(
                        blank=True, related_name="attestations", to="core.evidence"
                    ),
                ),
            ],
            options={
                "verbose_name": "Attestation",
                "verbose_name_plural": "Attestations",
                "ordering": ["-attested_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_attest_content_ef456f_idx",
                    ),
                    models.Index(
                        fields=["attestation_type", "status"],
                        name="core_attest_attesta_e112a0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ControlOrigination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "origination_type",
                    models.CharField(
                        choices=[
                            ("sp_corporate", "Service Provider Corporate"),
                            ("sp_system", "Service Provider System-Specific"),
                            ("customer_configured", "Configured by Customer"),
                            ("customer_provided", "Provided by Customer"),
                            ("inherited", "Inherited"),
                            ("shared", "Shared"),
                            ("hybrid", "Hybrid"),
                        ],
                        help_text="How this control is originated (FedRAMP origination type)",
                        max_length=30,
                    ),
                ),
                (
                    "implementation_status",
                    models.CharField(
                        choices=[
                            ("implemented", "Implemented"),
                            ("partially_implemented", "Partially Implemented"),
                            ("planned", "Planned"),
                            ("alternative", "Alternative Implementation"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="implemented",
                        help_text="Current implementation status of this control origination",
                        max_length=30,
                    ),
                ),
                (
                    "responsibility_percentage",
                    models.IntegerField(
                        default=100,
                        help_text="Percentage of control responsibility (0-100)",
                    ),
                ),
                (
                    "responsible_role",
                    models.CharField(
                        blank=True,
                        help_text="Role responsible for this origination (e.g., ISSO, System Admin)",
                        max_length=255,
                    ),
                ),
                (
                    "inherited_from_system",
                    models.CharField(
                        blank=True,
                        help_text="Name of parent system (if external)",
                        max_length=255,
                    ),
                ),
                (
                    "implementation_narrative",
                    models.TextField(
                        blank=True, help_text="Control implementation statement"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Control parameter values (e.g., password age=90)",
                    ),
                ),
                (
                    "applied_control",
                    models.ForeignKey(
                        help_text="The applied control this origination describes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="originations",
                        to="core.appliedcontrol",
                    ),
                ),
                (
                    "compliance_assessment",
                    models.ForeignKey(
                        help_text="The compliance assessment context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_originations",
                        to="core.complianceassessment",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "inherited_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent origination this was inherited from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inherited_by",
                        to="core.controlorigination",
                    ),
                ),
                (
                    "responsible_entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Entity responsible for this control origination",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_originations",
                        to="tprm.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control Origination",
                "verbose_name_plural": "Control Originations",
                "ordering": ["applied_control", "origination_type"],
                "unique_together": {
                    ("applied_control", "compliance_assessment", "origination_type")
                },
            },
        ),
        migrations.CreateModel(
            name="ResponsibilityAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "responsible_party",
                    models.CharField(
                        choices=[
                            ("provider_full", "Provider (Full)"),
                            ("customer_full", "Customer (Full)"),
                            ("shared", "Shared"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        help_text="Which party is responsible for this control",
                        max_length=20,
                    ),
                ),
                (
                    "provider_percentage",
                    models.IntegerField(
                        default=0, help_text="Provider responsibility %"
                    ),
                ),
                (
                    "customer_percentage",
                    models.IntegerField(
                        default=0, help_text="Customer responsibility %"
                    ),
                ),
                (
                    "provider_narrative",
                    models.TextField(
                        blank=True, help_text="What the provider does for this control"
                    ),
                ),
                (
                    "customer_narrative",
                    models.TextField(
                        blank=True,
                        help_text="What the customer must do for this control",
                    ),
                ),
                (
                    "customer_controls",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Customer's applied controls implementing this responsibility",
                        related_name="customer_responsibilities",
                        to="core.appliedcontrol",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "provider_controls",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Provider's applied controls implementing this responsibility",
                        related_name="provider_responsibilities",
                        to="core.appliedcontrol",
                    ),
                ),
                (
                    "reference_control",
                    models.ForeignKey(
                        help_text="The reference control being assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibility_assignments",
                        to="core.referencecontrol",
                    ),
                ),
                (
                    "matrix",
                    models.ForeignKey(
                        help_text="The shared responsibility matrix this assignment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.sharedresponsibilitymatrix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsibility Assignment",
                "verbose_name_plural": "Responsibility Assignments",
                "ordering": ["reference_control"],
                "unique_together": {("matrix", "reference_control")},
            },
        ),
    ]
